// SPDX-License-Identifier: MIT
// Copyright wtfsck@protonmail.com
// Copyright iced contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

namespace Iced.UnitTests.Intel {
	static class DecoderConstants {
		internal const ulong DEFAULT_IP16 = 0x0000_0000_0000_7FF0;
		internal const ulong DEFAULT_IP32 = 0x0000_0000_7FFF_FFF0;
		internal const ulong DEFAULT_IP64 = 0x7FFF_FFFF_FFFF_FFF0;
	}
}
