-- SPDX-License-Identifier: MIT
-- Copyright (C) 2018-present iced project and contributors

-- ⚠️This file was generated by GENERATOR!🦹‍♂️

---Mnemonic condition code selector (eg. `JA` / `JNBE`)
return {
	---`JA`, `CMOVA`, `SETA`
	a = 0,
	---`JNBE`, `CMOVNBE`, `SETNBE`
	nbe = 1,
}
