-- SPDX-License-Identifier: MIT
-- Copyright (C) 2018-present iced project and contributors

-- ⚠️This file was generated by GENERATOR!🦹‍♂️

---Mnemonic condition code selector (eg. `JGE` / `JNL`)
return {
	---`JGE`, `CMOVGE`, `SETGE`
	ge = 0,
	---`JNL`, `CMOVNL`, `SETNL`
	nl = 1,
}
