-- SPDX-License-Identifier: MIT
-- Copyright (C) 2018-present iced project and contributors

-- ⚠️This file was generated by GENERATOR!🦹‍♂️

---Mnemonic condition code selector (eg. `JNP` / `JPO`)
return {
	---`JNP`, `CMOVNP`, `SETNP`
	np = 0,
	---`JPO`, `CMOVPO`, `SETPO`
	po = 1,
}
