// SPDX-License-Identifier: MIT
// Copyright wtfsckgh@gmail.com
// Copyright iced contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if DECODER
namespace Iced.Intel.DecoderInternal {
	enum SerializedDataKind : byte {
		HandlerReference,
		ArrayReference,
	}
}
#endif
