// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once
#ifndef ICED_X86_INTERNAL_DECODERCONSTANTS_HPP
#define ICED_X86_INTERNAL_DECODERCONSTANTS_HPP

#include <cstdint>
#include <cstddef>

namespace iced_x86 {
namespace internal {

namespace DecoderConstants {
	constexpr uint64_t DEFAULT_IP16 = 0x7FF0ULL;
	constexpr uint64_t DEFAULT_IP32 = 0x7FFFFFF0ULL;
	constexpr uint64_t DEFAULT_IP64 = 0x7FFFFFFFFFFFFFF0ULL;
} // namespace DecoderConstants

} // namespace internal
} // namespace iced_x86

#endif // ICED_X86_INTERNAL_DECODERCONSTANTS_HPP
