// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once
#ifndef ICED_X86_INTERNAL_MVEXOPCODEHANDLERKIND_HPP
#define ICED_X86_INTERNAL_MVEXOPCODEHANDLERKIND_HPP

#include <cstdint>
#include <cstddef>

namespace iced_x86 {
namespace internal {

enum class MvexOpCodeHandlerKind : uint8_t {
	INVALID = 0,
	INVALID2 = 1,
	DUP = 2,
	HANDLER_REFERENCE = 3,
	ARRAY_REFERENCE = 4,
	RM = 5,
	GROUP = 6,
	W = 7,
	MANDATORY_PREFIX2 = 8,
	EH = 9,
	M = 10,
	MV = 11,
	VW = 12,
	HWIB = 13,
	VWIB = 14,
	VHW = 15,
	VHWIB = 16,
	VKW = 17,
	KHW = 18,
	KHWIB = 19,
	VSIB = 20,
	VSIB_V = 21,
	V_VSIB = 22
};

/// @brief Number of MvexOpCodeHandlerKind enum values.
constexpr std::size_t MVEX_OP_CODE_HANDLER_KIND_COUNT = 23;

} // namespace internal
} // namespace iced_x86

#endif // ICED_X86_INTERNAL_MVEXOPCODEHANDLERKIND_HPP
