// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once
#ifndef ICED_X86_OP_CODE_INFO_FLAGS_HPP
#define ICED_X86_OP_CODE_INFO_FLAGS_HPP

#include <cstdint>

namespace iced_x86 {
namespace internal {

/// @brief OpCodeInfo flags 1
struct OpCodeInfoFlags1 {
	static constexpr uint32_t NONE = 0x00000000U;
	static constexpr uint32_t CPL0_ONLY = 0x00000001U;
	static constexpr uint32_t CPL3_ONLY = 0x00000002U;
	static constexpr uint32_t INPUT_OUTPUT = 0x00000004U;
	static constexpr uint32_t NOP = 0x00000008U;
	static constexpr uint32_t RESERVED_NOP = 0x00000010U;
	static constexpr uint32_t SERIALIZING_INTEL = 0x00000020U;
	static constexpr uint32_t SERIALIZING_AMD = 0x00000040U;
	static constexpr uint32_t MAY_REQUIRE_CPL0 = 0x00000080U;
	static constexpr uint32_t CET_TRACKED = 0x00000100U;
	static constexpr uint32_t NON_TEMPORAL = 0x00000200U;
	static constexpr uint32_t FPU_NO_WAIT = 0x00000400U;
	static constexpr uint32_t IGNORES_MOD_BITS = 0x00000800U;
	static constexpr uint32_t NO66 = 0x00001000U;
	static constexpr uint32_t NFX = 0x00002000U;
	static constexpr uint32_t REQUIRES_UNIQUE_REG_NUMS = 0x00004000U;
	static constexpr uint32_t PRIVILEGED = 0x00008000U;
	static constexpr uint32_t SAVE_RESTORE = 0x00010000U;
	static constexpr uint32_t STACK_INSTRUCTION = 0x00020000U;
	static constexpr uint32_t IGNORES_SEGMENT = 0x00040000U;
	static constexpr uint32_t OP_MASK_READ_WRITE = 0x00080000U;
	static constexpr uint32_t MOD_REG_RM_STRING = 0x00100000U;
	static constexpr uint32_t DEC_OPTION_VALUE_MASK = 0x0000001FU;
	static constexpr uint32_t DEC_OPTION_VALUE_SHIFT = 0x00000015U;
	static constexpr uint32_t FORCE_OP_SIZE64 = 0x40000000U;
	static constexpr uint32_t REQUIRES_UNIQUE_DEST_REG_NUM = 0x80000000U;
};

/// @brief OpCodeInfo flags 2
struct OpCodeInfoFlags2 {
	static constexpr uint32_t NONE = 0x00000000U;
	static constexpr uint32_t REAL_MODE = 0x00000001U;
	static constexpr uint32_t PROTECTED_MODE = 0x00000002U;
	static constexpr uint32_t VIRTUAL8086_MODE = 0x00000004U;
	static constexpr uint32_t COMPATIBILITY_MODE = 0x00000008U;
	static constexpr uint32_t USE_OUTSIDE_SMM = 0x00000010U;
	static constexpr uint32_t USE_IN_SMM = 0x00000020U;
	static constexpr uint32_t USE_OUTSIDE_ENCLAVE_SGX = 0x00000040U;
	static constexpr uint32_t USE_IN_ENCLAVE_SGX1 = 0x00000080U;
	static constexpr uint32_t USE_IN_ENCLAVE_SGX2 = 0x00000100U;
	static constexpr uint32_t USE_OUTSIDE_VMX_OP = 0x00000200U;
	static constexpr uint32_t USE_IN_VMX_ROOT_OP = 0x00000400U;
	static constexpr uint32_t USE_IN_VMX_NON_ROOT_OP = 0x00000800U;
	static constexpr uint32_t USE_OUTSIDE_SEAM = 0x00001000U;
	static constexpr uint32_t USE_IN_SEAM = 0x00002000U;
	static constexpr uint32_t TDX_NON_ROOT_GEN_UD = 0x00004000U;
	static constexpr uint32_t TDX_NON_ROOT_GEN_VE = 0x00008000U;
	static constexpr uint32_t TDX_NON_ROOT_MAY_GEN_EX = 0x00010000U;
	static constexpr uint32_t INTEL_VM_EXIT = 0x00020000U;
	static constexpr uint32_t INTEL_MAY_VM_EXIT = 0x00040000U;
	static constexpr uint32_t INTEL_SMM_VM_EXIT = 0x00080000U;
	static constexpr uint32_t AMD_VM_EXIT = 0x00100000U;
	static constexpr uint32_t AMD_MAY_VM_EXIT = 0x00200000U;
	static constexpr uint32_t TSX_ABORT = 0x00400000U;
	static constexpr uint32_t TSX_IMPL_ABORT = 0x00800000U;
	static constexpr uint32_t TSX_MAY_ABORT = 0x01000000U;
	static constexpr uint32_t INTEL_DECODER16OR32 = 0x02000000U;
	static constexpr uint32_t INTEL_DECODER64 = 0x04000000U;
	static constexpr uint32_t AMD_DECODER16OR32 = 0x08000000U;
	static constexpr uint32_t AMD_DECODER64 = 0x10000000U;
	static constexpr uint32_t INSTR_STR_FMT_OPTION_MASK = 0x00000007U;
	static constexpr uint32_t INSTR_STR_FMT_OPTION_SHIFT = 0x0000001DU;
};

} // namespace internal
} // namespace iced_x86

#endif // ICED_X86_OP_CODE_INFO_FLAGS_HPP
