/*
Copyright (C) 2018-2019 de4dot@gmail.com

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

using System;
using Generator.Enums;

namespace Generator.Tables {
	sealed class RegisterInfo {
		public EnumValue Register { get; }
		public EnumValue Base { get; }
		public EnumValue FullRegister { get; }
		public int Size { get; }

		public RegisterInfo(EnumValue register, EnumValue @base, EnumValue fullRegister, int size) {
			Register = register;
			Base = @base;
			FullRegister = fullRegister;
			Size = size;
		}
	}

	static class RegisterInfoTable {
		public static RegisterInfo[] Data = CreateData();

		static RegisterInfo[] CreateData() {
			var reg = RegisterEnum.Instance;
			var result = new RegisterInfo[RegisterEnum.NumValues] {
				new RegisterInfo(reg["None"], reg["None"], reg["None"], 0),
				new RegisterInfo(reg["AL"], reg["AL"], reg["RAX"], 1),
				new RegisterInfo(reg["CL"], reg["AL"], reg["RCX"], 1),
				new RegisterInfo(reg["DL"], reg["AL"], reg["RDX"], 1),
				new RegisterInfo(reg["BL"], reg["AL"], reg["RBX"], 1),
				new RegisterInfo(reg["AH"], reg["AL"], reg["RAX"], 1),
				new RegisterInfo(reg["CH"], reg["AL"], reg["RCX"], 1),
				new RegisterInfo(reg["DH"], reg["AL"], reg["RDX"], 1),
				new RegisterInfo(reg["BH"], reg["AL"], reg["RBX"], 1),
				new RegisterInfo(reg["SPL"], reg["AL"], reg["RSP"], 1),
				new RegisterInfo(reg["BPL"], reg["AL"], reg["RBP"], 1),
				new RegisterInfo(reg["SIL"], reg["AL"], reg["RSI"], 1),
				new RegisterInfo(reg["DIL"], reg["AL"], reg["RDI"], 1),
				new RegisterInfo(reg["R8L"], reg["AL"], reg["R8"], 1),
				new RegisterInfo(reg["R9L"], reg["AL"], reg["R9"], 1),
				new RegisterInfo(reg["R10L"], reg["AL"], reg["R10"], 1),
				new RegisterInfo(reg["R11L"], reg["AL"], reg["R11"], 1),
				new RegisterInfo(reg["R12L"], reg["AL"], reg["R12"], 1),
				new RegisterInfo(reg["R13L"], reg["AL"], reg["R13"], 1),
				new RegisterInfo(reg["R14L"], reg["AL"], reg["R14"], 1),
				new RegisterInfo(reg["R15L"], reg["AL"], reg["R15"], 1),
				new RegisterInfo(reg["AX"], reg["AX"], reg["RAX"], 2),
				new RegisterInfo(reg["CX"], reg["AX"], reg["RCX"], 2),
				new RegisterInfo(reg["DX"], reg["AX"], reg["RDX"], 2),
				new RegisterInfo(reg["BX"], reg["AX"], reg["RBX"], 2),
				new RegisterInfo(reg["SP"], reg["AX"], reg["RSP"], 2),
				new RegisterInfo(reg["BP"], reg["AX"], reg["RBP"], 2),
				new RegisterInfo(reg["SI"], reg["AX"], reg["RSI"], 2),
				new RegisterInfo(reg["DI"], reg["AX"], reg["RDI"], 2),
				new RegisterInfo(reg["R8W"], reg["AX"], reg["R8"], 2),
				new RegisterInfo(reg["R9W"], reg["AX"], reg["R9"], 2),
				new RegisterInfo(reg["R10W"], reg["AX"], reg["R10"], 2),
				new RegisterInfo(reg["R11W"], reg["AX"], reg["R11"], 2),
				new RegisterInfo(reg["R12W"], reg["AX"], reg["R12"], 2),
				new RegisterInfo(reg["R13W"], reg["AX"], reg["R13"], 2),
				new RegisterInfo(reg["R14W"], reg["AX"], reg["R14"], 2),
				new RegisterInfo(reg["R15W"], reg["AX"], reg["R15"], 2),
				new RegisterInfo(reg["EAX"], reg["EAX"], reg["RAX"], 4),
				new RegisterInfo(reg["ECX"], reg["EAX"], reg["RCX"], 4),
				new RegisterInfo(reg["EDX"], reg["EAX"], reg["RDX"], 4),
				new RegisterInfo(reg["EBX"], reg["EAX"], reg["RBX"], 4),
				new RegisterInfo(reg["ESP"], reg["EAX"], reg["RSP"], 4),
				new RegisterInfo(reg["EBP"], reg["EAX"], reg["RBP"], 4),
				new RegisterInfo(reg["ESI"], reg["EAX"], reg["RSI"], 4),
				new RegisterInfo(reg["EDI"], reg["EAX"], reg["RDI"], 4),
				new RegisterInfo(reg["R8D"], reg["EAX"], reg["R8"], 4),
				new RegisterInfo(reg["R9D"], reg["EAX"], reg["R9"], 4),
				new RegisterInfo(reg["R10D"], reg["EAX"], reg["R10"], 4),
				new RegisterInfo(reg["R11D"], reg["EAX"], reg["R11"], 4),
				new RegisterInfo(reg["R12D"], reg["EAX"], reg["R12"], 4),
				new RegisterInfo(reg["R13D"], reg["EAX"], reg["R13"], 4),
				new RegisterInfo(reg["R14D"], reg["EAX"], reg["R14"], 4),
				new RegisterInfo(reg["R15D"], reg["EAX"], reg["R15"], 4),
				new RegisterInfo(reg["RAX"], reg["RAX"], reg["RAX"], 8),
				new RegisterInfo(reg["RCX"], reg["RAX"], reg["RCX"], 8),
				new RegisterInfo(reg["RDX"], reg["RAX"], reg["RDX"], 8),
				new RegisterInfo(reg["RBX"], reg["RAX"], reg["RBX"], 8),
				new RegisterInfo(reg["RSP"], reg["RAX"], reg["RSP"], 8),
				new RegisterInfo(reg["RBP"], reg["RAX"], reg["RBP"], 8),
				new RegisterInfo(reg["RSI"], reg["RAX"], reg["RSI"], 8),
				new RegisterInfo(reg["RDI"], reg["RAX"], reg["RDI"], 8),
				new RegisterInfo(reg["R8"], reg["RAX"], reg["R8"], 8),
				new RegisterInfo(reg["R9"], reg["RAX"], reg["R9"], 8),
				new RegisterInfo(reg["R10"], reg["RAX"], reg["R10"], 8),
				new RegisterInfo(reg["R11"], reg["RAX"], reg["R11"], 8),
				new RegisterInfo(reg["R12"], reg["RAX"], reg["R12"], 8),
				new RegisterInfo(reg["R13"], reg["RAX"], reg["R13"], 8),
				new RegisterInfo(reg["R14"], reg["RAX"], reg["R14"], 8),
				new RegisterInfo(reg["R15"], reg["RAX"], reg["R15"], 8),
				new RegisterInfo(reg["EIP"], reg["EIP"], reg["RIP"], 4),
				new RegisterInfo(reg["RIP"], reg["EIP"], reg["RIP"], 8),
				new RegisterInfo(reg["ES"], reg["ES"], reg["ES"], 2),
				new RegisterInfo(reg["CS"], reg["ES"], reg["CS"], 2),
				new RegisterInfo(reg["SS"], reg["ES"], reg["SS"], 2),
				new RegisterInfo(reg["DS"], reg["ES"], reg["DS"], 2),
				new RegisterInfo(reg["FS"], reg["ES"], reg["FS"], 2),
				new RegisterInfo(reg["GS"], reg["ES"], reg["GS"], 2),
				new RegisterInfo(reg["XMM0"], reg["XMM0"], reg["ZMM0"], 16),
				new RegisterInfo(reg["XMM1"], reg["XMM0"], reg["ZMM1"], 16),
				new RegisterInfo(reg["XMM2"], reg["XMM0"], reg["ZMM2"], 16),
				new RegisterInfo(reg["XMM3"], reg["XMM0"], reg["ZMM3"], 16),
				new RegisterInfo(reg["XMM4"], reg["XMM0"], reg["ZMM4"], 16),
				new RegisterInfo(reg["XMM5"], reg["XMM0"], reg["ZMM5"], 16),
				new RegisterInfo(reg["XMM6"], reg["XMM0"], reg["ZMM6"], 16),
				new RegisterInfo(reg["XMM7"], reg["XMM0"], reg["ZMM7"], 16),
				new RegisterInfo(reg["XMM8"], reg["XMM0"], reg["ZMM8"], 16),
				new RegisterInfo(reg["XMM9"], reg["XMM0"], reg["ZMM9"], 16),
				new RegisterInfo(reg["XMM10"], reg["XMM0"], reg["ZMM10"], 16),
				new RegisterInfo(reg["XMM11"], reg["XMM0"], reg["ZMM11"], 16),
				new RegisterInfo(reg["XMM12"], reg["XMM0"], reg["ZMM12"], 16),
				new RegisterInfo(reg["XMM13"], reg["XMM0"], reg["ZMM13"], 16),
				new RegisterInfo(reg["XMM14"], reg["XMM0"], reg["ZMM14"], 16),
				new RegisterInfo(reg["XMM15"], reg["XMM0"], reg["ZMM15"], 16),
				new RegisterInfo(reg["XMM16"], reg["XMM0"], reg["ZMM16"], 16),
				new RegisterInfo(reg["XMM17"], reg["XMM0"], reg["ZMM17"], 16),
				new RegisterInfo(reg["XMM18"], reg["XMM0"], reg["ZMM18"], 16),
				new RegisterInfo(reg["XMM19"], reg["XMM0"], reg["ZMM19"], 16),
				new RegisterInfo(reg["XMM20"], reg["XMM0"], reg["ZMM20"], 16),
				new RegisterInfo(reg["XMM21"], reg["XMM0"], reg["ZMM21"], 16),
				new RegisterInfo(reg["XMM22"], reg["XMM0"], reg["ZMM22"], 16),
				new RegisterInfo(reg["XMM23"], reg["XMM0"], reg["ZMM23"], 16),
				new RegisterInfo(reg["XMM24"], reg["XMM0"], reg["ZMM24"], 16),
				new RegisterInfo(reg["XMM25"], reg["XMM0"], reg["ZMM25"], 16),
				new RegisterInfo(reg["XMM26"], reg["XMM0"], reg["ZMM26"], 16),
				new RegisterInfo(reg["XMM27"], reg["XMM0"], reg["ZMM27"], 16),
				new RegisterInfo(reg["XMM28"], reg["XMM0"], reg["ZMM28"], 16),
				new RegisterInfo(reg["XMM29"], reg["XMM0"], reg["ZMM29"], 16),
				new RegisterInfo(reg["XMM30"], reg["XMM0"], reg["ZMM30"], 16),
				new RegisterInfo(reg["XMM31"], reg["XMM0"], reg["ZMM31"], 16),
				new RegisterInfo(reg["YMM0"], reg["YMM0"], reg["ZMM0"], 32),
				new RegisterInfo(reg["YMM1"], reg["YMM0"], reg["ZMM1"], 32),
				new RegisterInfo(reg["YMM2"], reg["YMM0"], reg["ZMM2"], 32),
				new RegisterInfo(reg["YMM3"], reg["YMM0"], reg["ZMM3"], 32),
				new RegisterInfo(reg["YMM4"], reg["YMM0"], reg["ZMM4"], 32),
				new RegisterInfo(reg["YMM5"], reg["YMM0"], reg["ZMM5"], 32),
				new RegisterInfo(reg["YMM6"], reg["YMM0"], reg["ZMM6"], 32),
				new RegisterInfo(reg["YMM7"], reg["YMM0"], reg["ZMM7"], 32),
				new RegisterInfo(reg["YMM8"], reg["YMM0"], reg["ZMM8"], 32),
				new RegisterInfo(reg["YMM9"], reg["YMM0"], reg["ZMM9"], 32),
				new RegisterInfo(reg["YMM10"], reg["YMM0"], reg["ZMM10"], 32),
				new RegisterInfo(reg["YMM11"], reg["YMM0"], reg["ZMM11"], 32),
				new RegisterInfo(reg["YMM12"], reg["YMM0"], reg["ZMM12"], 32),
				new RegisterInfo(reg["YMM13"], reg["YMM0"], reg["ZMM13"], 32),
				new RegisterInfo(reg["YMM14"], reg["YMM0"], reg["ZMM14"], 32),
				new RegisterInfo(reg["YMM15"], reg["YMM0"], reg["ZMM15"], 32),
				new RegisterInfo(reg["YMM16"], reg["YMM0"], reg["ZMM16"], 32),
				new RegisterInfo(reg["YMM17"], reg["YMM0"], reg["ZMM17"], 32),
				new RegisterInfo(reg["YMM18"], reg["YMM0"], reg["ZMM18"], 32),
				new RegisterInfo(reg["YMM19"], reg["YMM0"], reg["ZMM19"], 32),
				new RegisterInfo(reg["YMM20"], reg["YMM0"], reg["ZMM20"], 32),
				new RegisterInfo(reg["YMM21"], reg["YMM0"], reg["ZMM21"], 32),
				new RegisterInfo(reg["YMM22"], reg["YMM0"], reg["ZMM22"], 32),
				new RegisterInfo(reg["YMM23"], reg["YMM0"], reg["ZMM23"], 32),
				new RegisterInfo(reg["YMM24"], reg["YMM0"], reg["ZMM24"], 32),
				new RegisterInfo(reg["YMM25"], reg["YMM0"], reg["ZMM25"], 32),
				new RegisterInfo(reg["YMM26"], reg["YMM0"], reg["ZMM26"], 32),
				new RegisterInfo(reg["YMM27"], reg["YMM0"], reg["ZMM27"], 32),
				new RegisterInfo(reg["YMM28"], reg["YMM0"], reg["ZMM28"], 32),
				new RegisterInfo(reg["YMM29"], reg["YMM0"], reg["ZMM29"], 32),
				new RegisterInfo(reg["YMM30"], reg["YMM0"], reg["ZMM30"], 32),
				new RegisterInfo(reg["YMM31"], reg["YMM0"], reg["ZMM31"], 32),
				new RegisterInfo(reg["ZMM0"], reg["ZMM0"], reg["ZMM0"], 64),
				new RegisterInfo(reg["ZMM1"], reg["ZMM0"], reg["ZMM1"], 64),
				new RegisterInfo(reg["ZMM2"], reg["ZMM0"], reg["ZMM2"], 64),
				new RegisterInfo(reg["ZMM3"], reg["ZMM0"], reg["ZMM3"], 64),
				new RegisterInfo(reg["ZMM4"], reg["ZMM0"], reg["ZMM4"], 64),
				new RegisterInfo(reg["ZMM5"], reg["ZMM0"], reg["ZMM5"], 64),
				new RegisterInfo(reg["ZMM6"], reg["ZMM0"], reg["ZMM6"], 64),
				new RegisterInfo(reg["ZMM7"], reg["ZMM0"], reg["ZMM7"], 64),
				new RegisterInfo(reg["ZMM8"], reg["ZMM0"], reg["ZMM8"], 64),
				new RegisterInfo(reg["ZMM9"], reg["ZMM0"], reg["ZMM9"], 64),
				new RegisterInfo(reg["ZMM10"], reg["ZMM0"], reg["ZMM10"], 64),
				new RegisterInfo(reg["ZMM11"], reg["ZMM0"], reg["ZMM11"], 64),
				new RegisterInfo(reg["ZMM12"], reg["ZMM0"], reg["ZMM12"], 64),
				new RegisterInfo(reg["ZMM13"], reg["ZMM0"], reg["ZMM13"], 64),
				new RegisterInfo(reg["ZMM14"], reg["ZMM0"], reg["ZMM14"], 64),
				new RegisterInfo(reg["ZMM15"], reg["ZMM0"], reg["ZMM15"], 64),
				new RegisterInfo(reg["ZMM16"], reg["ZMM0"], reg["ZMM16"], 64),
				new RegisterInfo(reg["ZMM17"], reg["ZMM0"], reg["ZMM17"], 64),
				new RegisterInfo(reg["ZMM18"], reg["ZMM0"], reg["ZMM18"], 64),
				new RegisterInfo(reg["ZMM19"], reg["ZMM0"], reg["ZMM19"], 64),
				new RegisterInfo(reg["ZMM20"], reg["ZMM0"], reg["ZMM20"], 64),
				new RegisterInfo(reg["ZMM21"], reg["ZMM0"], reg["ZMM21"], 64),
				new RegisterInfo(reg["ZMM22"], reg["ZMM0"], reg["ZMM22"], 64),
				new RegisterInfo(reg["ZMM23"], reg["ZMM0"], reg["ZMM23"], 64),
				new RegisterInfo(reg["ZMM24"], reg["ZMM0"], reg["ZMM24"], 64),
				new RegisterInfo(reg["ZMM25"], reg["ZMM0"], reg["ZMM25"], 64),
				new RegisterInfo(reg["ZMM26"], reg["ZMM0"], reg["ZMM26"], 64),
				new RegisterInfo(reg["ZMM27"], reg["ZMM0"], reg["ZMM27"], 64),
				new RegisterInfo(reg["ZMM28"], reg["ZMM0"], reg["ZMM28"], 64),
				new RegisterInfo(reg["ZMM29"], reg["ZMM0"], reg["ZMM29"], 64),
				new RegisterInfo(reg["ZMM30"], reg["ZMM0"], reg["ZMM30"], 64),
				new RegisterInfo(reg["ZMM31"], reg["ZMM0"], reg["ZMM31"], 64),
				new RegisterInfo(reg["K0"], reg["K0"], reg["K0"], 8),
				new RegisterInfo(reg["K1"], reg["K0"], reg["K1"], 8),
				new RegisterInfo(reg["K2"], reg["K0"], reg["K2"], 8),
				new RegisterInfo(reg["K3"], reg["K0"], reg["K3"], 8),
				new RegisterInfo(reg["K4"], reg["K0"], reg["K4"], 8),
				new RegisterInfo(reg["K5"], reg["K0"], reg["K5"], 8),
				new RegisterInfo(reg["K6"], reg["K0"], reg["K6"], 8),
				new RegisterInfo(reg["K7"], reg["K0"], reg["K7"], 8),
				new RegisterInfo(reg["BND0"], reg["BND0"], reg["BND0"], 16),
				new RegisterInfo(reg["BND1"], reg["BND0"], reg["BND1"], 16),
				new RegisterInfo(reg["BND2"], reg["BND0"], reg["BND2"], 16),
				new RegisterInfo(reg["BND3"], reg["BND0"], reg["BND3"], 16),
				new RegisterInfo(reg["CR0"], reg["CR0"], reg["CR0"], 8),
				new RegisterInfo(reg["CR1"], reg["CR0"], reg["CR1"], 8),
				new RegisterInfo(reg["CR2"], reg["CR0"], reg["CR2"], 8),
				new RegisterInfo(reg["CR3"], reg["CR0"], reg["CR3"], 8),
				new RegisterInfo(reg["CR4"], reg["CR0"], reg["CR4"], 8),
				new RegisterInfo(reg["CR5"], reg["CR0"], reg["CR5"], 8),
				new RegisterInfo(reg["CR6"], reg["CR0"], reg["CR6"], 8),
				new RegisterInfo(reg["CR7"], reg["CR0"], reg["CR7"], 8),
				new RegisterInfo(reg["CR8"], reg["CR0"], reg["CR8"], 8),
				new RegisterInfo(reg["CR9"], reg["CR0"], reg["CR9"], 8),
				new RegisterInfo(reg["CR10"], reg["CR0"], reg["CR10"], 8),
				new RegisterInfo(reg["CR11"], reg["CR0"], reg["CR11"], 8),
				new RegisterInfo(reg["CR12"], reg["CR0"], reg["CR12"], 8),
				new RegisterInfo(reg["CR13"], reg["CR0"], reg["CR13"], 8),
				new RegisterInfo(reg["CR14"], reg["CR0"], reg["CR14"], 8),
				new RegisterInfo(reg["CR15"], reg["CR0"], reg["CR15"], 8),
				new RegisterInfo(reg["DR0"], reg["DR0"], reg["DR0"], 8),
				new RegisterInfo(reg["DR1"], reg["DR0"], reg["DR1"], 8),
				new RegisterInfo(reg["DR2"], reg["DR0"], reg["DR2"], 8),
				new RegisterInfo(reg["DR3"], reg["DR0"], reg["DR3"], 8),
				new RegisterInfo(reg["DR4"], reg["DR0"], reg["DR4"], 8),
				new RegisterInfo(reg["DR5"], reg["DR0"], reg["DR5"], 8),
				new RegisterInfo(reg["DR6"], reg["DR0"], reg["DR6"], 8),
				new RegisterInfo(reg["DR7"], reg["DR0"], reg["DR7"], 8),
				new RegisterInfo(reg["DR8"], reg["DR0"], reg["DR8"], 8),
				new RegisterInfo(reg["DR9"], reg["DR0"], reg["DR9"], 8),
				new RegisterInfo(reg["DR10"], reg["DR0"], reg["DR10"], 8),
				new RegisterInfo(reg["DR11"], reg["DR0"], reg["DR11"], 8),
				new RegisterInfo(reg["DR12"], reg["DR0"], reg["DR12"], 8),
				new RegisterInfo(reg["DR13"], reg["DR0"], reg["DR13"], 8),
				new RegisterInfo(reg["DR14"], reg["DR0"], reg["DR14"], 8),
				new RegisterInfo(reg["DR15"], reg["DR0"], reg["DR15"], 8),
				new RegisterInfo(reg["ST0"], reg["ST0"], reg["ST0"], 10),
				new RegisterInfo(reg["ST1"], reg["ST0"], reg["ST1"], 10),
				new RegisterInfo(reg["ST2"], reg["ST0"], reg["ST2"], 10),
				new RegisterInfo(reg["ST3"], reg["ST0"], reg["ST3"], 10),
				new RegisterInfo(reg["ST4"], reg["ST0"], reg["ST4"], 10),
				new RegisterInfo(reg["ST5"], reg["ST0"], reg["ST5"], 10),
				new RegisterInfo(reg["ST6"], reg["ST0"], reg["ST6"], 10),
				new RegisterInfo(reg["ST7"], reg["ST0"], reg["ST7"], 10),
				new RegisterInfo(reg["MM0"], reg["MM0"], reg["MM0"], 8),
				new RegisterInfo(reg["MM1"], reg["MM0"], reg["MM1"], 8),
				new RegisterInfo(reg["MM2"], reg["MM0"], reg["MM2"], 8),
				new RegisterInfo(reg["MM3"], reg["MM0"], reg["MM3"], 8),
				new RegisterInfo(reg["MM4"], reg["MM0"], reg["MM4"], 8),
				new RegisterInfo(reg["MM5"], reg["MM0"], reg["MM5"], 8),
				new RegisterInfo(reg["MM6"], reg["MM0"], reg["MM6"], 8),
				new RegisterInfo(reg["MM7"], reg["MM0"], reg["MM7"], 8),
				new RegisterInfo(reg["TR0"], reg["TR0"], reg["TR0"], 4),
				new RegisterInfo(reg["TR1"], reg["TR0"], reg["TR1"], 4),
				new RegisterInfo(reg["TR2"], reg["TR0"], reg["TR2"], 4),
				new RegisterInfo(reg["TR3"], reg["TR0"], reg["TR3"], 4),
				new RegisterInfo(reg["TR4"], reg["TR0"], reg["TR4"], 4),
				new RegisterInfo(reg["TR5"], reg["TR0"], reg["TR5"], 4),
				new RegisterInfo(reg["TR6"], reg["TR0"], reg["TR6"], 4),
				new RegisterInfo(reg["TR7"], reg["TR0"], reg["TR7"], 4),
			};
			if (result.Length != reg.Values.Length)
				throw new InvalidOperationException();
			Array.Sort(result, (a, b) => a.Register.Value.CompareTo(b.Register.Value));
			return result;
		}
	}
}
