/*
    Copyright (C) 2018-2019 de4dot@gmail.com

    This file is part of Iced.

    Iced is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Iced is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Iced.  If not, see <https://www.gnu.org/licenses/>.
*/

#if !NO_MASM_FORMATTER && !NO_FORMATTER
using System.Collections.Generic;
using Xunit;

namespace Iced.UnitTests.Intel.FormatterTests.Masm {
	public sealed class MasmFormatterTest64_ForceMemSize_008 : FormatterTest {
		[Theory]
		[MemberData(nameof(Format_Data))]
		void Format(int index, InstructionInfo info, string formattedString) => FormatBase(index, info, formattedString, MasmFormatterFactory.Create_ForceMemSize());
		public static IEnumerable<object[]> Format_Data => GetFormatData(infos, formattedStrings);

		static readonly InstructionInfo[] infos = InstructionInfos64_008.AllInfos;
		static readonly string[] formattedStrings = new string[InstructionInfos64_008.AllInfos_Length] {
			"vpcompressb zmm19{k3}{z},zmm10",
			"vpcompressb zmmword ptr [rax+1],zmm2",
			"vpcompressw xmm3,xmm2",
			"vpcompressw xmmword ptr [rax+2],xmm2",
			"vpcompressw ymm3{k3},ymm2",
			"vpcompressw ymmword ptr [rax+2]{k3},ymm2",
			"vpcompressw zmm19{k3}{z},zmm10",
			"vpcompressw zmmword ptr [rax+2],zmm2",
			"vpshldvw xmm2{k3},xmm6,xmm3",
			"vpshldvw xmm2,xmm6,xmmword ptr [rax+10h]",
			"vpshldvw ymm2{k3},ymm6,ymm3",
			"vpshldvw ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshldvw zmm18{k3}{z},zmm14,zmm3",
			"vpshldvw zmm2{k3}{z},zmm6,zmmword ptr [rax+40h]",
			"vpshldvd xmm18{k3},xmm14,xmm3",
			"vpshldvd xmm2,xmm6,xmmword ptr [rax+10h]",
			"vpshldvd xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vpshldvd ymm18{k3},ymm14,ymm3",
			"vpshldvd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshldvd ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vpshldvd zmm2{k3}{z},zmm6,zmm3",
			"vpshldvd zmm2,zmm6,zmmword ptr [rax+40h]",
			"vpshldvd zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"vpshldvq xmm18{k3},xmm14,xmm3",
			"vpshldvq xmm2,xmm6,xmmword ptr [rax+10h]",
			"vpshldvq xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vpshldvq ymm18{k3},ymm14,ymm3",
			"vpshldvq ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshldvq ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vpshldvq zmm2{k3}{z},zmm6,zmm3",
			"vpshldvq zmm2,zmm6,zmmword ptr [rax+40h]",
			"vpshldvq zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"vpshrdvw xmm2{k3},xmm6,xmm3",
			"vpshrdvw xmm2,xmm6,xmmword ptr [rax+10h]",
			"vpshrdvw ymm2{k3},ymm6,ymm3",
			"vpshrdvw ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshrdvw zmm18{k3}{z},zmm14,zmm3",
			"vpshrdvw zmm2{k3}{z},zmm6,zmmword ptr [rax+40h]",
			"vpshrdvd xmm18{k3},xmm14,xmm3",
			"vpshrdvd xmm2,xmm6,xmmword ptr [rax+10h]",
			"vpshrdvd xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vpshrdvd ymm18{k3},ymm14,ymm3",
			"vpshrdvd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshrdvd ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vpshrdvd zmm2{k3}{z},zmm6,zmm3",
			"vpshrdvd zmm2,zmm6,zmmword ptr [rax+40h]",
			"vpshrdvd zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"vpshrdvq xmm18{k3},xmm14,xmm3",
			"vpshrdvq xmm2,xmm6,xmmword ptr [rax+10h]",
			"vpshrdvq xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vpshrdvq ymm18{k3},ymm14,ymm3",
			"vpshrdvq ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshrdvq ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vpshrdvq zmm2{k3}{z},zmm6,zmm3",
			"vpshrdvq zmm2,zmm6,zmmword ptr [rax+40h]",
			"vpshrdvq zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"vpshufbitqmb k2{k3},xmm6,xmm3",
			"vpshufbitqmb k2,xmm6,xmmword ptr [rax+10h]",
			"vpshufbitqmb k2{k3},ymm6,ymm3",
			"vpshufbitqmb k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpshufbitqmb k2{k3},zmm6,zmm3",
			"vpshufbitqmb k2,zmm6,zmmword ptr [rax+40h]",
			"gf2p8mulb xmm1,xmm5",
			"gf2p8mulb xmm1,xmmword ptr [rax]",
			"vgf2p8mulb xmm2,xmm6,xmm3",
			"vgf2p8mulb xmm2,xmm6,xmmword ptr [rax]",
			"vgf2p8mulb ymm2,ymm6,ymm3",
			"vgf2p8mulb ymm2,ymm6,ymmword ptr [rax]",
			"vgf2p8mulb xmm2{k3},xmm6,xmm3",
			"vgf2p8mulb xmm2,xmm6,xmmword ptr [rax+10h]",
			"vgf2p8mulb ymm2{k3},ymm6,ymm3",
			"vgf2p8mulb ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vgf2p8mulb zmm18{k3}{z},zmm14,zmm3",
			"vgf2p8mulb zmm2{k5}{z},zmm6,zmmword ptr [rax+40h]",
			"vaesenc ymm2,ymm6,ymm3",
			"vaesenc ymm2,ymm6,ymmword ptr [rax]",
			"vaesenc xmm2,xmm6,xmm3",
			"vaesenc xmm2,xmm6,xmmword ptr [rax+10h]",
			"vaesenc ymm2,ymm6,ymm3",
			"vaesenc ymm2,ymm6,ymmword ptr [rax+20h]",
			"vaesenc zmm2,zmm6,zmm3",
			"vaesenc zmm2,zmm6,zmmword ptr [rax+40h]",
			"vaesenclast ymm2,ymm6,ymm3",
			"vaesenclast ymm2,ymm6,ymmword ptr [rax]",
			"vaesenclast xmm2,xmm6,xmm3",
			"vaesenclast xmm2,xmm6,xmmword ptr [rax+10h]",
			"vaesenclast ymm2,ymm6,ymm3",
			"vaesenclast ymm2,ymm6,ymmword ptr [rax+20h]",
			"vaesenclast zmm2,zmm6,zmm3",
			"vaesenclast zmm2,zmm6,zmmword ptr [rax+40h]",
			"vaesdec ymm2,ymm6,ymm3",
			"vaesdec ymm2,ymm6,ymmword ptr [rax]",
			"vaesdec xmm2,xmm6,xmm3",
			"vaesdec xmm2,xmm6,xmmword ptr [rax+10h]",
			"vaesdec ymm2,ymm6,ymm3",
			"vaesdec ymm2,ymm6,ymmword ptr [rax+20h]",
			"vaesdec zmm2,zmm6,zmm3",
			"vaesdec zmm2,zmm6,zmmword ptr [rax+40h]",
			"vaesdeclast ymm2,ymm6,ymm3",
			"vaesdeclast ymm2,ymm6,ymmword ptr [rax]",
			"vaesdeclast xmm2,xmm6,xmm3",
			"vaesdeclast xmm2,xmm6,xmmword ptr [rax+10h]",
			"vaesdeclast ymm2,ymm6,ymm3",
			"vaesdeclast ymm2,ymm6,ymmword ptr [rax+20h]",
			"vaesdeclast zmm2,zmm6,zmm3",
			"vaesdeclast zmm2,zmm6,zmmword ptr [rax+40h]",
			"wrussd dword ptr [rax],ebx",
			"wrussq qword ptr [rax],rbx",
			"wrssd dword ptr [rax],ebx",
			"wrssq qword ptr [rax],rbx",
			"movdir64b ebx,zmmword ptr [eax]",
			"movdir64b rbx,zmmword ptr [rax]",
			"movdiri dword ptr [rax],ebx",
			"movdiri qword ptr [rax],rbx",
			"vpclmulqdq ymm2,ymm6,ymm3,-5Bh",
			"vpclmulqdq ymm2,ymm6,ymmword ptr [rax],-5Bh",
			"vpclmulqdq xmm2,xmm6,xmm3,-5Bh",
			"vpclmulqdq xmm2,xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpclmulqdq ymm2,ymm6,ymm3,-5Bh",
			"vpclmulqdq ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpclmulqdq zmm2,zmm6,zmm3,-5Bh",
			"vpclmulqdq zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshldw xmm2{k3},xmm6,xmm3,-5Bh",
			"vpshldw xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpshldw ymm18{k3}{z},ymm14,ymm3,-5Bh",
			"vpshldw ymm2{k5}{z},ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpshldw zmm2{k3},zmm6,zmm3,-5Bh",
			"vpshldw zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshldd xmm2{k3},xmm6,xmm3,-5Bh",
			"vpshldd xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpshldd xmm2{k5}{z},xmm6,dword bcst [rax+4],-5Bh",
			"vpshldd ymm2{k3}{z},ymm6,ymm3,-5Bh",
			"vpshldd ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpshldd ymm2{k5}{z},ymm6,dword bcst [rax+4],-5Bh",
			"vpshldd zmm2{k3},zmm6,zmm3,-5Bh",
			"vpshldd zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshldd zmm2{k5}{z},zmm6,dword bcst [rax+4],-5Bh",
			"vpshldq xmm18{k3},xmm14,xmm3,-5Bh",
			"vpshldq xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpshldq xmm2{k5}{z},xmm6,qword bcst [rax+8],-5Bh",
			"vpshldq ymm2{k3}{z},ymm6,ymm3,-5Bh",
			"vpshldq ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpshldq ymm2{k5}{z},ymm6,qword bcst [rax+8],-5Bh",
			"vpshldq zmm18{k3},zmm14,zmm3,-5Bh",
			"vpshldq zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshldq zmm2{k5}{z},zmm6,qword bcst [rax+8],-5Bh",
			"vpshrdw xmm2{k3},xmm6,xmm3,-5Bh",
			"vpshrdw xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpshrdw ymm18{k3}{z},ymm14,ymm3,-5Bh",
			"vpshrdw ymm2{k5}{z},ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpshrdw zmm2{k3},zmm6,zmm3,-5Bh",
			"vpshrdw zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshrdd xmm2{k3},xmm6,xmm3,-5Bh",
			"vpshrdd xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpshrdd xmm2{k5}{z},xmm6,dword bcst [rax+4],-5Bh",
			"vpshrdd ymm2{k3}{z},ymm6,ymm3,-5Bh",
			"vpshrdd ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpshrdd ymm2{k5}{z},ymm6,dword bcst [rax+4],-5Bh",
			"vpshrdd zmm2{k3},zmm6,zmm3,-5Bh",
			"vpshrdd zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshrdd zmm2{k5}{z},zmm6,dword bcst [rax+4],-5Bh",
			"vpshrdq xmm18{k3},xmm14,xmm3,-5Bh",
			"vpshrdq xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpshrdq xmm2{k5}{z},xmm6,qword bcst [rax+8],-5Bh",
			"vpshrdq ymm2{k3}{z},ymm6,ymm3,-5Bh",
			"vpshrdq ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpshrdq ymm2{k5}{z},ymm6,qword bcst [rax+8],-5Bh",
			"vpshrdq zmm18{k3},zmm14,zmm3,-5Bh",
			"vpshrdq zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vpshrdq zmm2{k5}{z},zmm6,qword bcst [rax+8],-5Bh",
			"gf2p8affineqb xmm1,xmm5,-5Bh",
			"gf2p8affineqb xmm1,xmmword ptr [rax],-5Bh",
			"vgf2p8affineqb xmm2,xmm6,xmm3,-5Bh",
			"vgf2p8affineqb xmm2,xmm6,xmmword ptr [rax],-5Bh",
			"vgf2p8affineqb ymm2,ymm6,ymm3,-5Bh",
			"vgf2p8affineqb ymm2,ymm6,ymmword ptr [rax],-5Bh",
			"vgf2p8affineqb xmm18{k3},xmm14,xmm3,-5Bh",
			"vgf2p8affineqb xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vgf2p8affineqb xmm2{k5}{z},xmm6,qword bcst [rax+8],-5Bh",
			"vgf2p8affineqb ymm2{k3}{z},ymm6,ymm3,-5Bh",
			"vgf2p8affineqb ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vgf2p8affineqb ymm2{k5}{z},ymm6,qword bcst [rax+8],-5Bh",
			"vgf2p8affineqb zmm18{k3},zmm14,zmm3,-5Bh",
			"vgf2p8affineqb zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vgf2p8affineqb zmm2{k5}{z},zmm6,qword bcst [rax+8],-5Bh",
			"gf2p8affineinvqb xmm1,xmm5,-5Bh",
			"gf2p8affineinvqb xmm1,xmmword ptr [rax],-5Bh",
			"vgf2p8affineinvqb xmm2,xmm6,xmm3,-5Bh",
			"vgf2p8affineinvqb xmm2,xmm6,xmmword ptr [rax],-5Bh",
			"vgf2p8affineinvqb ymm2,ymm6,ymm3,-5Bh",
			"vgf2p8affineinvqb ymm2,ymm6,ymmword ptr [rax],-5Bh",
			"vgf2p8affineinvqb xmm18{k3},xmm14,xmm3,-5Bh",
			"vgf2p8affineinvqb xmm2{k3},xmm6,xmmword ptr [rax+10h],-5Bh",
			"vgf2p8affineinvqb xmm2{k5}{z},xmm6,qword bcst [rax+8],-5Bh",
			"vgf2p8affineinvqb ymm2{k3}{z},ymm6,ymm3,-5Bh",
			"vgf2p8affineinvqb ymm2,ymm6,ymmword ptr [rax+20h],-5Bh",
			"vgf2p8affineinvqb ymm2{k5}{z},ymm6,qword bcst [rax+8],-5Bh",
			"vgf2p8affineinvqb zmm18{k3},zmm14,zmm3,-5Bh",
			"vgf2p8affineinvqb zmm2,zmm6,zmmword ptr [rax+40h],-5Bh",
			"vgf2p8affineinvqb zmm2{k5}{z},zmm6,qword bcst [rax+8],-5Bh",
			"fs monitor eax,rcx,rdx",
			"fs monitor rax,rcx,rdx",
			"fs monitorx eax,rcx,rdx",
			"fs monitorx rax,rcx,rdx",
			"fs clzero",
			"fs clzero",
			"fs umonitor ebp",
			"fs umonitor rbp",
 		};
	}
}
#endif
