/*
    Copyright (C) 2018 de4dot@gmail.com

    This file is part of Iced.

    Iced is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Iced is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Iced.  If not, see <https://www.gnu.org/licenses/>.
*/

#if !NO_MASM_FORMATTER && !NO_FORMATTER
using System.Collections.Generic;
using Xunit;

namespace Iced.UnitTests.Intel.FormatterTests.Masm {
	public sealed class MasmFormatterTest64_ForceMemSize_002 : FormatterTest {
		[Theory]
		[MemberData(nameof(Format_Data))]
		void Format(int index, InstructionInfo info, string formattedString) => FormatBase(index, info, formattedString, MasmFormatterFactory.Create_ForceMemSize());
		public static IEnumerable<object[]> Format_Data => GetFormatData(infos, formattedStrings);

		static readonly InstructionInfo[] infos = InstructionInfos64_002.AllInfos;
		static readonly string[] formattedStrings = new string[InstructionInfos64_002.AllInfos_Length] {
			"vcvtpd2ps xmm2{k3},xmm3",
			"vcvtpd2ps xmm2,xmmword ptr [rax+10h]",
			"vcvtpd2ps xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2ps xmm2{k3},ymm3",
			"vcvtpd2ps xmm2,ymmword ptr [rax+20h]",
			"vcvtpd2ps xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2ps ymm2{k3},zmm3",
			"vcvtpd2ps ymm2,zmmword ptr [rax+40h]",
			"vcvtpd2ps ymm2{k3}{z},qword bcst [rax+8]",
			"cvtss2sd xmm1,xmm5",
			"cvtss2sd xmm1,dword ptr [rax]",
			"vcvtss2sd xmm2,xmm6,xmm3",
			"vcvtss2sd xmm2,xmm6,dword ptr [rax]",
			"vcvtss2sd xmm2,xmm6,xmm3",
			"vcvtss2sd xmm2,xmm6,dword ptr [rax+4]",
			"cvtsd2ss xmm1,xmm5",
			"cvtsd2ss xmm1,qword ptr [rax]",
			"vcvtsd2ss xmm2,xmm6,xmm3",
			"vcvtsd2ss xmm2,xmm6,qword ptr [rax]",
			"vcvtsd2ss xmm2,xmm6,xmm3",
			"vcvtsd2ss xmm2,xmm6,qword ptr [rax+8]",
			"cvtdq2ps xmm1,xmm5",
			"cvtdq2ps xmm1,xmmword ptr [rax]",
			"vcvtdq2ps xmm1,xmm5",
			"vcvtdq2ps xmm2,xmmword ptr [rax]",
			"vcvtdq2ps ymm1,ymm5",
			"vcvtdq2ps ymm2,ymmword ptr [rax]",
			"vcvtdq2ps xmm2{k3},xmm3",
			"vcvtdq2ps xmm2,xmmword ptr [rax+10h]",
			"vcvtdq2ps xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtdq2ps ymm2{k3},ymm3",
			"vcvtdq2ps ymm2,ymmword ptr [rax+20h]",
			"vcvtdq2ps ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtdq2ps zmm2{k3},zmm3",
			"vcvtdq2ps zmm2,zmmword ptr [rax+40h]",
			"vcvtdq2ps zmm2{k3}{z},dword bcst [rax+4]",
			"vcvtqq2ps xmm2{k3},xmm3",
			"vcvtqq2ps xmm2,xmmword ptr [rax+10h]",
			"vcvtqq2ps xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtqq2ps xmm2{k3},ymm3",
			"vcvtqq2ps xmm2,ymmword ptr [rax+20h]",
			"vcvtqq2ps xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtqq2ps ymm2{k3},zmm3",
			"vcvtqq2ps ymm2,zmmword ptr [rax+40h]",
			"vcvtqq2ps ymm2{k3}{z},qword bcst [rax+8]",
			"cvtps2dq xmm1,xmm5",
			"cvtps2dq xmm1,xmmword ptr [rax]",
			"vcvtps2dq xmm1,xmm5",
			"vcvtps2dq ymm1,ymm5",
			"vcvtps2dq xmm2{k3},xmm3",
			"vcvtps2dq xmm2,xmmword ptr [rax+10h]",
			"vcvtps2dq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2dq ymm2{k3},ymm3",
			"vcvtps2dq ymm2,ymmword ptr [rax+20h]",
			"vcvtps2dq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2dq zmm2{k3},zmm3",
			"vcvtps2dq zmm2,zmmword ptr [rax+40h]",
			"vcvtps2dq zmm2{k3}{z},dword bcst [rax+4]",
			"cvttps2dq xmm1,xmm5",
			"cvttps2dq xmm1,xmmword ptr [rax]",
			"vcvttps2dq xmm1,xmm5",
			"vcvttps2dq xmm2,xmmword ptr [rax]",
			"vcvttps2dq ymm1,ymm5",
			"vcvttps2dq ymm2,ymmword ptr [rax]",
			"vcvttps2dq xmm2{k3},xmm3",
			"vcvttps2dq xmm2,xmmword ptr [rax+10h]",
			"vcvttps2dq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2dq ymm2{k3},ymm3",
			"vcvttps2dq ymm2,ymmword ptr [rax+20h]",
			"vcvttps2dq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2dq zmm2{k3},zmm3",
			"vcvttps2dq zmm2,zmmword ptr [rax+40h]",
			"vcvttps2dq zmm2{k3}{z},dword bcst [rax+4]",
			"subps xmm1,xmm5",
			"subps xmm1,xmmword ptr [rax]",
			"vsubps xmm2,xmm6,xmm3",
			"vsubps xmm2,xmm6,xmmword ptr [rax]",
			"vsubps ymm2,ymm6,ymm3",
			"vsubps ymm2,ymm6,ymmword ptr [rax]",
			"vsubps xmm2{k3},xmm6,xmm3",
			"vsubps xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vsubps xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vsubps ymm2{k3},ymm6,ymm3",
			"vsubps ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vsubps ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vsubps zmm2{k3}{z},zmm6,zmm3 {ru-sae}",
			"vsubps zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vsubps zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"subpd xmm1,xmm5",
			"subpd xmm1,xmmword ptr [rax]",
			"vsubpd xmm2,xmm6,xmm3",
			"vsubpd xmm2,xmm6,xmmword ptr [rax]",
			"vsubpd ymm2,ymm6,ymm3",
			"vsubpd ymm2,ymm6,ymmword ptr [rax]",
			"vsubpd xmm2{k3}{z},xmm6,xmm3",
			"vsubpd xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vsubpd xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vsubpd ymm2{k3}{z},ymm6,ymm3",
			"vsubpd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vsubpd ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vsubpd zmm2{k3}{z},zmm6,zmm3 {ru-sae}",
			"vsubpd zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vsubpd zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"subss xmm1,xmm5",
			"subss xmm1,dword ptr [rax]",
			"vsubss xmm2,xmm6,xmm3",
			"vsubss xmm2,xmm6,dword ptr [rax]",
			"vsubss xmm2{k3},xmm6,xmm3",
			"vsubss xmm2{k3},xmm6,dword ptr [rax+4]",
			"subsd xmm1,xmm5",
			"subsd xmm1,qword ptr [rax]",
			"vsubsd xmm2,xmm6,xmm3",
			"vsubsd xmm2,xmm6,qword ptr [rax]",
			"vsubsd xmm2{k3}{z},xmm6,xmm3",
			"vsubsd xmm2{k3},xmm6,qword ptr [rax+8]",
			"minps xmm1,xmm5",
			"minps xmm1,xmmword ptr [rax]",
			"vminps xmm2,xmm6,xmm3",
			"vminps xmm2,xmm6,xmmword ptr [rax]",
			"vminps ymm2,ymm6,ymm3",
			"vminps ymm2,ymm6,ymmword ptr [rax]",
			"vminps xmm2{k3},xmm6,xmm3",
			"vminps xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vminps xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vminps ymm2{k3},ymm6,ymm3",
			"vminps ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vminps ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vminps zmm2{k3}{z},zmm6,zmm3 {sae}",
			"vminps zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vminps zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"minpd xmm1,xmm5",
			"minpd xmm1,xmmword ptr [rax]",
			"vminpd xmm2,xmm6,xmm3",
			"vminpd xmm2,xmm6,xmmword ptr [rax]",
			"vminpd ymm2,ymm6,ymm3",
			"vminpd ymm2,ymm6,ymmword ptr [rax]",
			"vminpd xmm2{k3}{z},xmm6,xmm3",
			"vminpd xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vminpd xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vminpd ymm2{k3}{z},ymm6,ymm3",
			"vminpd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vminpd ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vminpd zmm2{k3}{z},zmm6,zmm3 {sae}",
			"vminpd zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vminpd zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"minss xmm1,xmm5",
			"minss xmm1,dword ptr [rax]",
			"vminss xmm2,xmm6,xmm3",
			"vminss xmm2,xmm6,dword ptr [rax]",
			"vminss xmm2{k3},xmm6,xmm3",
			"vminss xmm2{k3},xmm6,dword ptr [rax+4]",
			"minsd xmm1,xmm5",
			"minsd xmm1,qword ptr [rax]",
			"vminsd xmm2,xmm6,xmm3",
			"vminsd xmm2,xmm6,qword ptr [rax]",
			"vminsd xmm2{k3}{z},xmm6,xmm3",
			"vminsd xmm2{k3},xmm6,qword ptr [rax+8]",
			"divps xmm1,xmm5",
			"divps xmm1,xmmword ptr [rax]",
			"vdivps xmm2,xmm6,xmm3",
			"vdivps xmm2,xmm6,xmmword ptr [rax]",
			"vdivps ymm2,ymm6,ymm3",
			"vdivps ymm2,ymm6,ymmword ptr [rax]",
			"vdivps xmm2{k3},xmm6,xmm3",
			"vdivps xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vdivps xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vdivps ymm2{k3},ymm6,ymm3",
			"vdivps ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vdivps ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vdivps zmm2{k3}{z},zmm6,zmm3 {ru-sae}",
			"vdivps zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vdivps zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"divpd xmm1,xmm5",
			"divpd xmm1,xmmword ptr [rax]",
			"vdivpd xmm2,xmm6,xmm3",
			"vdivpd xmm2,xmm6,xmmword ptr [rax]",
			"vdivpd ymm2,ymm6,ymm3",
			"vdivpd ymm2,ymm6,ymmword ptr [rax]",
			"vdivpd xmm2{k3}{z},xmm6,xmm3",
			"vdivpd xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vdivpd xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vdivpd ymm2{k3}{z},ymm6,ymm3",
			"vdivpd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vdivpd ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vdivpd zmm2{k3}{z},zmm6,zmm3 {ru-sae}",
			"vdivpd zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vdivpd zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"divss xmm1,xmm5",
			"divss xmm1,dword ptr [rax]",
			"vdivss xmm2,xmm6,xmm3",
			"vdivss xmm2,xmm6,dword ptr [rax]",
			"vdivss xmm2{k3},xmm6,xmm3",
			"vdivss xmm2{k3},xmm6,dword ptr [rax+4]",
			"divsd xmm1,xmm5",
			"divsd xmm1,qword ptr [rax]",
			"vdivsd xmm2,xmm6,xmm3",
			"vdivsd xmm2,xmm6,qword ptr [rax]",
			"vdivsd xmm2{k3}{z},xmm6,xmm3",
			"vdivsd xmm2{k3},xmm6,qword ptr [rax+8]",
			"maxps xmm1,xmm5",
			"maxps xmm1,xmmword ptr [rax]",
			"vmaxps xmm2,xmm6,xmm3",
			"vmaxps xmm2,xmm6,xmmword ptr [rax]",
			"vmaxps ymm2,ymm6,ymm3",
			"vmaxps ymm2,ymm6,ymmword ptr [rax]",
			"vmaxps xmm2{k3},xmm6,xmm3",
			"vmaxps xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vmaxps xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vmaxps ymm2{k3},ymm6,ymm3",
			"vmaxps ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vmaxps ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vmaxps zmm2{k3}{z},zmm6,zmm3 {sae}",
			"vmaxps zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vmaxps zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"maxpd xmm1,xmm5",
			"maxpd xmm1,xmmword ptr [rax]",
			"vmaxpd xmm2,xmm6,xmm3",
			"vmaxpd xmm2,xmm6,xmmword ptr [rax]",
			"vmaxpd ymm2,ymm6,ymm3",
			"vmaxpd ymm2,ymm6,ymmword ptr [rax]",
			"vmaxpd xmm2{k3}{z},xmm6,xmm3",
			"vmaxpd xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vmaxpd xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vmaxpd ymm2{k3}{z},ymm6,ymm3",
			"vmaxpd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vmaxpd ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vmaxpd zmm2{k3}{z},zmm6,zmm3 {sae}",
			"vmaxpd zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vmaxpd zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"maxss xmm1,xmm5",
			"maxss xmm1,dword ptr [rax]",
			"vmaxss xmm2,xmm6,xmm3",
			"vmaxss xmm2,xmm6,dword ptr [rax]",
			"vmaxss xmm2{k3},xmm6,xmm3",
			"vmaxss xmm2{k3},xmm6,dword ptr [rax+4]",
			"maxsd xmm1,xmm5",
			"maxsd xmm1,qword ptr [rax]",
			"vmaxsd xmm2,xmm6,xmm3",
			"vmaxsd xmm2,xmm6,qword ptr [rax]",
			"vmaxsd xmm2{k3}{z},xmm6,xmm3",
			"vmaxsd xmm2{k3},xmm6,qword ptr [rax+8]",
			"punpcklbw mm1,mm5",
			"punpcklbw mm1,dword ptr [rax]",
			"punpcklbw xmm1,xmm5",
			"punpcklbw xmm1,xmmword ptr [rax]",
			"vpunpcklbw xmm2,xmm6,xmm3",
			"vpunpcklbw xmm2,xmm6,xmmword ptr [rax]",
			"vpunpcklbw ymm2,ymm6,ymm3",
			"vpunpcklbw ymm2,ymm6,ymmword ptr [rax]",
			"vpunpcklbw xmm2{k3},xmm6,xmm3",
			"vpunpcklbw xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpcklbw ymm2{k3},ymm6,ymm3",
			"vpunpcklbw ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpcklbw zmm2{k3},zmm6,zmm3",
			"vpunpcklbw zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"punpcklwd mm1,mm5",
			"punpcklwd mm1,dword ptr [rax]",
			"punpcklwd xmm1,xmm5",
			"punpcklwd xmm1,xmmword ptr [rax]",
			"vpunpcklwd xmm2,xmm6,xmm3",
			"vpunpcklwd xmm2,xmm6,xmmword ptr [rax]",
			"vpunpcklwd ymm2,ymm6,ymm3",
			"vpunpcklwd ymm2,ymm6,ymmword ptr [rax]",
			"vpunpcklwd xmm2{k3},xmm6,xmm3",
			"vpunpcklwd xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpcklwd ymm2{k3},ymm6,ymm3",
			"vpunpcklwd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpcklwd zmm2{k3},zmm6,zmm3",
			"vpunpcklwd zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"punpckldq mm1,mm5",
			"punpckldq mm1,dword ptr [rax]",
			"punpckldq xmm1,xmm5",
			"punpckldq xmm1,xmmword ptr [rax]",
			"vpunpckldq xmm2,xmm6,xmm3",
			"vpunpckldq xmm2,xmm6,xmmword ptr [rax]",
			"vpunpckldq ymm2,ymm6,ymm3",
			"vpunpckldq ymm2,ymm6,ymmword ptr [rax]",
			"vpunpckldq xmm2{k3}{z},xmm6,xmm3",
			"vpunpckldq xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpckldq xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vpunpckldq ymm2{k3}{z},ymm6,ymm3",
			"vpunpckldq ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpckldq ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vpunpckldq zmm2{k3}{z},zmm6,zmm3",
			"vpunpckldq zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpunpckldq zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"packsswb mm1,mm5",
			"packsswb mm1,mmword ptr [rax]",
			"packsswb xmm1,xmm5",
			"packsswb xmm1,xmmword ptr [rax]",
			"vpacksswb xmm2,xmm6,xmm3",
			"vpacksswb xmm2,xmm6,xmmword ptr [rax]",
			"vpacksswb ymm2,ymm6,ymm3",
			"vpacksswb ymm2,ymm6,ymmword ptr [rax]",
			"vpacksswb xmm2{k3},xmm6,xmm3",
			"vpacksswb xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpacksswb ymm2{k3},ymm6,ymm3",
			"vpacksswb ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpacksswb zmm2{k3},zmm6,zmm3",
			"vpacksswb zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"pcmpgtb mm1,mm5",
			"pcmpgtb mm1,mmword ptr [rax]",
			"pcmpgtb xmm1,xmm5",
			"pcmpgtb xmm1,xmmword ptr [rax]",
			"vpcmpgtb xmm2,xmm6,xmm3",
			"vpcmpgtb xmm2,xmm6,xmmword ptr [rax]",
			"vpcmpgtb ymm2,ymm6,ymm3",
			"vpcmpgtb ymm2,ymm6,ymmword ptr [rax]",
			"vpcmpgtb k2{k3},xmm6,xmm3",
			"vpcmpgtb k2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpcmpgtb k2{k3},ymm6,ymm3",
			"vpcmpgtb k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpcmpgtb k2{k3},zmm6,zmm3",
			"vpcmpgtb k2{k3},zmm6,zmmword ptr [rax+40h]",
			"pcmpgtw mm1,mm5",
			"pcmpgtw mm1,mmword ptr [rax]",
			"pcmpgtw xmm1,xmm5",
			"pcmpgtw xmm1,xmmword ptr [rax]",
			"vpcmpgtw xmm2,xmm6,xmm3",
			"vpcmpgtw xmm2,xmm6,xmmword ptr [rax]",
			"vpcmpgtw ymm2,ymm6,ymm3",
			"vpcmpgtw ymm2,ymm6,ymmword ptr [rax]",
			"vpcmpgtw k2{k3},xmm6,xmm3",
			"vpcmpgtw k2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpcmpgtw k2{k3},ymm6,ymm3",
			"vpcmpgtw k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpcmpgtw k2{k3},zmm6,zmm3",
			"vpcmpgtw k2{k3},zmm6,zmmword ptr [rax+40h]",
			"pcmpgtd mm1,mm5",
			"pcmpgtd mm1,mmword ptr [rax]",
			"pcmpgtd xmm1,xmm5",
			"pcmpgtd xmm1,xmmword ptr [rax]",
			"vpcmpgtd xmm2,xmm6,xmm3",
			"vpcmpgtd xmm2,xmm6,xmmword ptr [rax]",
			"vpcmpgtd ymm2,ymm6,ymm3",
			"vpcmpgtd ymm2,ymm6,ymmword ptr [rax]",
			"vpcmpgtd k2{k3},xmm6,xmm3",
			"vpcmpgtd k2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpcmpgtd k2{k5},xmm6,dword bcst [rax+4]",
			"vpcmpgtd k2{k3},ymm6,ymm3",
			"vpcmpgtd k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpcmpgtd k2{k5},ymm6,dword bcst [rax+4]",
			"vpcmpgtd k2{k3},zmm6,zmm3",
			"vpcmpgtd k2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpcmpgtd k2{k5},zmm6,dword bcst [rax+4]",
			"packuswb mm1,mm5",
			"packuswb mm1,mmword ptr [rax]",
			"packuswb xmm1,xmm5",
			"packuswb xmm1,xmmword ptr [rax]",
			"vpackuswb xmm2,xmm6,xmm3",
			"vpackuswb xmm2,xmm6,xmmword ptr [rax]",
			"vpackuswb ymm2,ymm6,ymm3",
			"vpackuswb ymm2,ymm6,ymmword ptr [rax]",
			"vpackuswb xmm2{k3},xmm6,xmm3",
			"vpackuswb xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpackuswb ymm2{k3},ymm6,ymm3",
			"vpackuswb ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpackuswb zmm2{k3},zmm6,zmm3",
			"vpackuswb zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"punpckhbw mm1,mm5",
			"punpckhbw mm1,mmword ptr [rax]",
			"punpckhbw xmm1,xmm5",
			"punpckhbw xmm1,xmmword ptr [rax]",
			"vpunpckhbw xmm2,xmm6,xmm3",
			"vpunpckhbw xmm2,xmm6,xmmword ptr [rax]",
			"vpunpckhbw ymm2,ymm6,ymm3",
			"vpunpckhbw ymm2,ymm6,ymmword ptr [rax]",
			"vpunpckhbw xmm2{k3},xmm6,xmm3",
			"vpunpckhbw xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpckhbw ymm2{k3},ymm6,ymm3",
			"vpunpckhbw ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpckhbw zmm2{k3},zmm6,zmm3",
			"vpunpckhbw zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"punpckhwd mm1,mm5",
			"punpckhwd mm1,mmword ptr [rax]",
			"punpckhwd xmm1,xmm5",
			"punpckhwd xmm1,xmmword ptr [rax]",
			"vpunpckhwd xmm2,xmm6,xmm3",
			"vpunpckhwd xmm2,xmm6,xmmword ptr [rax]",
			"vpunpckhwd ymm2,ymm6,ymm3",
			"vpunpckhwd ymm2,ymm6,ymmword ptr [rax]",
			"vpunpckhwd xmm2{k3},xmm6,xmm3",
			"vpunpckhwd xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpckhwd ymm2{k3},ymm6,ymm3",
			"vpunpckhwd ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpckhwd zmm2{k3},zmm6,zmm3",
			"vpunpckhwd zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"punpckhdq mm1,mm5",
			"punpckhdq mm1,mmword ptr [rax]",
			"punpckhdq xmm1,xmm5",
			"punpckhdq xmm1,xmmword ptr [rax]",
			"vpunpckhdq xmm2,xmm6,xmm3",
			"vpunpckhdq xmm2,xmm6,xmmword ptr [rax]",
			"vpunpckhdq ymm2,ymm6,ymm3",
			"vpunpckhdq ymm2,ymm6,ymmword ptr [rax]",
			"vpunpckhdq xmm2{k3}{z},xmm6,xmm3",
			"vpunpckhdq xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpckhdq xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vpunpckhdq ymm2{k3}{z},ymm6,ymm3",
			"vpunpckhdq ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpckhdq ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vpunpckhdq zmm2{k3}{z},zmm6,zmm3",
			"vpunpckhdq zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpunpckhdq zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"packssdw mm1,mm5",
			"packssdw mm1,mmword ptr [rax]",
			"packssdw xmm1,xmm5",
			"packssdw xmm1,xmmword ptr [rax]",
			"vpackssdw xmm2,xmm6,xmm3",
			"vpackssdw xmm2,xmm6,xmmword ptr [rax]",
			"vpackssdw ymm2,ymm6,ymm3",
			"vpackssdw ymm2,ymm6,ymmword ptr [rax]",
			"vpackssdw xmm2{k3}{z},xmm6,xmm3",
			"vpackssdw xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpackssdw xmm2{k5}{z},xmm6,dword bcst [rax+4]",
			"vpackssdw ymm2{k3}{z},ymm6,ymm3",
			"vpackssdw ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpackssdw ymm2{k5}{z},ymm6,dword bcst [rax+4]",
			"vpackssdw zmm2{k3}{z},zmm6,zmm3",
			"vpackssdw zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpackssdw zmm2{k5}{z},zmm6,dword bcst [rax+4]",
			"punpcklqdq xmm1,xmm5",
			"punpcklqdq xmm1,xmmword ptr [rax]",
			"vpunpcklqdq xmm2,xmm6,xmm3",
			"vpunpcklqdq xmm2,xmm6,xmmword ptr [rax]",
			"vpunpcklqdq ymm2,ymm6,ymm3",
			"vpunpcklqdq ymm2,ymm6,ymmword ptr [rax]",
			"vpunpcklqdq xmm2{k3}{z},xmm6,xmm3",
			"vpunpcklqdq xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpcklqdq xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vpunpcklqdq ymm2{k3}{z},ymm6,ymm3",
			"vpunpcklqdq ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpcklqdq ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vpunpcklqdq zmm2{k3}{z},zmm6,zmm3",
			"vpunpcklqdq zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpunpcklqdq zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"punpckhqdq xmm1,xmm5",
			"punpckhqdq xmm1,xmmword ptr [rax]",
			"vpunpckhqdq xmm2,xmm6,xmm3",
			"vpunpckhqdq xmm2,xmm6,xmmword ptr [rax]",
			"vpunpckhqdq ymm2,ymm6,ymm3",
			"vpunpckhqdq ymm2,ymm6,ymmword ptr [rax]",
			"vpunpckhqdq xmm2{k3}{z},xmm6,xmm3",
			"vpunpckhqdq xmm2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpunpckhqdq xmm2{k5}{z},xmm6,qword bcst [rax+8]",
			"vpunpckhqdq ymm2{k3}{z},ymm6,ymm3",
			"vpunpckhqdq ymm2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpunpckhqdq ymm2{k5}{z},ymm6,qword bcst [rax+8]",
			"vpunpckhqdq zmm2{k3}{z},zmm6,zmm3",
			"vpunpckhqdq zmm2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpunpckhqdq zmm2{k5}{z},zmm6,qword bcst [rax+8]",
			"movd mm1,ebp",
			"movd mm1,dword ptr [rax]",
			"movq mm1,rbp",
			"movq mm1,qword ptr [rax]",
			"movd xmm1,ebp",
			"movd xmm1,dword ptr [rax]",
			"movq xmm1,rbp",
			"movq xmm1,qword ptr [rax]",
			"vmovd xmm1,ebp",
			"vmovd xmm1,dword ptr [rax]",
			"vmovq xmm1,rbp",
			"vmovq xmm1,qword ptr [rax]",
			"vmovd xmm2,ebx",
			"vmovd xmm2,dword ptr [rax+4]",
			"vmovq xmm2,rbx",
			"vmovq xmm2,qword ptr [rax+8]",
			"movq mm1,mm5",
			"movq mm1,qword ptr [rax]",
			"movdqa xmm1,xmm5",
			"movdqa xmm1,xmmword ptr [rax]",
			"vmovdqa xmm1,xmm5",
			"vmovdqa xmm2,xmmword ptr [rax]",
			"vmovdqa ymm1,ymm5",
			"vmovdqa ymm2,ymmword ptr [rax]",
			"vmovdqa32 xmm2,xmm3",
			"vmovdqa32 xmm2,xmmword ptr [rax+10h]",
			"vmovdqa32 ymm2,ymm3",
			"vmovdqa32 ymm2,ymmword ptr [rax+20h]",
			"vmovdqa32 zmm2,zmm3",
			"vmovdqa32 zmm2,zmmword ptr [rax+40h]",
			"vmovdqa64 xmm2,xmm3",
			"vmovdqa64 xmm2,xmmword ptr [rax+10h]",
			"vmovdqa64 ymm2,ymm3",
			"vmovdqa64 ymm2,ymmword ptr [rax+20h]",
			"vmovdqa64 zmm2,zmm3",
			"vmovdqa64 zmm2,zmmword ptr [rax+40h]",
			"movdqu xmm1,xmm5",
			"movdqu xmm1,xmmword ptr [rax]",
			"vmovdqu xmm1,xmm5",
			"vmovdqu xmm2,xmmword ptr [rax]",
			"vmovdqu ymm1,ymm5",
			"vmovdqu ymm2,ymmword ptr [rax]",
			"vmovdqu32 xmm2,xmm3",
			"vmovdqu32 xmm2,xmmword ptr [rax+10h]",
			"vmovdqu32 ymm2,ymm3",
			"vmovdqu32 ymm2,ymmword ptr [rax+20h]",
			"vmovdqu32 zmm2,zmm3",
			"vmovdqu32 zmm2,zmmword ptr [rax+40h]",
			"vmovdqu64 xmm2,xmm3",
			"vmovdqu64 xmm2,xmmword ptr [rax+10h]",
			"vmovdqu64 ymm2,ymm3",
			"vmovdqu64 ymm2,ymmword ptr [rax+20h]",
			"vmovdqu64 zmm2,zmm3",
			"vmovdqu64 zmm2,zmmword ptr [rax+40h]",
			"vmovdqu8 xmm2,xmm3",
			"vmovdqu8 xmm2,xmmword ptr [rax+10h]",
			"vmovdqu8 ymm2,ymm3",
			"vmovdqu8 ymm2,ymmword ptr [rax+20h]",
			"vmovdqu8 zmm2,zmm3",
			"vmovdqu8 zmm2,zmmword ptr [rax+40h]",
			"vmovdqu16 xmm2,xmm3",
			"vmovdqu16 xmm2,xmmword ptr [rax+10h]",
			"vmovdqu16 ymm2,ymm3",
			"vmovdqu16 ymm2,ymmword ptr [rax+20h]",
			"vmovdqu16 zmm2,zmm3",
			"vmovdqu16 zmm2,zmmword ptr [rax+40h]",
			"pshufw mm1,mm5,-5Bh",
			"pshufw mm1,mmword ptr [rax],-5Bh",
			"pshufd xmm1,xmm5,-5Bh",
			"pshufd xmm1,xmmword ptr [rax],-5Bh",
			"vpshufd xmm2,xmm3,-5Bh",
			"vpshufd xmm2,xmmword ptr [rax],-5Bh",
			"vpshufd ymm2,ymm3,-5Bh",
			"vpshufd ymm2,ymmword ptr [rax],-5Bh",
			"vpshufd xmm2{k3}{z},xmm3,-5Bh",
			"vpshufd xmm2{k3}{z},xmmword ptr [rax+10h],-5Bh",
			"vpshufd xmm2{k5},dword bcst [rax+4],-5Bh",
			"vpshufd ymm2{k3}{z},ymm3,-5Bh",
			"vpshufd ymm2{k3}{z},ymmword ptr [rax+20h],-5Bh",
			"vpshufd ymm2{k5},dword bcst [rax+4],-5Bh",
			"vpshufd zmm2{k3}{z},zmm3,-5Bh",
			"vpshufd zmm2{k3}{z},zmmword ptr [rax+40h],-5Bh",
			"vpshufd zmm2{k5},dword bcst [rax+4],-5Bh",
			"pshufhw xmm1,xmm5,-5Bh",
			"pshufhw xmm1,xmmword ptr [rax],-5Bh",
			"vpshufhw xmm2,xmm3,-5Bh",
			"vpshufhw xmm2,xmmword ptr [rax],-5Bh",
			"vpshufhw ymm2,ymm3,-5Bh",
			"vpshufhw ymm2,ymmword ptr [rax],-5Bh",
			"vpshufhw xmm2{k3}{z},xmm3,-5Bh",
			"vpshufhw xmm2{k3}{z},xmmword ptr [rax+10h],-5Bh",
			"vpshufhw ymm2{k3}{z},ymm3,-5Bh",
			"vpshufhw ymm2{k3}{z},ymmword ptr [rax+20h],-5Bh",
			"vpshufhw zmm2{k3}{z},zmm3,-5Bh",
			"vpshufhw zmm2{k3}{z},zmmword ptr [rax+40h],-5Bh",
			"pshuflw xmm1,xmm5,-5Bh",
			"pshuflw xmm1,xmmword ptr [rax],-5Bh",
			"vpshuflw xmm2,xmm3,-5Bh",
			"vpshuflw xmm2,xmmword ptr [rax],-5Bh",
			"vpshuflw ymm2,ymm3,-5Bh",
			"vpshuflw ymm2,ymmword ptr [rax],-5Bh",
			"vpshuflw xmm2{k3}{z},xmm3,-5Bh",
			"vpshuflw xmm2{k3}{z},xmmword ptr [rax+10h],-5Bh",
			"vpshuflw ymm2{k3}{z},ymm3,-5Bh",
			"vpshuflw ymm2{k3}{z},ymmword ptr [rax+20h],-5Bh",
			"vpshuflw zmm2{k3}{z},zmm3,-5Bh",
			"vpshuflw zmm2{k3}{z},zmmword ptr [rax+40h],-5Bh",
			"psrlw mm5,-5Bh",
			"psrlw xmm5,-5Bh",
			"vpsrlw xmm6,xmm5,-5Bh",
			"vpsrlw ymm6,ymm5,-5Bh",
			"vpsrlw xmm6{k3},xmm5,-5Bh",
			"vpsrlw xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsrlw ymm6{k3},ymm5,-5Bh",
			"vpsrlw ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsrlw zmm6{k3},zmm5,-5Bh",
			"vpsrlw zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"psraw mm5,-5Bh",
			"psraw xmm5,-5Bh",
			"vpsraw xmm6,xmm5,-5Bh",
			"vpsraw ymm6,ymm5,-5Bh",
			"vpsraw xmm6{k3},xmm5,-5Bh",
			"vpsraw xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsraw ymm6{k3},ymm5,-5Bh",
			"vpsraw ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsraw zmm6{k3},zmm5,-5Bh",
			"vpsraw zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"psllw mm5,-5Bh",
			"psllw xmm5,-5Bh",
			"vpsllw xmm6,xmm5,-5Bh",
			"vpsllw ymm6,ymm5,-5Bh",
			"vpsllw xmm6{k3},xmm5,-5Bh",
			"vpsllw xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsllw ymm6{k3},ymm5,-5Bh",
			"vpsllw ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsllw zmm6{k3},zmm5,-5Bh",
			"vpsllw zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vprord xmm6{k3},xmm5,-5Bh",
			"vprord xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vprord xmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vprord ymm6{k3},ymm5,-5Bh",
			"vprord ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vprord ymm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vprord zmm6{k3},zmm5,-5Bh",
			"vprord zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vprord zmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vprorq xmm6{k3},xmm5,-5Bh",
			"vprorq xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vprorq xmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vprorq ymm6{k3},ymm5,-5Bh",
			"vprorq ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vprorq ymm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vprorq zmm6{k3},zmm5,-5Bh",
			"vprorq zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vprorq zmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vprold xmm6{k3},xmm5,-5Bh",
			"vprold xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vprold xmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vprold ymm6{k3},ymm5,-5Bh",
			"vprold ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vprold ymm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vprold zmm6{k3},zmm5,-5Bh",
			"vprold zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vprold zmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vprolq xmm6{k3},xmm5,-5Bh",
			"vprolq xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vprolq xmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vprolq ymm6{k3},ymm5,-5Bh",
			"vprolq ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vprolq ymm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vprolq zmm6{k3},zmm5,-5Bh",
			"vprolq zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vprolq zmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"psrld mm5,-5Bh",
			"psrld xmm5,-5Bh",
			"vpsrld xmm6,xmm5,-5Bh",
			"vpsrld ymm6,ymm5,-5Bh",
			"vpsrld xmm6{k3},xmm5,-5Bh",
			"vpsrld xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsrld xmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpsrld ymm6{k3},ymm5,-5Bh",
			"vpsrld ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsrld ymm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpsrld zmm6{k3},zmm5,-5Bh",
			"vpsrld zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vpsrld zmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"psrad mm5,-5Bh",
			"psrad xmm5,-5Bh",
			"vpsrad xmm6,xmm5,-5Bh",
			"vpsrad ymm6,ymm5,-5Bh",
			"vpsrad xmm6{k3},xmm5,-5Bh",
			"vpsrad xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsrad xmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpsrad ymm6{k3},ymm5,-5Bh",
			"vpsrad ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsrad ymm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpsrad zmm6{k3},zmm5,-5Bh",
			"vpsrad zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vpsrad zmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpsraq xmm6{k3},xmm5,-5Bh",
			"vpsraq xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsraq xmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vpsraq ymm6{k3},ymm5,-5Bh",
			"vpsraq ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsraq ymm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vpsraq zmm6{k3},zmm5,-5Bh",
			"vpsraq zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vpsraq zmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"pslld mm5,-5Bh",
			"pslld xmm5,-5Bh",
			"vpslld xmm6,xmm5,-5Bh",
			"vpslld ymm6,ymm5,-5Bh",
			"vpslld xmm6{k3},xmm5,-5Bh",
			"vpslld xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpslld xmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpslld ymm6{k3},ymm5,-5Bh",
			"vpslld ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpslld ymm6{k5}{z},dword bcst [rax+4],-5Bh",
			"vpslld zmm6{k3},zmm5,-5Bh",
			"vpslld zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vpslld zmm6{k5}{z},dword bcst [rax+4],-5Bh",
			"psrlq mm5,-5Bh",
			"psrlq xmm5,-5Bh",
			"vpsrlq xmm6,xmm5,-5Bh",
			"vpsrlq ymm6,ymm5,-5Bh",
			"vpsrlq xmm6{k3},xmm5,-5Bh",
			"vpsrlq xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsrlq xmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vpsrlq ymm6{k3},ymm5,-5Bh",
			"vpsrlq ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsrlq ymm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vpsrlq zmm6{k3},zmm5,-5Bh",
			"vpsrlq zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vpsrlq zmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"psrldq xmm5,-5Bh",
			"vpsrldq xmm6,xmm5,-5Bh",
			"vpsrldq ymm6,ymm5,-5Bh",
			"vpsrldq xmm6,xmm5,-5Bh",
			"vpsrldq xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpsrldq ymm6,ymm5,-5Bh",
			"vpsrldq ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpsrldq zmm6,zmm5,-5Bh",
			"vpsrldq zmm6,zmmword ptr [rax+40h],-5Bh",
			"psllq mm5,-5Bh",
			"psllq xmm5,-5Bh",
			"vpsllq xmm6,xmm5,-5Bh",
			"vpsllq ymm6,ymm5,-5Bh",
			"vpsllq xmm6{k3},xmm5,-5Bh",
			"vpsllq xmm6{k3},xmmword ptr [rax+10h],-5Bh",
			"vpsllq xmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vpsllq ymm6{k3},ymm5,-5Bh",
			"vpsllq ymm6{k3},ymmword ptr [rax+20h],-5Bh",
			"vpsllq ymm6{k5}{z},qword bcst [rax+8],-5Bh",
			"vpsllq zmm6{k3},zmm5,-5Bh",
			"vpsllq zmm6{k3},zmmword ptr [rax+40h],-5Bh",
			"vpsllq zmm6{k5}{z},qword bcst [rax+8],-5Bh",
			"pslldq xmm5,-5Bh",
			"vpslldq xmm6,xmm5,-5Bh",
			"vpslldq ymm6,ymm5,-5Bh",
			"vpslldq xmm6,xmm5,-5Bh",
			"vpslldq xmm6,xmmword ptr [rax+10h],-5Bh",
			"vpslldq ymm6,ymm5,-5Bh",
			"vpslldq ymm6,ymmword ptr [rax+20h],-5Bh",
			"vpslldq zmm6,zmm5,-5Bh",
			"vpslldq zmm6,zmmword ptr [rax+40h],-5Bh",
			"pcmpeqb mm1,mm5",
			"pcmpeqb mm1,mmword ptr [rax]",
			"pcmpeqb xmm1,xmm5",
			"pcmpeqb xmm1,xmmword ptr [rax]",
			"vpcmpeqb xmm2,xmm6,xmm3",
			"vpcmpeqb xmm2,xmm6,xmmword ptr [rax]",
			"vpcmpeqb ymm2,ymm6,ymm3",
			"vpcmpeqb ymm2,ymm6,ymmword ptr [rax]",
			"vpcmpeqb k2{k3},xmm6,xmm3",
			"vpcmpeqb k2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpcmpeqb k2{k3},ymm6,ymm3",
			"vpcmpeqb k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpcmpeqb k2{k3},zmm6,zmm3",
			"vpcmpeqb k2{k3},zmm6,zmmword ptr [rax+40h]",
			"pcmpeqw mm1,mm5",
			"pcmpeqw mm1,mmword ptr [rax]",
			"pcmpeqw xmm1,xmm5",
			"pcmpeqw xmm1,xmmword ptr [rax]",
			"vpcmpeqw xmm2,xmm6,xmm3",
			"vpcmpeqw xmm2,xmm6,xmmword ptr [rax]",
			"vpcmpeqw ymm2,ymm6,ymm3",
			"vpcmpeqw ymm2,ymm6,ymmword ptr [rax]",
			"vpcmpeqw k2{k3},xmm6,xmm3",
			"vpcmpeqw k2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpcmpeqw k2{k3},ymm6,ymm3",
			"vpcmpeqw k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpcmpeqw k2{k3},zmm6,zmm3",
			"vpcmpeqw k2{k3},zmm6,zmmword ptr [rax+40h]",
			"pcmpeqd mm1,mm5",
			"pcmpeqd mm1,mmword ptr [rax]",
			"pcmpeqd xmm1,xmm5",
			"pcmpeqd xmm1,xmmword ptr [rax]",
			"vpcmpeqd xmm2,xmm6,xmm3",
			"vpcmpeqd xmm2,xmm6,xmmword ptr [rax]",
			"vpcmpeqd ymm2,ymm6,ymm3",
			"vpcmpeqd ymm2,ymm6,ymmword ptr [rax]",
			"vpcmpeqd k2{k3},xmm6,xmm3",
			"vpcmpeqd k2{k3},xmm6,xmmword ptr [rax+10h]",
			"vpcmpeqd k2{k5},xmm6,dword bcst [rax+4]",
			"vpcmpeqd k2{k3},ymm6,ymm3",
			"vpcmpeqd k2{k3},ymm6,ymmword ptr [rax+20h]",
			"vpcmpeqd k2{k5},ymm6,dword bcst [rax+4]",
			"vpcmpeqd k2{k3},zmm6,zmm3",
			"vpcmpeqd k2{k3},zmm6,zmmword ptr [rax+40h]",
			"vpcmpeqd k2{k5},zmm6,dword bcst [rax+4]",
			"emms",
			"vzeroupper",
			"vzeroall",
			"vmread rsi,rcx",
			"vmread qword ptr [rax],rbx",
			"vmwrite rcx,rsi",
			"vmwrite rbx,qword ptr [rax]",
			"vcvttps2udq xmm2{k3},xmm3",
			"vcvttps2udq xmm2,xmmword ptr [rax+10h]",
			"vcvttps2udq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2udq ymm2{k3},ymm3",
			"vcvttps2udq ymm2,ymmword ptr [rax+20h]",
			"vcvttps2udq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2udq zmm2{k3},zmm3",
			"vcvttps2udq zmm2,zmmword ptr [rax+40h]",
			"vcvttps2udq zmm2{k3}{z},dword bcst [rax+4]",
			"vcvttpd2udq xmm2{k3},xmm3",
			"vcvttpd2udq xmm2,xmmword ptr [rax+10h]",
			"vcvttpd2udq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvttpd2udq xmm2{k3},ymm3",
			"vcvttpd2udq xmm2,ymmword ptr [rax+20h]",
			"vcvttpd2udq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvttpd2udq ymm2{k3},zmm3",
			"vcvttpd2udq ymm2,zmmword ptr [rax+40h]",
			"vcvttpd2udq ymm2{k3}{z},qword bcst [rax+8]",
			"vcvttps2uqq xmm2{k3},xmm3",
			"vcvttps2uqq xmm2,qword ptr [rax+8]",
			"vcvttps2uqq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2uqq ymm2{k3},xmm3",
			"vcvttps2uqq ymm2,xmmword ptr [rax+10h]",
			"vcvttps2uqq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2uqq zmm2{k3},ymm3",
			"vcvttps2uqq zmm2,ymmword ptr [rax+20h]",
			"vcvttps2uqq zmm2{k3}{z},dword bcst [rax+4]",
			"vcvttpd2uqq xmm2{k3},xmm3",
			"vcvttpd2uqq xmm2,xmmword ptr [rax+10h]",
			"vcvttpd2uqq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvttpd2uqq ymm2{k3},ymm3",
			"vcvttpd2uqq ymm2,ymmword ptr [rax+20h]",
			"vcvttpd2uqq ymm2{k3}{z},qword bcst [rax+8]",
			"vcvttpd2uqq zmm2{k3},zmm3",
			"vcvttpd2uqq zmm2,zmmword ptr [rax+40h]",
			"vcvttpd2uqq zmm2{k3}{z},qword bcst [rax+8]",
			"vcvttss2usi edx,xmm3",
			"vcvttss2usi edx,dword ptr [rax+4]",
			"vcvttss2usi rdx,xmm3",
			"vcvttss2usi rdx,dword ptr [rax+4]",
			"vcvttsd2usi edx,xmm3",
			"vcvttsd2usi edx,qword ptr [rax+8]",
			"vcvttsd2usi rdx,xmm3",
			"vcvttsd2usi rdx,qword ptr [rax+8]",
			"vcvtps2udq xmm2{k3},xmm3",
			"vcvtps2udq xmm2,xmmword ptr [rax+10h]",
			"vcvtps2udq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2udq ymm2{k3},ymm3",
			"vcvtps2udq ymm2,ymmword ptr [rax+20h]",
			"vcvtps2udq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2udq zmm2{k3},zmm3",
			"vcvtps2udq zmm2,zmmword ptr [rax+40h]",
			"vcvtps2udq zmm2{k3}{z},dword bcst [rax+4]",
			"vcvtpd2udq xmm2{k3},xmm3",
			"vcvtpd2udq xmm2,xmmword ptr [rax+10h]",
			"vcvtpd2udq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2udq xmm2{k3},ymm3",
			"vcvtpd2udq xmm2,ymmword ptr [rax+20h]",
			"vcvtpd2udq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2udq ymm2{k3},zmm3",
			"vcvtpd2udq ymm2,zmmword ptr [rax+40h]",
			"vcvtpd2udq ymm2{k3}{z},qword bcst [rax+8]",
			"vcvtps2uqq xmm2{k3},xmm3",
			"vcvtps2uqq xmm2,qword ptr [rax+8]",
			"vcvtps2uqq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2uqq ymm2{k3},xmm3",
			"vcvtps2uqq ymm2,xmmword ptr [rax+10h]",
			"vcvtps2uqq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2uqq zmm2{k3},ymm3",
			"vcvtps2uqq zmm2,ymmword ptr [rax+20h]",
			"vcvtps2uqq zmm2{k3}{z},dword bcst [rax+4]",
			"vcvtpd2uqq xmm2{k3},xmm3",
			"vcvtpd2uqq xmm2,xmmword ptr [rax+10h]",
			"vcvtpd2uqq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2uqq ymm2{k3},ymm3",
			"vcvtpd2uqq ymm2,ymmword ptr [rax+20h]",
			"vcvtpd2uqq ymm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2uqq zmm2{k3},zmm3",
			"vcvtpd2uqq zmm2,zmmword ptr [rax+40h]",
			"vcvtpd2uqq zmm2{k3}{z},qword bcst [rax+8]",
			"vcvtss2usi edx,xmm3",
			"vcvtss2usi edx,dword ptr [rax+4]",
			"vcvtss2usi rdx,xmm3",
			"vcvtss2usi rdx,dword ptr [rax+4]",
			"vcvtsd2usi edx,xmm3",
			"vcvtsd2usi edx,qword ptr [rax+8]",
			"vcvtsd2usi rdx,xmm3",
			"vcvtsd2usi rdx,qword ptr [rax+8]",
			"vcvttps2qq xmm2{k3},xmm3",
			"vcvttps2qq xmm2,qword ptr [rax+8]",
			"vcvttps2qq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2qq ymm2{k3},xmm3",
			"vcvttps2qq ymm2,xmmword ptr [rax+10h]",
			"vcvttps2qq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvttps2qq zmm2{k3},ymm3",
			"vcvttps2qq zmm2,ymmword ptr [rax+20h]",
			"vcvttps2qq zmm2{k3}{z},dword bcst [rax+4]",
			"vcvttpd2qq xmm2{k3},xmm3",
			"vcvttpd2qq xmm2,xmmword ptr [rax+10h]",
			"vcvttpd2qq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvttpd2qq ymm2{k3},ymm3",
			"vcvttpd2qq ymm2,ymmword ptr [rax+20h]",
			"vcvttpd2qq ymm2{k3}{z},qword bcst [rax+8]",
			"vcvttpd2qq zmm2{k3},zmm3",
			"vcvttpd2qq zmm2,zmmword ptr [rax+40h]",
			"vcvttpd2qq zmm2{k3}{z},qword bcst [rax+8]",
			"vcvtudq2pd xmm2{k3},xmm3",
			"vcvtudq2pd xmm2,qword ptr [rax+8]",
			"vcvtudq2pd xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtudq2pd ymm2{k3},xmm3",
			"vcvtudq2pd ymm2,xmmword ptr [rax+10h]",
			"vcvtudq2pd ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtudq2pd zmm2{k3},ymm3",
			"vcvtudq2pd zmm2,ymmword ptr [rax+20h]",
			"vcvtudq2pd zmm2{k3}{z},dword bcst [rax+4]",
			"vcvtuqq2pd xmm2{k3},xmm3",
			"vcvtuqq2pd xmm2,xmmword ptr [rax+10h]",
			"vcvtuqq2pd xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtuqq2pd ymm2{k3},ymm3",
			"vcvtuqq2pd ymm2,ymmword ptr [rax+20h]",
			"vcvtuqq2pd ymm2{k3}{z},qword bcst [rax+8]",
			"vcvtuqq2pd zmm2{k3},zmm3",
			"vcvtuqq2pd zmm2,zmmword ptr [rax+40h]",
			"vcvtuqq2pd zmm2{k3}{z},qword bcst [rax+8]",
			"vcvtudq2ps xmm2{k3},xmm3",
			"vcvtudq2ps xmm2,xmmword ptr [rax+10h]",
			"vcvtudq2ps xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtudq2ps ymm2{k3},ymm3",
			"vcvtudq2ps ymm2,ymmword ptr [rax+20h]",
			"vcvtudq2ps ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtudq2ps zmm2{k3},zmm3",
			"vcvtudq2ps zmm2,zmmword ptr [rax+40h]",
			"vcvtudq2ps zmm2{k3}{z},dword bcst [rax+4]",
			"vcvtuqq2ps xmm2{k3},xmm3",
			"vcvtuqq2ps xmm2,xmmword ptr [rax+10h]",
			"vcvtuqq2ps xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtuqq2ps xmm2{k3},ymm3",
			"vcvtuqq2ps xmm2,ymmword ptr [rax+20h]",
			"vcvtuqq2ps xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtuqq2ps ymm2{k3},zmm3",
			"vcvtuqq2ps ymm2,zmmword ptr [rax+40h]",
			"vcvtuqq2ps ymm2{k3}{z},qword bcst [rax+8]",
			"vcvtps2qq xmm2{k3},xmm3",
			"vcvtps2qq xmm2,qword ptr [rax+8]",
			"vcvtps2qq xmm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2qq ymm2{k3},xmm3",
			"vcvtps2qq ymm2,xmmword ptr [rax+10h]",
			"vcvtps2qq ymm2{k3}{z},dword bcst [rax+4]",
			"vcvtps2qq zmm2{k3},ymm3",
			"vcvtps2qq zmm2,ymmword ptr [rax+20h]",
			"vcvtps2qq zmm2{k3}{z},dword bcst [rax+4]",
			"vcvtpd2qq xmm2{k3},xmm3",
			"vcvtpd2qq xmm2,xmmword ptr [rax+10h]",
			"vcvtpd2qq xmm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2qq ymm2{k3},ymm3",
			"vcvtpd2qq ymm2,ymmword ptr [rax+20h]",
			"vcvtpd2qq ymm2{k3}{z},qword bcst [rax+8]",
			"vcvtpd2qq zmm2{k3},zmm3",
			"vcvtpd2qq zmm2,zmmword ptr [rax+40h]",
			"vcvtpd2qq zmm2{k3}{z},qword bcst [rax+8]",
			"vcvtusi2ss xmm2,xmm6,ebx",
			"vcvtusi2ss xmm2,xmm6,dword ptr [rax+4]",
			"vcvtusi2ss xmm2,xmm6,rbx",
			"vcvtusi2ss xmm2,xmm6,qword ptr [rax+8]",
			"vcvtusi2sd xmm2,xmm6,ebx",
			"vcvtusi2sd xmm2,xmm6,dword ptr [rax+4]",
			"vcvtusi2sd xmm2,xmm6,rbx",
			"vcvtusi2sd xmm2,xmm6,qword ptr [rax+8]",
			"haddpd xmm1,xmm5",
			"haddpd xmm1,xmmword ptr [rax]",
			"vhaddpd xmm2,xmm6,xmm3",
			"vhaddpd xmm2,xmm6,xmmword ptr [rax]",
			"vhaddpd ymm2,ymm6,ymm3",
			"vhaddpd ymm2,ymm6,ymmword ptr [rax]",
			"haddps xmm1,xmm5",
			"haddps xmm1,xmmword ptr [rax]",
			"vhaddps xmm2,xmm6,xmm3",
			"vhaddps xmm2,xmm6,xmmword ptr [rax]",
			"vhaddps ymm2,ymm6,ymm3",
			"vhaddps ymm2,ymm6,ymmword ptr [rax]",
			"hsubpd xmm1,xmm5",
			"hsubpd xmm1,xmmword ptr [rax]",
			"vhsubpd xmm2,xmm6,xmm3",
			"vhsubpd xmm2,xmm6,xmmword ptr [rax]",
			"vhsubpd ymm2,ymm6,ymm3",
			"vhsubpd ymm2,ymm6,ymmword ptr [rax]",
			"hsubps xmm1,xmm5",
			"hsubps xmm1,xmmword ptr [rax]",
			"vhsubps xmm2,xmm6,xmm3",
			"vhsubps xmm2,xmm6,xmmword ptr [rax]",
			"vhsubps ymm2,ymm6,ymm3",
			"vhsubps ymm2,ymm6,ymmword ptr [rax]",
			"movd ebp,mm1",
			"movd dword ptr [rax],mm1",
			"movq rbp,mm1",
			"movq qword ptr [rax],mm1",
			"movd ebp,xmm1",
			"movd dword ptr [rax],xmm1",
			"movq rbp,xmm1",
			"movq qword ptr [rax],xmm1",
			"vmovd ebp,xmm1",
			"vmovd dword ptr [rax],xmm1",
			"vmovq rbp,xmm1",
			"vmovq qword ptr [rax],xmm1",
			"vmovd ebx,xmm2",
			"vmovd dword ptr [rax+4],xmm2",
			"vmovq rbx,xmm2",
			"vmovq qword ptr [rax+8],xmm2",
			"movq xmm1,xmm5",
			"movq xmm1,qword ptr [rax]",
			"vmovq xmm1,xmm5",
			"vmovq xmm2,qword ptr [rax]",
			"vmovq xmm2,xmm3",
			"vmovq xmm2,qword ptr [rax+8]",
			"movq mm5,mm1",
			"movq qword ptr [rax],mm1",
			"movdqa xmm5,xmm1",
			"movdqa xmmword ptr [rax],xmm1",
			"vmovdqa xmm5,xmm1",
			"vmovdqa xmmword ptr [rax],xmm2",
			"vmovdqa ymm5,ymm1",
			"vmovdqa ymmword ptr [rax],ymm2",
			"vmovdqa32 xmm3,xmm2",
			"vmovdqa32 xmmword ptr [rax+10h],xmm2",
			"vmovdqa32 ymm3,ymm2",
			"vmovdqa32 ymmword ptr [rax+20h],ymm2",
			"vmovdqa32 zmm3,zmm2",
			"vmovdqa32 zmmword ptr [rax+40h],zmm2",
			"vmovdqa64 xmm3,xmm2",
			"vmovdqa64 xmmword ptr [rax+10h],xmm2",
			"vmovdqa64 ymm3,ymm2",
			"vmovdqa64 ymmword ptr [rax+20h],ymm2",
		};
	}
}
#endif
