/*
Copyright (C) 2018-2019 de4dot@gmail.com

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

// This file was generated by the Generator project
#nullable enable

#if !NO_INSTR_INFO
namespace Iced.Intel.InstructionInfoInternal {
	static partial class CpuidFeatureInternalData {
		static byte[] GetGetCpuidFeaturesData() =>
			new byte[] {
				// Header
				0x00,
				0x80,
				0x02,
				0x00,
				0xEF,
				0xFF,
				0x0F,
				0x00,
				0x00,
				0x30,
				0x00,
				0x00,
				0x00,
				0x08,
				0x00,
				0x00,
				0x00,
				0x00,
				0x00,

				0x00,// INTEL8086
				0x01,// INTEL8086_ONLY
				0x02,// INTEL186
				0x03,// INTEL286
				0x04,// INTEL286_ONLY
				0x05,// INTEL386
				0x06,// INTEL386_ONLY
				0x07,// INTEL386_A0_ONLY
				0x08,// INTEL486
				0x09,// INTEL486_A_ONLY
				0x0A,// INTEL386_486_ONLY
				0x0B,// IA64
				0x0C,// X64
				0x0D,// ADX
				0x0E,// AES
				0x0E, 0x0F,// AES, AVX
				0x0F,// AVX
				0x0F, 0x41,// AVX, GFNI
				0x10,// AVX2
				0x11,// AVX512_4FMAPS
				0x12,// AVX512_4VNNIW
				0x14,// AVX512_BITALG
				0x15,// AVX512_IFMA
				0x16,// AVX512_VBMI
				0x17,// AVX512_VBMI2
				0x18,// AVX512_VNNI
				0x1A,// AVX512_VPOPCNTDQ
				0x1B,// AVX512BW
				0x1C,// AVX512CD
				0x1D,// AVX512DQ
				0x1E,// AVX512ER
				0x1F,// AVX512F
				0x1F, 0x19,// AVX512F, AVX512_VP2INTERSECT
				0x1F, 0x41,// AVX512F, GFNI
				0x1F, 0x78,// AVX512F, VAES
				0x1F, 0x7A,// AVX512F, VPCLMULQDQ
				0x20,// AVX512PF
				0x21, 0x13,// AVX512VL, AVX512_BF16
				0x21, 0x14,// AVX512VL, AVX512_BITALG
				0x21, 0x15,// AVX512VL, AVX512_IFMA
				0x21, 0x16,// AVX512VL, AVX512_VBMI
				0x21, 0x17,// AVX512VL, AVX512_VBMI2
				0x21, 0x18,// AVX512VL, AVX512_VNNI
				0x21, 0x19,// AVX512VL, AVX512_VP2INTERSECT
				0x21, 0x1A,// AVX512VL, AVX512_VPOPCNTDQ
				0x21, 0x1B,// AVX512VL, AVX512BW
				0x21, 0x1C,// AVX512VL, AVX512CD
				0x21, 0x1D,// AVX512VL, AVX512DQ
				0x21, 0x1F,// AVX512VL, AVX512F
				0x21, 0x41,// AVX512VL, GFNI
				0x21, 0x78,// AVX512VL, VAES
				0x21, 0x7A,// AVX512VL, VPCLMULQDQ
				0x22,// BMI1
				0x23,// BMI2
				0x24,// CET_IBT
				0x25,// CET_SS
				0x26,// CFLSH
				0x27,// CL1INVMB
				0x28,// CLDEMOTE
				0x29,// CLFLUSHOPT
				0x2A,// CLFSH
				0x2B,// CLWB
				0x2C,// CLZERO
				0x2D,// CMOV
				0x2E,// CMPXCHG16B
				0x2F,// CPUID
				0x30,// CX8
				0x31,// D3NOW
				0x32,// D3NOWEXT
				0x33,// ECR
				0x34,// ENCLV
				0x35,// ENQCMD
				0x36,// F16C
				0x37,// FMA
				0x38,// FMA4
				0x39,// FPU
				0x39, 0x2D,// FPU, CMOV
				0x39, 0x6E,// FPU, SSE3
				0x3A,// FPU287
				0x3B,// FPU287XL_ONLY
				0x3C,// FPU387
				0x3D,// FPU387SL_ONLY
				0x3E,// FSGSBASE
				0x3F,// FXSR
				0x40,// GEODE
				0x41,// GFNI
				0x43,// HLE_or_RTM
				0x44,// INVEPT
				0x45,// INVPCID
				0x46,// INVVPID
				0x47,// LWP
				0x48,// LZCNT
				0x49,// MMX
				0x4A,// MONITOR
				0x4B,// MONITORX
				0x4C,// MOVBE
				0x4D,// MOVDIR64B
				0x4E,// MOVDIRI
				0x4F,// MPX
				0x50,// MSR
				0x51,// MULTIBYTENOP
				0x52,// PADLOCK_ACE
				0x53,// PADLOCK_PHE
				0x54,// PADLOCK_PMM
				0x55,// PADLOCK_RNG
				0x56,// PAUSE
				0x57,// PCLMULQDQ
				0x57, 0x0F,// PCLMULQDQ, AVX
				0x58,// PCOMMIT
				0x59,// PCONFIG
				0x5A,// PKU
				0x5B,// POPCNT
				0x5C,// PREFETCHW
				0x5D,// PREFETCHWT1
				0x5E,// PTWRITE
				0x5F,// RDPID
				0x60,// RDPMC
				0x61,// RDRAND
				0x62,// RDSEED
				0x63,// RDTSCP
				0x64,// RTM
				0x65,// SEP
				0x66,// SGX1
				0x67,// SHA
				0x69,// SKINIT_or_SVML
				0x6A,// SMAP
				0x6B,// SMX
				0x6C,// SSE
				0x6D,// SSE2
				0x6E,// SSE3
				0x6F,// SSE4_1
				0x70,// SSE4_2
				0x71,// SSE4A
				0x72,// SSSE3
				0x73,// SVM
				0x75,// SYSCALL
				0x76,// TBM
				0x77,// TSC
				0x78,// VAES
				0x79,// VMX
				0x7A,// VPCLMULQDQ
				0x7B,// WAITPKG
				0x7C,// WBNOINVD
				0x7D,// XOP
				0x7E,// XSAVE
				0x7F,// XSAVEC
				0x80,// XSAVEOPT
				0x81,// XSAVES
				0x82,// ZALLOC
			};
	}
}
#endif
