// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.info;

public final class RflagsBitsConstants {
	private RflagsBitsConstants() {
	}

	public static final char AF = 'a';
	public static final char CF = 'c';
	public static final char OF = 'o';
	public static final char PF = 'p';
	public static final char SF = 's';
	public static final char ZF = 'z';
	public static final char IF = 'i';
	public static final char DF = 'd';
	public static final char AC = 'A';
	public static final char C0 = '0';
	public static final char C1 = '1';
	public static final char C2 = '2';
	public static final char C3 = '3';
	public static final char UIF = 'u';
}
