/*
Copyright (C) 2018-2019 de4dot@gmail.com

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#if !NO_NASM_FORMATTER && !NO_FORMATTER
using System.Collections.Generic;
using Xunit;

namespace Iced.UnitTests.Intel.FormatterTests.Nasm {
	public sealed class NasmFormatterTest64_ForceMemSize_001 : FormatterTest {
		[Theory]
		[MemberData(nameof(Format_Data))]
		void Format(int index, InstructionInfo info, string formattedString) => FormatBase(index, info, formattedString, NasmFormatterFactory.Create_ForceMemSize());
		public static IEnumerable<object[]> Format_Data => GetFormatData(infos, formattedStrings);

		static readonly InstructionInfo[] infos = InstructionInfos64_001.AllInfos;
		static readonly string[] formattedStrings = new string[InstructionInfos64_001.AllInfos_Length] {
			"idiv byte [rax]",
			"test cx,-0x5aa6",
			"test word [rax],-0x5aa6",
			"test ecx,0x3412a55a",
			"test dword [rax],0x3412a55a",
			"test rcx,-0x7bed5aa6",
			"test qword [rax],-0x7bed5aa6",
			"not cx",
			"not word [rax]",
			"not ecx",
			"not dword [rax]",
			"not rcx",
			"not qword [rax]",
			"neg si",
			"neg word [rax]",
			"neg esi",
			"neg dword [rax]",
			"neg rsi",
			"neg qword [rax]",
			"mul bp",
			"mul word [rax]",
			"mul ebp",
			"mul dword [rax]",
			"mul rbp",
			"mul qword [rax]",
			"imul si",
			"imul word [rax]",
			"imul esi",
			"imul dword [rax]",
			"imul rsi",
			"imul qword [rax]",
			"div di",
			"div word [rax]",
			"div edi",
			"div dword [rax]",
			"div rdi",
			"div qword [rax]",
			"idiv ax",
			"idiv word [rax]",
			"idiv eax",
			"idiv dword [rax]",
			"idiv r8",
			"idiv qword [rax]",
			"clc",
			"stc",
			"cli",
			"sti",
			"cld",
			"std",
			"inc cl",
			"inc byte [rax]",
			"dec dh",
			"dec byte [rax]",
			"inc cx",
			"inc word [rax]",
			"inc ecx",
			"inc dword [rax]",
			"inc rcx",
			"inc qword [rax]",
			"dec si",
			"dec word [rax]",
			"dec esi",
			"dec dword [rax]",
			"dec rsi",
			"dec qword [rax]",
			"call rcx",
			"call qword [rax]",
			"call word far [rax]",
			"call dword far [rax]",
			"call far [rax]",
			"jmp rsi",
			"jmp qword [rax]",
			"jmp word far [rax]",
			"jmp dword far [rax]",
			"jmp far [rax]",
			"push si",
			"push word [rax]",
			"push rsi",
			"push qword [rax]",
			"sldt cx",
			"o16 sldt word [rax]",
			"sldt ecx",
			"sldt word [rax]",
			"sldt rcx",
			"o64 sldt word [rax]",
			"str dx",
			"o16 str word [rax]",
			"str edx",
			"str word [rax]",
			"str rdx",
			"o64 str word [rax]",
			"o16 lldt bx",
			"o16 lldt word [rax]",
			"lldt bx",
			"lldt word [rax]",
			"o64 lldt bx",
			"o64 lldt word [rax]",
			"o16 ltr sp",
			"o16 ltr word [rax]",
			"ltr sp",
			"ltr word [rax]",
			"o64 ltr sp",
			"o64 ltr word [rax]",
			"o16 verr bp",
			"o16 verr word [rax]",
			"verr bp",
			"verr word [rax]",
			"o64 verr bp",
			"o64 verr word [rax]",
			"o16 verw si",
			"o16 verw word [rax]",
			"verw si",
			"verw word [rax]",
			"o64 verw si",
			"o64 verw word [rax]",
			"sgdt [rax]",
			"sidt [rax]",
			"lgdt [rax]",
			"lidt [rax]",
			"smsw bp",
			"o16 smsw word [rax]",
			"smsw ebp",
			"smsw word [rax]",
			"smsw rbp",
			"o64 smsw word [rax]",
			"o16 lmsw si",
			"o16 lmsw word [rax]",
			"lmsw si",
			"lmsw word [rax]",
			"o64 lmsw si",
			"o64 lmsw word [rax]",
			"invlpg [rax]",
			"enclv",
			"vmcall",
			"vmlaunch",
			"vmresume",
			"vmxoff",
			"monitor",
			"mwait",
			"clac",
			"stac",
			"encls",
			"xgetbv",
			"xsetbv",
			"vmfunc",
			"xend",
			"xtest",
			"enclu",
			"rdpkru",
			"wrpkru",
			"swapgs",
			"rdtscp",
			"lar cx,si",
			"lar bx,word [rax]",
			"lar ecx,esi",
			"lar ebx,word [rax]",
			"lar rcx,rsi",
			"lar rbx,word [rax]",
			"lsl cx,si",
			"lsl bx,word [rax]",
			"lsl ecx,esi",
			"lsl ebx,word [rax]",
			"lsl rcx,rsi",
			"lsl rbx,word [rax]",
			"syscall",
			"clts",
			"sysret",
			"o64 sysret",
			"invd",
			"wbinvd",
			"ud2",
			"prefetchw [rax]",
			"prefetchwt1 byte [rax]",
			"movups xmm1,xmm5",
			"movups xmm1,oword [rax]",
			"vmovups xmm1,xmm5",
			"vmovups xmm2,oword [rax]",
			"vmovups ymm1,ymm5",
			"vmovups ymm2,yword [rax]",
			"vmovups xmm2,xmm3",
			"vmovups xmm2,oword [rax+0x10]",
			"vmovups ymm2,ymm3",
			"vmovups ymm2,yword [rax+0x20]",
			"vmovups zmm2,zmm3",
			"vmovups zmm2,zword [rax+0x40]",
			"movupd xmm1,xmm5",
			"movupd xmm1,oword [rax]",
			"vmovupd xmm1,xmm5",
			"vmovupd xmm2,oword [rax]",
			"vmovupd ymm1,ymm5",
			"vmovupd ymm2,yword [rax]",
			"vmovupd xmm2,xmm3",
			"vmovupd xmm2,oword [rax+0x10]",
			"vmovupd ymm2,ymm3",
			"vmovupd ymm2,yword [rax+0x20]",
			"vmovupd zmm2,zmm3",
			"vmovupd zmm2,zword [rax+0x40]",
			"movss xmm1,xmm5",
			"movss xmm1,dword [rax]",
			"vmovss xmm1,xmm6,xmm5",
			"vmovss xmm2,dword [rax]",
			"vmovss xmm2,xmm6,xmm3",
			"vmovss xmm2,dword [rax+4]",
			"movsd xmm1,xmm5",
			"movsd xmm1,qword [rax]",
			"vmovsd xmm1,xmm6,xmm5",
			"vmovsd xmm2,qword [rax]",
			"vmovsd xmm2,xmm6,xmm3",
			"vmovsd xmm2,qword [rax+8]",
			"movups xmm5,xmm1",
			"movups oword [rax],xmm1",
			"vmovups xmm5,xmm1",
			"vmovups oword [rax],xmm2",
			"vmovups ymm5,ymm1",
			"vmovups yword [rax],ymm2",
			"vmovups xmm3,xmm2",
			"vmovups oword [rax+0x10],xmm2",
			"vmovups ymm3,ymm2",
			"vmovups yword [rax+0x20],ymm2",
			"vmovups zmm3,zmm2",
			"vmovups zword [rax+0x40],zmm2",
			"movupd xmm5,xmm1",
			"movupd oword [rax],xmm1",
			"vmovupd xmm5,xmm1",
			"vmovupd oword [rax],xmm2",
			"vmovupd ymm5,ymm1",
			"vmovupd yword [rax],ymm2",
			"vmovupd xmm3,xmm2",
			"vmovupd oword [rax+0x10],xmm2",
			"vmovupd ymm3,ymm2",
			"vmovupd yword [rax+0x20],ymm2",
			"vmovupd zmm3,zmm2",
			"vmovupd zword [rax+0x40],zmm2",
			"movss xmm5,xmm1",
			"movss dword [rax],xmm1",
			"vmovss xmm5,xmm6,xmm1",
			"vmovss dword [rax],xmm2",
			"vmovss xmm3,xmm6,xmm2",
			"vmovss dword [rax+4],xmm2",
			"movsd xmm5,xmm1",
			"movsd qword [rax],xmm1",
			"vmovsd xmm5,xmm6,xmm1",
			"vmovsd qword [rax],xmm2",
			"vmovsd xmm3,xmm6,xmm2",
			"vmovsd qword [rax+8],xmm2",
			"movhlps xmm1,xmm5",
			"movlps xmm1,qword [rax]",
			"vmovhlps xmm2,xmm6,xmm3",
			"vmovlps xmm2,xmm6,qword [rax]",
			"vmovhlps xmm2,xmm6,xmm3",
			"vmovlps xmm2,xmm6,qword [rax+8]",
			"movlpd xmm1,qword [rax]",
			"vmovlpd xmm2,xmm6,qword [rax]",
			"vmovlpd xmm2,xmm6,qword [rax+8]",
			"movsldup xmm1,xmm5",
			"movsldup xmm1,[rax]",
			"vmovsldup xmm1,xmm5",
			"vmovsldup xmm2,oword [rax]",
			"vmovsldup ymm1,ymm5",
			"vmovsldup ymm2,yword [rax]",
			"vmovsldup xmm2,xmm3",
			"vmovsldup xmm2,oword [rax+0x10]",
			"vmovsldup ymm2,ymm3",
			"vmovsldup ymm2,yword [rax+0x20]",
			"vmovsldup zmm2,zmm3",
			"vmovsldup zmm2,zword [rax+0x40]",
			"movddup xmm1,xmm5",
			"movddup xmm1,[rax]",
			"vmovddup xmm1,xmm5",
			"vmovddup xmm2,qword [rax]",
			"vmovddup ymm1,ymm5",
			"vmovddup ymm2,yword [rax]",
			"vmovddup xmm2,xmm3",
			"vmovddup xmm2,qword [rax+8]",
			"vmovddup ymm2,ymm3",
			"vmovddup ymm2,yword [rax+0x20]",
			"vmovddup zmm2,zmm3",
			"vmovddup zmm2,zword [rax+0x40]",
			"movlps qword [rax],xmm1",
			"vmovlps qword [rax],xmm2",
			"vmovlps qword [rax+8],xmm2",
			"movlpd qword [rax],xmm1",
			"vmovlpd qword [rax],xmm2",
			"vmovlpd qword [rax+8],xmm2",
			"unpcklps xmm1,xmm5",
			"unpcklps xmm1,oword [rax]",
			"vunpcklps xmm2,xmm6,xmm3",
			"vunpcklps xmm2,xmm6,oword [rax]",
			"vunpcklps ymm2,ymm6,ymm3",
			"vunpcklps ymm2,ymm6,yword [rax]",
			"vunpcklps xmm2{k3},xmm6,xmm3",
			"vunpcklps xmm2{k3},xmm6,oword [rax+0x10]",
			"vunpcklps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vunpcklps ymm2{k3},ymm6,ymm3",
			"vunpcklps ymm2{k3},ymm6,yword [rax+0x20]",
			"vunpcklps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vunpcklps zmm2{k3},zmm6,zmm3",
			"vunpcklps zmm2{k3},zmm6,zword [rax+0x40]",
			"vunpcklps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"unpcklpd xmm1,xmm5",
			"unpcklpd xmm1,oword [rax]",
			"vunpcklpd xmm2,xmm6,xmm3",
			"vunpcklpd xmm2,xmm6,oword [rax]",
			"vunpcklpd ymm2,ymm6,ymm3",
			"vunpcklpd ymm2,ymm6,yword [rax]",
			"vunpcklpd xmm2{k3}{z},xmm6,xmm3",
			"vunpcklpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vunpcklpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vunpcklpd ymm2{k3}{z},ymm6,ymm3",
			"vunpcklpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vunpcklpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vunpcklpd zmm2{k3}{z},zmm6,zmm3",
			"vunpcklpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vunpcklpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"unpckhps xmm1,xmm5",
			"unpckhps xmm1,oword [rax]",
			"vunpckhps xmm2,xmm6,xmm3",
			"vunpckhps xmm2,xmm6,oword [rax]",
			"vunpckhps ymm2,ymm6,ymm3",
			"vunpckhps ymm2,ymm6,yword [rax]",
			"vunpckhps xmm2{k3},xmm6,xmm3",
			"vunpckhps xmm2{k3},xmm6,oword [rax+0x10]",
			"vunpckhps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vunpckhps ymm2{k3},ymm6,ymm3",
			"vunpckhps ymm2{k3},ymm6,yword [rax+0x20]",
			"vunpckhps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vunpckhps zmm2{k3},zmm6,zmm3",
			"vunpckhps zmm2{k3},zmm6,zword [rax+0x40]",
			"vunpckhps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"unpckhpd xmm1,xmm5",
			"unpckhpd xmm1,oword [rax]",
			"vunpckhpd xmm2,xmm6,xmm3",
			"vunpckhpd xmm2,xmm6,oword [rax]",
			"vunpckhpd ymm2,ymm6,ymm3",
			"vunpckhpd ymm2,ymm6,yword [rax]",
			"vunpckhpd xmm2{k3}{z},xmm6,xmm3",
			"vunpckhpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vunpckhpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vunpckhpd ymm2{k3}{z},ymm6,ymm3",
			"vunpckhpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vunpckhpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vunpckhpd zmm2{k3}{z},zmm6,zmm3",
			"vunpckhpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vunpckhpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"movlhps xmm1,xmm5",
			"vmovlhps xmm2,xmm6,xmm3",
			"vmovlhps xmm2,xmm6,xmm3",
			"movhps xmm1,qword [rax]",
			"vmovhps xmm2,xmm6,qword [rax]",
			"vmovhps xmm2,xmm6,qword [rax+8]",
			"movhpd xmm1,[rax]",
			"vmovhpd xmm2,xmm6,qword [rax]",
			"vmovhpd xmm2,xmm6,qword [rax+8]",
			"movshdup xmm1,xmm5",
			"movshdup xmm1,[rax]",
			"vmovshdup xmm1,xmm5",
			"vmovshdup xmm2,oword [rax]",
			"vmovshdup ymm1,ymm5",
			"vmovshdup ymm2,yword [rax]",
			"vmovshdup xmm2,xmm3",
			"vmovshdup xmm2,oword [rax+0x10]",
			"vmovshdup ymm2,ymm3",
			"vmovshdup ymm2,yword [rax+0x20]",
			"vmovshdup zmm2,zmm3",
			"vmovshdup zmm2,zword [rax+0x40]",
			"movhps qword [rax],xmm1",
			"vmovhps qword [rax],xmm2",
			"vmovhps qword [rax+8],xmm2",
			"movhpd [rax],xmm1",
			"vmovhpd qword [rax],xmm2",
			"vmovhpd qword [rax+8],xmm2",
			"prefetchnta byte [rax]",
			"prefetcht0 byte [rax]",
			"prefetcht1 byte [rax]",
			"prefetcht2 byte [rax]",
			"bndldx bnd1,[rax]",
			"bndmov bnd1,bnd2",
			"bndmov bnd1,[rax]",
			"bndcl bnd1,rdx",
			"bndcl bnd1,[rax]",
			"bndcu bnd1,rdx",
			"bndcu bnd1,[rax]",
			"bndstx [rax],bnd1",
			"bndmov bnd2,bnd1",
			"bndmov [rax],bnd1",
			"bndmk bnd1,[rax]",
			"bndcn bnd1,rdx",
			"bndcn bnd1,[rax]",
			"nop cx",
			"nop word [rax]",
			"nop ecx",
			"nop dword [rax]",
			"nop rcx",
			"nop qword [rax]",
			"mov rsi,cr3",
			"mov rsi,dr3",
			"mov cr3,rsi",
			"mov dr3,rsi",
			"movaps xmm1,xmm5",
			"movaps xmm1,oword [rax]",
			"vmovaps xmm1,xmm5",
			"vmovaps xmm2,oword [rax]",
			"vmovaps ymm1,ymm5",
			"vmovaps ymm2,yword [rax]",
			"vmovaps xmm2,xmm3",
			"vmovaps xmm2,oword [rax+0x10]",
			"vmovaps ymm2,ymm3",
			"vmovaps ymm2,yword [rax+0x20]",
			"vmovaps zmm2,zmm3",
			"vmovaps zmm2,zword [rax+0x40]",
			"movapd xmm1,xmm5",
			"movapd xmm1,oword [rax]",
			"vmovapd xmm1,xmm5",
			"vmovapd xmm2,oword [rax]",
			"vmovapd ymm1,ymm5",
			"vmovapd ymm2,yword [rax]",
			"vmovapd xmm2,xmm3",
			"vmovapd xmm2,oword [rax+0x10]",
			"vmovapd ymm2,ymm3",
			"vmovapd ymm2,yword [rax+0x20]",
			"vmovapd zmm2,zmm3",
			"vmovapd zmm2,zword [rax+0x40]",
			"movaps xmm5,xmm1",
			"movaps oword [rax],xmm1",
			"vmovaps xmm5,xmm1",
			"vmovaps oword [rax],xmm2",
			"vmovaps ymm5,ymm1",
			"vmovaps yword [rax],ymm2",
			"vmovaps xmm3,xmm2",
			"vmovaps oword [rax+0x10],xmm2",
			"vmovaps ymm3,ymm2",
			"vmovaps yword [rax+0x20],ymm2",
			"vmovaps zmm3,zmm2",
			"vmovaps zword [rax+0x40],zmm2",
			"movapd xmm5,xmm1",
			"movapd oword [rax],xmm1",
			"vmovapd xmm5,xmm1",
			"vmovapd oword [rax],xmm2",
			"vmovapd ymm5,ymm1",
			"vmovapd yword [rax],ymm2",
			"vmovapd xmm3,xmm2",
			"vmovapd oword [rax+0x10],xmm2",
			"vmovapd ymm3,ymm2",
			"vmovapd yword [rax+0x20],ymm2",
			"vmovapd zmm3,zmm2",
			"vmovapd zword [rax+0x40],zmm2",
			"cvtpi2ps xmm1,mm5",
			"cvtpi2ps xmm1,qword [rax]",
			"cvtpi2pd xmm1,mm5",
			"cvtpi2pd xmm1,qword [rax]",
			"cvtsi2ss xmm1,ebp",
			"cvtsi2ss xmm1,dword [rax]",
			"cvtsi2ss xmm1,rbp",
			"cvtsi2ss xmm1,qword [rax]",
			"vcvtsi2ss xmm2,xmm6,ebx",
			"vcvtsi2ss xmm2,xmm6,dword [rax]",
			"vcvtsi2ss xmm2,xmm6,rbx",
			"vcvtsi2ss xmm2,xmm6,qword [rax]",
			"vcvtsi2ss xmm2,xmm6,ebx",
			"vcvtsi2ss xmm2,xmm6,dword [rax+4]",
			"vcvtsi2ss xmm2,xmm6,rbx",
			"vcvtsi2ss xmm2,xmm6,qword [rax+8]",
			"cvtsi2sd xmm1,ebp",
			"cvtsi2sd xmm1,dword [rax]",
			"cvtsi2sd xmm1,rbp",
			"cvtsi2sd xmm1,qword [rax]",
			"vcvtsi2sd xmm2,xmm6,ebx",
			"vcvtsi2sd xmm2,xmm6,dword [rax]",
			"vcvtsi2sd xmm2,xmm6,rbx",
			"vcvtsi2sd xmm2,xmm6,qword [rax]",
			"vcvtsi2sd xmm2,xmm6,ebx",
			"vcvtsi2sd xmm2,xmm6,dword [rax+4]",
			"vcvtsi2sd xmm2,xmm6,rbx",
			"vcvtsi2sd xmm2,xmm6,qword [rax+8]",
			"movntps oword [rax],xmm1",
			"vmovntps oword [rax],xmm2",
			"vmovntps yword [rax],ymm2",
			"vmovntps oword [rax+0x10],xmm2",
			"vmovntps yword [rax+0x20],ymm2",
			"vmovntps zword [rax+0x40],zmm2",
			"movntpd oword [rax],xmm1",
			"vmovntpd oword [rax],xmm2",
			"vmovntpd yword [rax],ymm2",
			"vmovntpd oword [rax+0x10],xmm2",
			"vmovntpd yword [rax+0x20],ymm2",
			"vmovntpd zword [rax+0x40],zmm2",
			"cvttps2pi mm1,xmm5",
			"cvttps2pi mm1,qword [rax]",
			"cvttpd2pi mm1,xmm5",
			"cvttpd2pi mm1,oword [rax]",
			"cvttss2si ecx,xmm5",
			"cvttss2si ecx,dword [rax]",
			"cvttss2si rcx,xmm5",
			"cvttss2si rcx,dword [rax]",
			"vcvttss2si ecx,xmm5",
			"vcvttss2si edx,dword [rax]",
			"vcvttss2si rcx,xmm5",
			"vcvttss2si rdx,dword [rax]",
			"vcvttss2si edx,xmm3",
			"vcvttss2si edx,dword [rax+4]",
			"vcvttss2si rdx,xmm3",
			"vcvttss2si rdx,dword [rax+4]",
			"cvttsd2si ecx,xmm5",
			"cvttsd2si ecx,qword [rax]",
			"cvttsd2si rcx,xmm5",
			"cvttsd2si rcx,qword [rax]",
			"vcvttsd2si ecx,xmm5",
			"vcvttsd2si edx,qword [rax]",
			"vcvttsd2si rcx,xmm5",
			"vcvttsd2si rdx,qword [rax]",
			"vcvttsd2si edx,xmm3",
			"vcvttsd2si edx,qword [rax+8]",
			"vcvttsd2si rdx,xmm3",
			"vcvttsd2si rdx,qword [rax+8]",
			"cvtps2pi mm1,xmm5",
			"cvtps2pi mm1,qword [rax]",
			"cvtpd2pi mm1,xmm5",
			"cvtpd2pi mm1,oword [rax]",
			"cvtss2si ecx,xmm5",
			"cvtss2si ecx,dword [rax]",
			"cvtss2si rcx,xmm5",
			"cvtss2si rcx,dword [rax]",
			"vcvtss2si ecx,xmm5",
			"vcvtss2si edx,dword [rax]",
			"vcvtss2si rcx,xmm5",
			"vcvtss2si rdx,dword [rax]",
			"vcvtss2si edx,xmm3",
			"vcvtss2si edx,dword [rax+4]",
			"vcvtss2si rdx,xmm3",
			"vcvtss2si rdx,dword [rax+4]",
			"cvtsd2si ecx,xmm5",
			"cvtsd2si ecx,qword [rax]",
			"cvtsd2si rcx,xmm5",
			"cvtsd2si rcx,qword [rax]",
			"vcvtsd2si ecx,xmm5",
			"vcvtsd2si edx,qword [rax]",
			"vcvtsd2si rcx,xmm5",
			"vcvtsd2si rdx,qword [rax]",
			"vcvtsd2si edx,xmm3",
			"vcvtsd2si edx,qword [rax+8]",
			"vcvtsd2si rdx,xmm3",
			"vcvtsd2si rdx,qword [rax+8]",
			"ucomiss xmm1,xmm5",
			"ucomiss xmm1,dword [rax]",
			"vucomiss xmm2,xmm3",
			"vucomiss xmm2,dword [rax]",
			"vucomiss xmm2,xmm3",
			"vucomiss xmm2,dword [rax+4]",
			"ucomisd xmm1,xmm5",
			"ucomisd xmm1,[rax]",
			"vucomisd xmm2,xmm3",
			"vucomisd xmm2,qword [rax]",
			"vucomisd xmm2,xmm3",
			"vucomisd xmm2,qword [rax+8]",
			"comiss xmm1,xmm5",
			"comiss xmm1,dword [rax]",
			"comisd xmm1,xmm5",
			"comisd xmm1,[rax]",
			"vcomiss xmm2,xmm3",
			"vcomiss xmm2,dword [rax]",
			"vcomisd xmm2,xmm3",
			"vcomisd xmm2,qword [rax]",
			"vcomiss xmm2,xmm3",
			"vcomiss xmm2,dword [rax+4]",
			"vcomisd xmm2,xmm3",
			"vcomisd xmm2,qword [rax+8]",
			"wrmsr",
			"rdtsc",
			"rdmsr",
			"rdpmc",
			"sysenter",
			"sysexit",
			"o64 sysexit",
			"getsec",
			"cmovo cx,si",
			"cmovo bx,word [rax]",
			"cmovo ecx,esi",
			"cmovo ebx,dword [rax]",
			"cmovo rcx,rsi",
			"cmovo rbx,qword [rax]",
			"cmovno cx,si",
			"cmovno bx,word [rax]",
			"cmovno ecx,esi",
			"cmovno ebx,dword [rax]",
			"cmovno rcx,rsi",
			"cmovno rbx,qword [rax]",
			"cmovb cx,si",
			"cmovb bx,word [rax]",
			"cmovb ecx,esi",
			"cmovb ebx,dword [rax]",
			"cmovb rcx,rsi",
			"cmovb rbx,qword [rax]",
			"cmovae cx,si",
			"cmovae bx,word [rax]",
			"cmovae ecx,esi",
			"cmovae ebx,dword [rax]",
			"cmovae rcx,rsi",
			"cmovae rbx,qword [rax]",
			"cmove cx,si",
			"cmove bx,word [rax]",
			"cmove ecx,esi",
			"cmove ebx,dword [rax]",
			"cmove rcx,rsi",
			"cmove rbx,qword [rax]",
			"cmovne cx,si",
			"cmovne bx,word [rax]",
			"cmovne ecx,esi",
			"cmovne ebx,dword [rax]",
			"cmovne rcx,rsi",
			"cmovne rbx,qword [rax]",
			"cmovbe cx,si",
			"cmovbe bx,word [rax]",
			"cmovbe ecx,esi",
			"cmovbe ebx,dword [rax]",
			"cmovbe rcx,rsi",
			"cmovbe rbx,qword [rax]",
			"cmova cx,si",
			"cmova bx,word [rax]",
			"cmova ecx,esi",
			"cmova ebx,dword [rax]",
			"cmova rcx,rsi",
			"cmova rbx,qword [rax]",
			"cmovs cx,si",
			"cmovs bx,word [rax]",
			"cmovs ecx,esi",
			"cmovs ebx,dword [rax]",
			"cmovs rcx,rsi",
			"cmovs rbx,qword [rax]",
			"cmovns cx,si",
			"cmovns bx,word [rax]",
			"cmovns ecx,esi",
			"cmovns ebx,dword [rax]",
			"cmovns rcx,rsi",
			"cmovns rbx,qword [rax]",
			"cmovp cx,si",
			"cmovp bx,word [rax]",
			"cmovp ecx,esi",
			"cmovp ebx,dword [rax]",
			"cmovp rcx,rsi",
			"cmovp rbx,qword [rax]",
			"cmovnp cx,si",
			"cmovnp bx,word [rax]",
			"cmovnp ecx,esi",
			"cmovnp ebx,dword [rax]",
			"cmovnp rcx,rsi",
			"cmovnp rbx,qword [rax]",
			"cmovl cx,si",
			"cmovl bx,word [rax]",
			"cmovl ecx,esi",
			"cmovl ebx,dword [rax]",
			"cmovl rcx,rsi",
			"cmovl rbx,qword [rax]",
			"cmovge cx,si",
			"cmovge bx,word [rax]",
			"cmovge ecx,esi",
			"cmovge ebx,dword [rax]",
			"cmovge rcx,rsi",
			"cmovge rbx,qword [rax]",
			"cmovle cx,si",
			"cmovle bx,word [rax]",
			"cmovle ecx,esi",
			"cmovle ebx,dword [rax]",
			"cmovle rcx,rsi",
			"cmovle rbx,qword [rax]",
			"cmovg cx,si",
			"cmovg bx,word [rax]",
			"cmovg ecx,esi",
			"cmovg ebx,dword [rax]",
			"cmovg rcx,rsi",
			"cmovg rbx,qword [rax]",
			"kandw k2,k6,k3",
			"kandq k2,k6,k3",
			"kandb k2,k6,k3",
			"kandd k2,k6,k3",
			"kandnw k2,k6,k3",
			"kandnq k2,k6,k3",
			"kandnb k2,k6,k3",
			"kandnd k2,k6,k3",
			"knotw k2,k3",
			"knotq k2,k3",
			"knotb k2,k3",
			"knotd k2,k3",
			"korw k2,k6,k3",
			"korq k2,k6,k3",
			"korb k2,k6,k3",
			"kord k2,k6,k3",
			"kxnorw k2,k6,k3",
			"kxnorq k2,k6,k3",
			"kxnorb k2,k6,k3",
			"kxnord k2,k6,k3",
			"kxorw k2,k6,k3",
			"kxorq k2,k6,k3",
			"kxorb k2,k6,k3",
			"kxord k2,k6,k3",
			"kaddw k2,k6,k3",
			"kaddq k2,k6,k3",
			"kaddb k2,k6,k3",
			"kaddd k2,k6,k3",
			"kunpckwd k2,k6,k3",
			"kunpckdq k2,k6,k3",
			"kunpckbw k2,k6,k3",
			"movmskps ecx,xmm5",
			"movmskps rcx,xmm5",
			"vmovmskps edx,xmm3",
			"vmovmskps rdx,xmm3",
			"vmovmskps edx,ymm3",
			"vmovmskps rdx,ymm3",
			"movmskpd ecx,xmm5",
			"movmskpd rcx,xmm5",
			"vmovmskpd edx,xmm3",
			"vmovmskpd rdx,xmm3",
			"vmovmskpd edx,ymm3",
			"vmovmskpd rdx,ymm3",
			"sqrtps xmm1,xmm5",
			"sqrtps xmm1,oword [rax]",
			"vsqrtps xmm2,xmm3",
			"vsqrtps xmm2,oword [rax]",
			"vsqrtps ymm2,ymm3",
			"vsqrtps ymm2,yword [rax]",
			"vsqrtps xmm2{k3},xmm3",
			"vsqrtps xmm2{k3},oword [rax+0x10]",
			"vsqrtps xmm2{k5}{z},dword [rax+4]{1to4}",
			"vsqrtps ymm2{k3},ymm3",
			"vsqrtps ymm2{k3},yword [rax+0x20]",
			"vsqrtps ymm2{k5}{z},dword [rax+4]{1to8}",
			"vsqrtps zmm2{k3}{z},zmm3,{ru-sae}",
			"vsqrtps zmm2{k3},zword [rax+0x40]",
			"vsqrtps zmm2{k5}{z},dword [rax+4]{1to16}",
			"sqrtpd xmm1,xmm5",
			"sqrtpd xmm1,oword [rax]",
			"vsqrtpd xmm2,xmm3",
			"vsqrtpd xmm2,oword [rax]",
			"vsqrtpd ymm2,ymm3",
			"vsqrtpd ymm2,yword [rax]",
			"vsqrtpd xmm2{k3}{z},xmm3",
			"vsqrtpd xmm2{k3},oword [rax+0x10]",
			"vsqrtpd xmm2{k5}{z},qword [rax+8]{1to2}",
			"vsqrtpd ymm2{k3}{z},ymm3",
			"vsqrtpd ymm2{k3},yword [rax+0x20]",
			"vsqrtpd ymm2{k5}{z},qword [rax+8]{1to4}",
			"vsqrtpd zmm2{k3}{z},zmm3,{ru-sae}",
			"vsqrtpd zmm2{k3},zword [rax+0x40]",
			"vsqrtpd zmm2{k5}{z},qword [rax+8]{1to8}",
			"sqrtss xmm1,xmm5",
			"sqrtss xmm1,dword [rax]",
			"vsqrtss xmm2,xmm6,xmm3",
			"vsqrtss xmm2,xmm6,dword [rax]",
			"vsqrtss xmm2{k3},xmm6,xmm3",
			"vsqrtss xmm2{k3},xmm6,dword [rax+4]",
			"sqrtsd xmm1,xmm5",
			"sqrtsd xmm1,[rax]",
			"vsqrtsd xmm2,xmm6,xmm3",
			"vsqrtsd xmm2,xmm6,qword [rax]",
			"vsqrtsd xmm2{k3}{z},xmm6,xmm3",
			"vsqrtsd xmm2{k3},xmm6,qword [rax+8]",
			"rsqrtps xmm1,xmm5",
			"rsqrtps xmm1,oword [rax]",
			"vrsqrtps xmm2,xmm3",
			"vrsqrtps xmm2,oword [rax]",
			"vrsqrtps ymm2,ymm3",
			"vrsqrtps ymm2,yword [rax]",
			"rsqrtss xmm1,xmm5",
			"rsqrtss xmm1,dword [rax]",
			"vrsqrtss xmm2,xmm6,xmm3",
			"vrsqrtss xmm2,xmm6,dword [rax]",
			"rcpps xmm1,xmm5",
			"rcpps xmm1,oword [rax]",
			"vrcpps xmm2,xmm3",
			"vrcpps xmm2,oword [rax]",
			"vrcpps ymm2,ymm3",
			"vrcpps ymm2,yword [rax]",
			"rcpss xmm1,xmm5",
			"rcpss xmm1,dword [rax]",
			"vrcpss xmm2,xmm6,xmm3",
			"vrcpss xmm2,xmm6,dword [rax]",
			"andps xmm1,xmm5",
			"andps xmm1,oword [rax]",
			"vandps xmm2,xmm6,xmm3",
			"vandps xmm2,xmm6,oword [rax]",
			"vandps ymm2,ymm6,ymm3",
			"vandps ymm2,ymm6,yword [rax]",
			"vandps xmm2{k3},xmm6,xmm3",
			"vandps xmm2{k3},xmm6,oword [rax+0x10]",
			"vandps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vandps ymm2{k3},ymm6,ymm3",
			"vandps ymm2{k3},ymm6,yword [rax+0x20]",
			"vandps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vandps zmm2{k3},zmm6,zmm3",
			"vandps zmm2{k3},zmm6,zword [rax+0x40]",
			"vandps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"andpd xmm1,xmm5",
			"andpd xmm1,oword [rax]",
			"vandpd xmm2,xmm6,xmm3",
			"vandpd xmm2,xmm6,oword [rax]",
			"vandpd ymm2,ymm6,ymm3",
			"vandpd ymm2,ymm6,yword [rax]",
			"vandpd xmm2{k3}{z},xmm6,xmm3",
			"vandpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vandpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vandpd ymm2{k3}{z},ymm6,ymm3",
			"vandpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vandpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vandpd zmm2{k3}{z},zmm6,zmm3",
			"vandpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vandpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"andnps xmm1,xmm5",
			"andnps xmm1,oword [rax]",
			"vandnps xmm2,xmm6,xmm3",
			"vandnps xmm2,xmm6,oword [rax]",
			"vandnps ymm2,ymm6,ymm3",
			"vandnps ymm2,ymm6,yword [rax]",
			"vandnps xmm2{k3},xmm6,xmm3",
			"vandnps xmm2{k3},xmm6,oword [rax+0x10]",
			"vandnps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vandnps ymm2{k3},ymm6,ymm3",
			"vandnps ymm2{k3},ymm6,yword [rax+0x20]",
			"vandnps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vandnps zmm2{k3},zmm6,zmm3",
			"vandnps zmm2{k3},zmm6,zword [rax+0x40]",
			"vandnps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"andnpd xmm1,xmm5",
			"andnpd xmm1,oword [rax]",
			"vandnpd xmm2,xmm6,xmm3",
			"vandnpd xmm2,xmm6,oword [rax]",
			"vandnpd ymm2,ymm6,ymm3",
			"vandnpd ymm2,ymm6,yword [rax]",
			"vandnpd xmm2{k3}{z},xmm6,xmm3",
			"vandnpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vandnpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vandnpd ymm2{k3}{z},ymm6,ymm3",
			"vandnpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vandnpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vandnpd zmm2{k3}{z},zmm6,zmm3",
			"vandnpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vandnpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"orps xmm1,xmm5",
			"orps xmm1,oword [rax]",
			"vorps xmm2,xmm6,xmm3",
			"vorps xmm2,xmm6,oword [rax]",
			"vorps ymm2,ymm6,ymm3",
			"vorps ymm2,ymm6,yword [rax]",
			"vorps xmm2{k3},xmm6,xmm3",
			"vorps xmm2{k3},xmm6,oword [rax+0x10]",
			"vorps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vorps ymm2{k3},ymm6,ymm3",
			"vorps ymm2{k3},ymm6,yword [rax+0x20]",
			"vorps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vorps zmm2{k3},zmm6,zmm3",
			"vorps zmm2{k3},zmm6,zword [rax+0x40]",
			"vorps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"orpd xmm1,xmm5",
			"orpd xmm1,oword [rax]",
			"vorpd xmm2,xmm6,xmm3",
			"vorpd xmm2,xmm6,oword [rax]",
			"vorpd ymm2,ymm6,ymm3",
			"vorpd ymm2,ymm6,yword [rax]",
			"vorpd xmm2{k3}{z},xmm6,xmm3",
			"vorpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vorpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vorpd ymm2{k3}{z},ymm6,ymm3",
			"vorpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vorpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vorpd zmm2{k3}{z},zmm6,zmm3",
			"vorpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vorpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"xorps xmm1,xmm5",
			"xorps xmm1,oword [rax]",
			"vxorps xmm2,xmm6,xmm3",
			"vxorps xmm2,xmm6,oword [rax]",
			"vxorps ymm2,ymm6,ymm3",
			"vxorps ymm2,ymm6,yword [rax]",
			"vxorps xmm2{k3},xmm6,xmm3",
			"vxorps xmm2{k3},xmm6,oword [rax+0x10]",
			"vxorps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vxorps ymm2{k3},ymm6,ymm3",
			"vxorps ymm2{k3},ymm6,yword [rax+0x20]",
			"vxorps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vxorps zmm2{k3},zmm6,zmm3",
			"vxorps zmm2{k3},zmm6,zword [rax+0x40]",
			"vxorps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"xorpd xmm1,xmm5",
			"xorpd xmm1,oword [rax]",
			"vxorpd xmm2,xmm6,xmm3",
			"vxorpd xmm2,xmm6,oword [rax]",
			"vxorpd ymm2,ymm6,ymm3",
			"vxorpd ymm2,ymm6,yword [rax]",
			"vxorpd xmm2{k3}{z},xmm6,xmm3",
			"vxorpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vxorpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vxorpd ymm2{k3}{z},ymm6,ymm3",
			"vxorpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vxorpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vxorpd zmm2{k3}{z},zmm6,zmm3",
			"vxorpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vxorpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"addps xmm1,xmm5",
			"addps xmm1,oword [rax]",
			"vaddps xmm2,xmm6,xmm3",
			"vaddps xmm2,xmm6,oword [rax]",
			"vaddps ymm2,ymm6,ymm3",
			"vaddps ymm2,ymm6,yword [rax]",
			"vaddps xmm2{k3},xmm6,xmm3",
			"vaddps xmm2{k3},xmm6,oword [rax+0x10]",
			"vaddps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vaddps ymm2{k3},ymm6,ymm3",
			"vaddps ymm2{k3},ymm6,yword [rax+0x20]",
			"vaddps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vaddps zmm2{k3}{z},zmm6,zmm3,{ru-sae}",
			"vaddps zmm2{k3},zmm6,zword [rax+0x40]",
			"vaddps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"addpd xmm1,xmm5",
			"addpd xmm1,oword [rax]",
			"vaddpd xmm2,xmm6,xmm3",
			"vaddpd xmm2,xmm6,oword [rax]",
			"vaddpd ymm2,ymm6,ymm3",
			"vaddpd ymm2,ymm6,yword [rax]",
			"vaddpd xmm2{k3}{z},xmm6,xmm3",
			"vaddpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vaddpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vaddpd ymm2{k3}{z},ymm6,ymm3",
			"vaddpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vaddpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vaddpd zmm2{k3}{z},zmm6,zmm3,{ru-sae}",
			"vaddpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vaddpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"addss xmm1,xmm5",
			"addss xmm1,dword [rax]",
			"vaddss xmm2,xmm6,xmm3",
			"vaddss xmm2,xmm6,dword [rax]",
			"vaddss xmm2{k3},xmm6,xmm3",
			"vaddss xmm2{k3},xmm6,dword [rax+4]",
			"addsd xmm1,xmm5",
			"addsd xmm1,qword [rax]",
			"vaddsd xmm2,xmm6,xmm3",
			"vaddsd xmm2,xmm6,qword [rax]",
			"vaddsd xmm2{k3}{z},xmm6,xmm3",
			"vaddsd xmm2{k3},xmm6,qword [rax+8]",
			"mulps xmm1,xmm5",
			"mulps xmm1,oword [rax]",
			"vmulps xmm2,xmm6,xmm3",
			"vmulps xmm2,xmm6,oword [rax]",
			"vmulps ymm2,ymm6,ymm3",
			"vmulps ymm2,ymm6,yword [rax]",
			"vmulps xmm2{k3},xmm6,xmm3",
			"vmulps xmm2{k3},xmm6,oword [rax+0x10]",
			"vmulps xmm2{k5}{z},xmm6,dword [rax+4]{1to4}",
			"vmulps ymm2{k3},ymm6,ymm3",
			"vmulps ymm2{k3},ymm6,yword [rax+0x20]",
			"vmulps ymm2{k5}{z},ymm6,dword [rax+4]{1to8}",
			"vmulps zmm2{k3}{z},zmm6,zmm3,{ru-sae}",
			"vmulps zmm2{k3},zmm6,zword [rax+0x40]",
			"vmulps zmm2{k5}{z},zmm6,dword [rax+4]{1to16}",
			"mulpd xmm1,xmm5",
			"mulpd xmm1,oword [rax]",
			"vmulpd xmm2,xmm6,xmm3",
			"vmulpd xmm2,xmm6,oword [rax]",
			"vmulpd ymm2,ymm6,ymm3",
			"vmulpd ymm2,ymm6,yword [rax]",
			"vmulpd xmm2{k3}{z},xmm6,xmm3",
			"vmulpd xmm2{k3},xmm6,oword [rax+0x10]",
			"vmulpd xmm2{k5}{z},xmm6,qword [rax+8]{1to2}",
			"vmulpd ymm2{k3}{z},ymm6,ymm3",
			"vmulpd ymm2{k3},ymm6,yword [rax+0x20]",
			"vmulpd ymm2{k5}{z},ymm6,qword [rax+8]{1to4}",
			"vmulpd zmm2{k3}{z},zmm6,zmm3,{ru-sae}",
			"vmulpd zmm2{k3},zmm6,zword [rax+0x40]",
			"vmulpd zmm2{k5}{z},zmm6,qword [rax+8]{1to8}",
			"mulss xmm1,xmm5",
			"mulss xmm1,dword [rax]",
			"vmulss xmm2,xmm6,xmm3",
			"vmulss xmm2,xmm6,dword [rax]",
			"vmulss xmm2{k3},xmm6,xmm3",
			"vmulss xmm2{k3},xmm6,dword [rax+4]",
			"mulsd xmm1,xmm5",
			"mulsd xmm1,[rax]",
			"vmulsd xmm2,xmm6,xmm3",
			"vmulsd xmm2,xmm6,qword [rax]",
			"vmulsd xmm2{k3}{z},xmm6,xmm3",
			"vmulsd xmm2{k3},xmm6,qword [rax+8]",
			"cvtps2pd xmm1,xmm5",
			"cvtps2pd xmm1,qword [rax]",
			"vcvtps2pd xmm1,xmm5",
			"vcvtps2pd xmm2,qword [rax]",
			"vcvtps2pd ymm1,xmm5",
			"vcvtps2pd ymm2,oword [rax]",
			"vcvtps2pd xmm2{k3},xmm3",
			"vcvtps2pd xmm2,qword [rax+8]",
			"vcvtps2pd xmm2{k3}{z},dword [rax+4]{1to2}",
			"vcvtps2pd ymm2{k3},xmm3",
			"vcvtps2pd ymm2,oword [rax+0x10]",
			"vcvtps2pd ymm2{k3}{z},dword [rax+4]{1to4}",
			"vcvtps2pd zmm2{k3},ymm3",
			"vcvtps2pd zmm2,yword [rax+0x20]",
			"vcvtps2pd zmm2{k3}{z},dword [rax+4]{1to8}",
			"cvtpd2ps xmm1,xmm5",
			"cvtpd2ps xmm1,oword [rax]",
			"vcvtpd2ps xmm1,xmm5",
			"vcvtpd2ps xmm2,oword [rax]",
			"vcvtpd2ps xmm1,ymm5",
			"vcvtpd2ps xmm2,yword [rax]",
		};
	}
}
#endif
