// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once
#ifndef ICED_X86_DECODEROPTIONS_HPP
#define ICED_X86_DECODEROPTIONS_HPP

#include <cstdint>
#include <cstddef>

namespace iced_x86 {

/// @brief Decoder options
namespace DecoderOptions {
	using Value = uint32_t;

	/// @brief No option is enabled
	constexpr Value NONE = 0x0U;
	/// @brief Disable some checks for invalid encodings of instructions, eg. most instructions can't use a @c LOCK prefix so if one is found, they're decoded as @ref Code::INVALID unless this option is enabled.
	constexpr Value NO_INVALID_CHECK = 0x1U;
	/// @brief AMD decoder: allow 16-bit branch/ret instructions in 64-bit mode, no @c o64 CALL/JMP FAR [mem], o64 LSS/LFS/LGS, @c UD0 has no modr/m byte, decode @c LOCK MOV CR. The AMD decoder can still decode Intel instructions.
	constexpr Value AMD = 0x2U;
	/// @brief Decode opcodes @c 0F0D and @c 0F18-0F1F as reserved-nop instructions (eg. @ref Code::RESERVEDNOP_RM32_R32_0_F1_D)
	constexpr Value FORCE_RESERVED_NOP = 0x4U;
	/// @brief Decode @c UMOV instructions
	constexpr Value UMOV = 0x8U;
	/// @brief Decode @c XBTS/@c IBTS
	constexpr Value XBTS = 0x10U;
	/// @brief Decode @c 0FA6/@c 0FA7 as @c CMPXCHG
	constexpr Value CMPXCHG486A = 0x20U;
	/// @brief Decode some old removed FPU instructions (eg. @c FRSTPM)
	constexpr Value OLD_FPU = 0x40U;
	/// @brief Decode @c PCOMMIT
	constexpr Value PCOMMIT = 0x80U;
	/// @brief Decode 286 @c STOREALL/@c LOADALL (@c 0F04 and @c 0F05)
	constexpr Value LOADALL286 = 0x100U;
	/// @brief Decode 386 @c LOADALL
	constexpr Value LOADALL386 = 0x200U;
	/// @brief Decode @c CL1INVMB
	constexpr Value CL1INVMB = 0x400U;
	/// @brief Decode @c MOV r32,tr and @c MOV tr,r32
	constexpr Value MOV_TR = 0x800U;
	/// @brief Decode @c JMPE instructions
	constexpr Value JMPE = 0x1000U;
	/// @brief Don't decode @c PAUSE, decode @c NOP instead
	constexpr Value NO_PAUSE = 0x2000U;
	/// @brief Don't decode @c WBNOINVD, decode @c WBINVD instead
	constexpr Value NO_WBNOINVD = 0x4000U;
	/// @brief Decode undocumented Intel @c RDUDBG and @c WRUDBG instructions
	constexpr Value UDBG = 0x8000U;
	/// @brief Don't decode @c TZCNT, decode @c BSF instead
	constexpr Value NO_MPFX_0FBC = 0x10000U;
	/// @brief Don't decode @c LZCNT, decode @c BSR instead
	constexpr Value NO_MPFX_0FBD = 0x20000U;
	/// @brief Don't decode @c LAHF and @c SAHF in 64-bit mode
	constexpr Value NO_LAHF_SAHF_64 = 0x40000U;
	/// @brief Decode @c MPX instructions
	constexpr Value MPX = 0x80000U;
	/// @brief Decode most Cyrix instructions: @c FPU, @c EMMI, @c SMM, @c DDI
	constexpr Value CYRIX = 0x100000U;
	/// @brief Decode Cyrix @c SMINT 0F7E (Cyrix 6x86 or earlier)
	constexpr Value CYRIX_SMINT_0F7E = 0x200000U;
	/// @brief Decode Cyrix @c DMI instructions (AMD Geode GX/LX)
	constexpr Value CYRIX_DMI = 0x400000U;
	/// @brief Decode Centaur @c ALTINST
	constexpr Value ALTINST = 0x800000U;
	/// @brief Decode Intel Knights Corner instructions
	constexpr Value KNC = 0x1000000U;
} // namespace DecoderOptions

} // namespace iced_x86

#endif // ICED_X86_DECODEROPTIONS_HPP
