// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.internal;

/**
 * DO NOT USE: INTERNAL API
 */
public final class InstrFlags1 {
	private InstrFlags1() {
	}

	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int SEGMENT_PREFIX_MASK = 0x0000_0007;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int SEGMENT_PREFIX_SHIFT = 0x0000_0005;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int DATA_LENGTH_MASK = 0x0000_000F;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int DATA_LENGTH_SHIFT = 0x0000_0008;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int ROUNDING_CONTROL_MASK = 0x0000_0007;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int ROUNDING_CONTROL_SHIFT = 0x0000_000C;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int OP_MASK_MASK = 0x0000_0007;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int OP_MASK_SHIFT = 0x0000_000F;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int CODE_SIZE_MASK = 0x0000_0003;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int CODE_SIZE_SHIFT = 0x0000_0012;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int BROADCAST = 0x0400_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int SUPPRESS_ALL_EXCEPTIONS = 0x0800_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int ZEROING_MASKING = 0x1000_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int REPE_PREFIX = 0x2000_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int REPNE_PREFIX = 0x4000_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int LOCK_PREFIX = 0x8000_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int EQUALS_IGNORE_MASK = 0x000C_0000;
}
