// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.internal;

/**
 * DO NOT USE: INTERNAL API
 */
public final class MvexInfoFlags1 {
	private MvexInfoFlags1() {
	}

	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NONE = 0x0000_0000;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NDD = 0x0000_0001;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NDS = 0x0000_0002;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int EVICTION_HINT = 0x0000_0004;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int IMM_ROUNDING_CONTROL = 0x0000_0008;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int ROUNDING_CONTROL = 0x0000_0010;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int SUPPRESS_ALL_EXCEPTIONS = 0x0000_0020;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int IGNORES_OP_MASK_REGISTER = 0x0000_0040;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int REQUIRE_OP_MASK_REGISTER = 0x0000_0080;
}
