// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.internal.fmt.nasm;

/**
 * DO NOT USE: INTERNAL API
 */
public final class BranchSizeInfo {
	private BranchSizeInfo() {
	}

	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NONE = 0;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NEAR = 1;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NEAR_WORD = 2;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int NEAR_DWORD = 3;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int WORD = 4;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int DWORD = 5;
	/**
	 * DO NOT USE: INTERNAL API
	 */
	public static final int SHORT = 6;
}
