# SPDX-License-Identifier: MIT
# Copyright wtfsck@protonmail.com
# Copyright iced contributors

# ⚠️This file was generated by GENERATOR!🦹‍♂️

# pylint: disable=invalid-name
# pylint: disable=line-too-long
# pylint: disable=too-many-lines

"""
Mnemonic condition code selector (eg. ``JE`` / ``JZ``)
"""

from typing import List

E: int = 0
"""
``JE``, ``CMOVE``, ``SETE``, ``LOOPE``, ``REPE``
"""
Z: int = 1
"""
``JZ``, ``CMOVZ``, ``SETZ``, ``LOOPZ``, ``REPZ``
"""

__all__: List[str] = []
