# SPDX-License-Identifier: MIT
# Copyright wtfsckgh@gmail.com
# Copyright iced contributors

# ⚠️This file was generated by GENERATOR!🦹‍♂️

# pylint: disable=invalid-name
# pylint: disable=line-too-long
# pylint: disable=too-many-lines

"""
Mnemonic condition code selector (eg. ``JG`` / ``JNLE``)
"""

from typing import List

G: int = 0
"""
``JG``, ``CMOVG``, ``SETG``
"""
NLE: int = 1
"""
``JNLE``, ``CMOVNLE``, ``SETNLE``
"""

__all__: List[str] = []
