#
# SPDX-License-Identifier: MIT
# Copyright wtfsckgh@gmail.com
# Copyright iced contributors
#

# ⚠️This file was generated by GENERATOR!🦹‍♂️

# pylint: disable=invalid-name
# pylint: disable=line-too-long
# pylint: disable=too-many-lines

"""
Mnemonic condition code selector (eg. ``JNP`` / ``JPO``)
"""

from typing import List

NP: int = 0
"""
``JNP``, ``CMOVNP``, ``SETNP``
"""
PO: int = 1
"""
``JPO``, ``CMOVPO``, ``SETPO``
"""

__all__: List[str] = []
