# SPDX-License-Identifier: MIT
# Copyright (C) 2018-present iced project and contributors

# ⚠️This file was generated by GENERATOR!🦹‍♂️

# pylint: disable=invalid-name
# pylint: disable=line-too-long
# pylint: disable=too-many-lines

"""
``RFLAGS`` bits, FPU condition code bits and misc bits (``UIF``) supported by the instruction info code
"""

import typing
if typing.TYPE_CHECKING:
	from ._iced_x86_py import RflagsBits
else:
	RflagsBits = int

NONE: RflagsBits = 0x0000_0000 # type: ignore
"""
No bit is set
"""
OF: RflagsBits = 0x0000_0001 # type: ignore
"""
``RFLAGS.OF``
"""
SF: RflagsBits = 0x0000_0002 # type: ignore
"""
``RFLAGS.SF``
"""
ZF: RflagsBits = 0x0000_0004 # type: ignore
"""
``RFLAGS.ZF``
"""
AF: RflagsBits = 0x0000_0008 # type: ignore
"""
``RFLAGS.AF``
"""
CF: RflagsBits = 0x0000_0010 # type: ignore
"""
``RFLAGS.CF``
"""
PF: RflagsBits = 0x0000_0020 # type: ignore
"""
``RFLAGS.PF``
"""
DF: RflagsBits = 0x0000_0040 # type: ignore
"""
``RFLAGS.DF``
"""
IF: RflagsBits = 0x0000_0080 # type: ignore
"""
``RFLAGS.IF``
"""
AC: RflagsBits = 0x0000_0100 # type: ignore
"""
``RFLAGS.AC``
"""
UIF: RflagsBits = 0x0000_0200 # type: ignore
"""
``UIF``
"""
C0: RflagsBits = 0x0000_0400 # type: ignore
"""
FPU status word bit ``C0``
"""
C1: RflagsBits = 0x0000_0800 # type: ignore
"""
FPU status word bit ``C1``
"""
C2: RflagsBits = 0x0000_1000 # type: ignore
"""
FPU status word bit ``C2``
"""
C3: RflagsBits = 0x0000_2000 # type: ignore
"""
FPU status word bit ``C3``
"""
