// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.fmt;

/**
 * Mnemonic condition code selector (eg.<!-- --> {@code JA} / {@code JNBE})
 */
public final class CC_a {
	private CC_a() {
	}

	/**
	 * {@code JA}, {@code CMOVA}, {@code SETA}
	 */
	public static final int A = 0;
	/**
	 * {@code JNBE}, {@code CMOVNBE}, {@code SETNBE}
	 */
	public static final int NBE = 1;
}
