// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.fmt;

/**
 * Mnemonic condition code selector (eg.<!-- --> <code>JA</code> / <code>JNBE</code>)
 */
public final class CC_a {
	private CC_a() {
	}

	/**
	 * <code>JA</code>, <code>CMOVA</code>, <code>SETA</code>
	 */
	public static final int A = 0;
	/**
	 * <code>JNBE</code>, <code>CMOVNBE</code>, <code>SETNBE</code>
	 */
	public static final int NBE = 1;
}
