// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.fmt;

/**
 * Mnemonic condition code selector (eg.<!-- --> {@code JE} / {@code JZ})
 */
public final class CC_e {
	private CC_e() {
	}

	/**
	 * {@code JE}, {@code CMOVE}, {@code SETE}, {@code LOOPE}, {@code REPE}
	 */
	public static final int E = 0;
	/**
	 * {@code JZ}, {@code CMOVZ}, {@code SETZ}, {@code LOOPZ}, {@code REPZ}
	 */
	public static final int Z = 1;
}
