// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.fmt;

/**
 * Number kind
 */
public final class NumberKind {
	private NumberKind() {
	}

	public static final int INT8 = 0;
	public static final int UINT8 = 1;
	public static final int INT16 = 2;
	public static final int UINT16 = 3;
	public static final int INT32 = 4;
	public static final int UINT32 = 5;
	public static final int INT64 = 6;
	public static final int UINT64 = 7;
}
