// SPDX-License-Identifier: MIT
// Copyright wtfsckgh@gmail.com
// Copyright iced contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if NASM
namespace Iced.Intel.NasmFormatterInternal {
	enum SizeOverride {
		None,
		Size16,
		Size32,
		Size64,
	}
}
#endif
