// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86;

/**
 * Registers passed to {@code Instruction.create()} methods.
 *
 * @see ICRegisters
 * @see ICRegistersGPR
 * @see ICRegistersVec
 * @see ICRegistersGPR8
 * @see ICRegistersGPR16
 * @see ICRegistersGPR32
 * @see ICRegistersGPR64
 * @see ICRegistersIP
 * @see ICRegistersSegment
 * @see ICRegistersST
 * @see ICRegistersCR
 * @see ICRegistersDR
 * @see ICRegistersTR
 * @see ICRegistersBND
 * @see ICRegistersK
 * @see ICRegistersMM
 * @see ICRegistersXMM
 * @see ICRegistersZMM
 * @see ICRegistersTMM
 */
public final class ICRegistersYMM {
	private ICRegistersYMM() {
	}

	public static final ICRegister ymm0 = ICRegisters.ymm0;
	public static final ICRegister ymm1 = ICRegisters.ymm1;
	public static final ICRegister ymm2 = ICRegisters.ymm2;
	public static final ICRegister ymm3 = ICRegisters.ymm3;
	public static final ICRegister ymm4 = ICRegisters.ymm4;
	public static final ICRegister ymm5 = ICRegisters.ymm5;
	public static final ICRegister ymm6 = ICRegisters.ymm6;
	public static final ICRegister ymm7 = ICRegisters.ymm7;
	public static final ICRegister ymm8 = ICRegisters.ymm8;
	public static final ICRegister ymm9 = ICRegisters.ymm9;
	public static final ICRegister ymm10 = ICRegisters.ymm10;
	public static final ICRegister ymm11 = ICRegisters.ymm11;
	public static final ICRegister ymm12 = ICRegisters.ymm12;
	public static final ICRegister ymm13 = ICRegisters.ymm13;
	public static final ICRegister ymm14 = ICRegisters.ymm14;
	public static final ICRegister ymm15 = ICRegisters.ymm15;
	public static final ICRegister ymm16 = ICRegisters.ymm16;
	public static final ICRegister ymm17 = ICRegisters.ymm17;
	public static final ICRegister ymm18 = ICRegisters.ymm18;
	public static final ICRegister ymm19 = ICRegisters.ymm19;
	public static final ICRegister ymm20 = ICRegisters.ymm20;
	public static final ICRegister ymm21 = ICRegisters.ymm21;
	public static final ICRegister ymm22 = ICRegisters.ymm22;
	public static final ICRegister ymm23 = ICRegisters.ymm23;
	public static final ICRegister ymm24 = ICRegisters.ymm24;
	public static final ICRegister ymm25 = ICRegisters.ymm25;
	public static final ICRegister ymm26 = ICRegisters.ymm26;
	public static final ICRegister ymm27 = ICRegisters.ymm27;
	public static final ICRegister ymm28 = ICRegisters.ymm28;
	public static final ICRegister ymm29 = ICRegisters.ymm29;
	public static final ICRegister ymm30 = ICRegisters.ymm30;
	public static final ICRegister ymm31 = ICRegisters.ymm31;
}
