// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86;

/**
 * Registers passed to {@code Instruction.create()} methods.
 *
 * @see ICRegisters
 * @see ICRegistersGPR
 * @see ICRegistersGPR8
 * @see ICRegistersGPR16
 * @see ICRegistersGPR32
 * @see ICRegistersGPR64
 * @see ICRegistersIP
 * @see ICRegistersSegment
 * @see ICRegistersST
 * @see ICRegistersCR
 * @see ICRegistersDR
 * @see ICRegistersTR
 * @see ICRegistersBND
 * @see ICRegistersK
 * @see ICRegistersMM
 * @see ICRegistersXMM
 * @see ICRegistersYMM
 * @see ICRegistersZMM
 * @see ICRegistersTMM
 */
public final class ICRegistersVec {
	private ICRegistersVec() {
	}

	public static final ICRegister xmm0 = ICRegisters.xmm0;
	public static final ICRegister xmm1 = ICRegisters.xmm1;
	public static final ICRegister xmm2 = ICRegisters.xmm2;
	public static final ICRegister xmm3 = ICRegisters.xmm3;
	public static final ICRegister xmm4 = ICRegisters.xmm4;
	public static final ICRegister xmm5 = ICRegisters.xmm5;
	public static final ICRegister xmm6 = ICRegisters.xmm6;
	public static final ICRegister xmm7 = ICRegisters.xmm7;
	public static final ICRegister xmm8 = ICRegisters.xmm8;
	public static final ICRegister xmm9 = ICRegisters.xmm9;
	public static final ICRegister xmm10 = ICRegisters.xmm10;
	public static final ICRegister xmm11 = ICRegisters.xmm11;
	public static final ICRegister xmm12 = ICRegisters.xmm12;
	public static final ICRegister xmm13 = ICRegisters.xmm13;
	public static final ICRegister xmm14 = ICRegisters.xmm14;
	public static final ICRegister xmm15 = ICRegisters.xmm15;
	public static final ICRegister xmm16 = ICRegisters.xmm16;
	public static final ICRegister xmm17 = ICRegisters.xmm17;
	public static final ICRegister xmm18 = ICRegisters.xmm18;
	public static final ICRegister xmm19 = ICRegisters.xmm19;
	public static final ICRegister xmm20 = ICRegisters.xmm20;
	public static final ICRegister xmm21 = ICRegisters.xmm21;
	public static final ICRegister xmm22 = ICRegisters.xmm22;
	public static final ICRegister xmm23 = ICRegisters.xmm23;
	public static final ICRegister xmm24 = ICRegisters.xmm24;
	public static final ICRegister xmm25 = ICRegisters.xmm25;
	public static final ICRegister xmm26 = ICRegisters.xmm26;
	public static final ICRegister xmm27 = ICRegisters.xmm27;
	public static final ICRegister xmm28 = ICRegisters.xmm28;
	public static final ICRegister xmm29 = ICRegisters.xmm29;
	public static final ICRegister xmm30 = ICRegisters.xmm30;
	public static final ICRegister xmm31 = ICRegisters.xmm31;
	public static final ICRegister ymm0 = ICRegisters.ymm0;
	public static final ICRegister ymm1 = ICRegisters.ymm1;
	public static final ICRegister ymm2 = ICRegisters.ymm2;
	public static final ICRegister ymm3 = ICRegisters.ymm3;
	public static final ICRegister ymm4 = ICRegisters.ymm4;
	public static final ICRegister ymm5 = ICRegisters.ymm5;
	public static final ICRegister ymm6 = ICRegisters.ymm6;
	public static final ICRegister ymm7 = ICRegisters.ymm7;
	public static final ICRegister ymm8 = ICRegisters.ymm8;
	public static final ICRegister ymm9 = ICRegisters.ymm9;
	public static final ICRegister ymm10 = ICRegisters.ymm10;
	public static final ICRegister ymm11 = ICRegisters.ymm11;
	public static final ICRegister ymm12 = ICRegisters.ymm12;
	public static final ICRegister ymm13 = ICRegisters.ymm13;
	public static final ICRegister ymm14 = ICRegisters.ymm14;
	public static final ICRegister ymm15 = ICRegisters.ymm15;
	public static final ICRegister ymm16 = ICRegisters.ymm16;
	public static final ICRegister ymm17 = ICRegisters.ymm17;
	public static final ICRegister ymm18 = ICRegisters.ymm18;
	public static final ICRegister ymm19 = ICRegisters.ymm19;
	public static final ICRegister ymm20 = ICRegisters.ymm20;
	public static final ICRegister ymm21 = ICRegisters.ymm21;
	public static final ICRegister ymm22 = ICRegisters.ymm22;
	public static final ICRegister ymm23 = ICRegisters.ymm23;
	public static final ICRegister ymm24 = ICRegisters.ymm24;
	public static final ICRegister ymm25 = ICRegisters.ymm25;
	public static final ICRegister ymm26 = ICRegisters.ymm26;
	public static final ICRegister ymm27 = ICRegisters.ymm27;
	public static final ICRegister ymm28 = ICRegisters.ymm28;
	public static final ICRegister ymm29 = ICRegisters.ymm29;
	public static final ICRegister ymm30 = ICRegisters.ymm30;
	public static final ICRegister ymm31 = ICRegisters.ymm31;
	public static final ICRegister zmm0 = ICRegisters.zmm0;
	public static final ICRegister zmm1 = ICRegisters.zmm1;
	public static final ICRegister zmm2 = ICRegisters.zmm2;
	public static final ICRegister zmm3 = ICRegisters.zmm3;
	public static final ICRegister zmm4 = ICRegisters.zmm4;
	public static final ICRegister zmm5 = ICRegisters.zmm5;
	public static final ICRegister zmm6 = ICRegisters.zmm6;
	public static final ICRegister zmm7 = ICRegisters.zmm7;
	public static final ICRegister zmm8 = ICRegisters.zmm8;
	public static final ICRegister zmm9 = ICRegisters.zmm9;
	public static final ICRegister zmm10 = ICRegisters.zmm10;
	public static final ICRegister zmm11 = ICRegisters.zmm11;
	public static final ICRegister zmm12 = ICRegisters.zmm12;
	public static final ICRegister zmm13 = ICRegisters.zmm13;
	public static final ICRegister zmm14 = ICRegisters.zmm14;
	public static final ICRegister zmm15 = ICRegisters.zmm15;
	public static final ICRegister zmm16 = ICRegisters.zmm16;
	public static final ICRegister zmm17 = ICRegisters.zmm17;
	public static final ICRegister zmm18 = ICRegisters.zmm18;
	public static final ICRegister zmm19 = ICRegisters.zmm19;
	public static final ICRegister zmm20 = ICRegisters.zmm20;
	public static final ICRegister zmm21 = ICRegisters.zmm21;
	public static final ICRegister zmm22 = ICRegisters.zmm22;
	public static final ICRegister zmm23 = ICRegisters.zmm23;
	public static final ICRegister zmm24 = ICRegisters.zmm24;
	public static final ICRegister zmm25 = ICRegisters.zmm25;
	public static final ICRegister zmm26 = ICRegisters.zmm26;
	public static final ICRegister zmm27 = ICRegisters.zmm27;
	public static final ICRegister zmm28 = ICRegisters.zmm28;
	public static final ICRegister zmm29 = ICRegisters.zmm29;
	public static final ICRegister zmm30 = ICRegisters.zmm30;
	public static final ICRegister zmm31 = ICRegisters.zmm31;
}
