// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86;

/**
 * Registers passed to {@code Instruction.create()} methods.
 *
 * @see ICRegisters
 * @see ICRegistersGPR
 * @see ICRegistersVec
 * @see ICRegistersGPR16
 * @see ICRegistersGPR32
 * @see ICRegistersGPR64
 * @see ICRegistersIP
 * @see ICRegistersSegment
 * @see ICRegistersST
 * @see ICRegistersCR
 * @see ICRegistersDR
 * @see ICRegistersTR
 * @see ICRegistersBND
 * @see ICRegistersK
 * @see ICRegistersMM
 * @see ICRegistersXMM
 * @see ICRegistersYMM
 * @see ICRegistersZMM
 * @see ICRegistersTMM
 */
public final class ICRegistersGPR8 {
	private ICRegistersGPR8() {
	}

	public static final ICRegister al = ICRegisters.al;
	public static final ICRegister cl = ICRegisters.cl;
	public static final ICRegister dl = ICRegisters.dl;
	public static final ICRegister bl = ICRegisters.bl;
	public static final ICRegister ah = ICRegisters.ah;
	public static final ICRegister ch = ICRegisters.ch;
	public static final ICRegister dh = ICRegisters.dh;
	public static final ICRegister bh = ICRegisters.bh;
	public static final ICRegister spl = ICRegisters.spl;
	public static final ICRegister bpl = ICRegisters.bpl;
	public static final ICRegister sil = ICRegisters.sil;
	public static final ICRegister dil = ICRegisters.dil;
	public static final ICRegister r8b = ICRegisters.r8b;
	public static final ICRegister r9b = ICRegisters.r9b;
	public static final ICRegister r10b = ICRegisters.r10b;
	public static final ICRegister r11b = ICRegisters.r11b;
	public static final ICRegister r12b = ICRegisters.r12b;
	public static final ICRegister r13b = ICRegisters.r13b;
	public static final ICRegister r14b = ICRegisters.r14b;
	public static final ICRegister r15b = ICRegisters.r15b;
}
