// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86;

/**
 * Registers passed to {@code Instruction.create()} methods.
 *
 * @see ICRegisters
 * @see ICRegistersGPR
 * @see ICRegistersVec
 * @see ICRegistersGPR8
 * @see ICRegistersGPR16
 * @see ICRegistersGPR32
 * @see ICRegistersGPR64
 * @see ICRegistersIP
 * @see ICRegistersSegment
 * @see ICRegistersST
 * @see ICRegistersCR
 * @see ICRegistersDR
 * @see ICRegistersTR
 * @see ICRegistersK
 * @see ICRegistersMM
 * @see ICRegistersXMM
 * @see ICRegistersYMM
 * @see ICRegistersZMM
 * @see ICRegistersTMM
 */
public final class ICRegistersBND {
	private ICRegistersBND() {
	}

	public static final ICRegister bnd0 = ICRegisters.bnd0;
	public static final ICRegister bnd1 = ICRegisters.bnd1;
	public static final ICRegister bnd2 = ICRegisters.bnd2;
	public static final ICRegister bnd3 = ICRegisters.bnd3;
}
