// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86;

/**
 * (MVEX) EH bit value
 */
public final class MvexEHBit {
	private MvexEHBit() {
	}

	/**
	 * Not hard coded to 0 or 1 so can be used for other purposes
	 */
	public static final int NONE = 0;
	/**
	 * EH bit must be 0
	 */
	public static final int EH0 = 1;
	/**
	 * EH bit must be 1
	 */
	public static final int EH1 = 2;
}
