// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.fmt;

import java.util.HashMap;

final class MnemonicOptionsDict {
	static final HashMap<String, Integer> toFormatMnemonicOptions = createFormatMnemonicOptions();
	private static HashMap<String, Integer> createFormatMnemonicOptions() {
		HashMap<String, Integer> map = new HashMap<String, Integer>(2);
		map.put("noprefixes", FormatMnemonicOptions.NO_PREFIXES);
		map.put("nomnemonic", FormatMnemonicOptions.NO_MNEMONIC);
		return map;
	}
}
