#
# Copyright (C) 2018-2019 de4dot@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

# ⚠️This file was generated by GENERATOR!🦹‍♂️

# pylint: disable=invalid-name
# pylint: disable=line-too-long
# pylint: disable=too-many-lines

"""
Tuple type (EVEX) which can be used to get the disp8 scale factor ``N``
"""

from typing import List

N1: int = 0
"""
``N = 1``
"""
N2: int = 1
"""
``N = 2``
"""
N4: int = 2
"""
``N = 4``
"""
N8: int = 3
"""
``N = 8``
"""
N16: int = 4
"""
``N = 16``
"""
N32: int = 5
"""
``N = 32``
"""
N64: int = 6
"""
``N = 64``
"""
N8B4: int = 7
"""
``N = b ? 4 : 8``
"""
N16B4: int = 8
"""
``N = b ? 4 : 16``
"""
N32B4: int = 9
"""
``N = b ? 4 : 32``
"""
N64B4: int = 10
"""
``N = b ? 4 : 64``
"""
N16B8: int = 11
"""
``N = b ? 8 : 16``
"""
N32B8: int = 12
"""
``N = b ? 8 : 32``
"""
N64B8: int = 13
"""
``N = b ? 8 : 64``
"""

__all__: List[str] = []
