// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.fmt.masm;

final class CtorKind {
	private CtorKind() {
	}

	static final int PREVIOUS = 0;
	static final int NORMAL_1 = 1;
	static final int NORMAL_2 = 2;
	static final int AAM_AAD = 3;
	static final int AX = 4;
	static final int AY = 5;
	static final int BND = 6;
	static final int STIG1 = 7;
	static final int DECLARE_DATA = 8;
	static final int DX = 9;
	static final int FWORD = 10;
	static final int INT3 = 11;
	static final int IMUL = 12;
	static final int INVLPGA = 13;
	static final int CCA_1 = 14;
	static final int CCA_2 = 15;
	static final int CCA_3 = 16;
	static final int CCB_1 = 17;
	static final int CCB_2 = 18;
	static final int CCB_3 = 19;
	static final int JCC_1 = 20;
	static final int JCC_2 = 21;
	static final int JCC_3 = 22;
	static final int LOOPCC1 = 23;
	static final int LOOPCC2 = 24;
	static final int MASKMOVQ = 25;
	static final int MEMSIZE = 26;
	static final int YD = 27;
	static final int YX = 28;
	static final int MONITOR = 29;
	static final int MWAIT = 30;
	static final int MWAITX = 31;
	static final int NOP = 32;
	static final int OP_SIZE_1 = 33;
	static final int OP_SIZE_2 = 34;
	static final int OP_SIZE2 = 35;
	static final int YA = 36;
	static final int PBLENDVB = 37;
	static final int PCLMULQDQ = 38;
	static final int POPS_2 = 39;
	static final int POPS_3 = 40;
	static final int XY = 41;
	static final int REG = 42;
	static final int REG16 = 43;
	static final int REG32 = 44;
	static final int REVERSE = 45;
	static final int ST_STI = 46;
	static final int STI_ST = 47;
	static final int XLAT = 48;
}
