// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

package com.github.icedland.iced.x86.asm;

/**
 * Registers passed to {@link CodeAssembler} methods
 *
 * @see AsmRegisters
 * @see AsmRegistersGPR
 * @see AsmRegistersVec
 * @see AsmRegistersGPR8
 * @see AsmRegistersGPR16
 * @see AsmRegistersGPR32
 * @see AsmRegistersGPR64
 * @see AsmRegistersIP
 * @see AsmRegistersSegment
 * @see AsmRegistersST
 * @see AsmRegistersCR
 * @see AsmRegistersDR
 * @see AsmRegistersTR
 * @see AsmRegistersBND
 * @see AsmRegistersK
 * @see AsmRegistersXMM
 * @see AsmRegistersYMM
 * @see AsmRegistersZMM
 * @see AsmRegistersTMM
 */
public final class AsmRegistersMM {
	private AsmRegistersMM() {
	}

	public static final AsmRegisterMM mm0 = AsmRegisters.mm0;
	public static final AsmRegisterMM mm1 = AsmRegisters.mm1;
	public static final AsmRegisterMM mm2 = AsmRegisters.mm2;
	public static final AsmRegisterMM mm3 = AsmRegisters.mm3;
	public static final AsmRegisterMM mm4 = AsmRegisters.mm4;
	public static final AsmRegisterMM mm5 = AsmRegisters.mm5;
	public static final AsmRegisterMM mm6 = AsmRegisters.mm6;
	public static final AsmRegisterMM mm7 = AsmRegisters.mm7;
}
