/*
    Copyright (C) 2018-2019 de4dot@gmail.com

    This file is part of Iced.

    Iced is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Iced is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Iced.  If not, see <https://www.gnu.org/licenses/>.
*/

#if !NO_INTEL_FORMATTER && !NO_FORMATTER
using System.Collections.Generic;
using Xunit;

namespace Iced.UnitTests.Intel.FormatterTests.Intel {
	public sealed class IntelFormatterTest64_ForceMemSize_004 : FormatterTest {
		[Theory]
		[MemberData(nameof(Format_Data))]
		void Format(int index, InstructionInfo info, string formattedString) => FormatBase(index, info, formattedString, IntelFormatterFactory.Create_ForceMemSize());
		public static IEnumerable<object[]> Format_Data => GetFormatData(infos, formattedStrings);

		static readonly InstructionInfo[] infos = InstructionInfos64_004.AllInfos;
		static readonly string[] formattedStrings = new string[InstructionInfos64_004.AllInfos_Length] {
			"vpsllw ymm2{k3}, ymm6, xmmword ptr [rax+0x10]",
			"vpsllw zmm2{k3}, zmm6, xmm3",
			"vpsllw zmm2{k3}, zmm6, xmmword ptr [rax+0x10]",
			"pslld mmx1, mmx5",
			"pslld mmx1, qword ptr [rax]",
			"pslld xmm1, xmm5",
			"pslld xmm1, xmmword ptr [rax]",
			"vpslld xmm2, xmm6, xmm3",
			"vpslld xmm2, xmm6, xmmword ptr [rax]",
			"vpslld ymm2, ymm6, xmm3",
			"vpslld ymm2, ymm6, xmmword ptr [rax]",
			"vpslld xmm2{k3}, xmm6, xmm3",
			"vpslld xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpslld ymm2{k3}, ymm6, xmm3",
			"vpslld ymm2{k3}, ymm6, xmmword ptr [rax+0x10]",
			"vpslld zmm2{k3}, zmm6, xmm3",
			"vpslld zmm2{k3}, zmm6, xmmword ptr [rax+0x10]",
			"psllq mmx1, mmx5",
			"psllq mmx1, qword ptr [rax]",
			"psllq xmm1, xmm5",
			"psllq xmm1, xmmword ptr [rax]",
			"vpsllq xmm2, xmm6, xmm3",
			"vpsllq xmm2, xmm6, xmmword ptr [rax]",
			"vpsllq ymm2, ymm6, xmm3",
			"vpsllq ymm2, ymm6, xmmword ptr [rax]",
			"vpsllq xmm2{k3}, xmm6, xmm3",
			"vpsllq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsllq ymm2{k3}, ymm6, xmm3",
			"vpsllq ymm2{k3}, ymm6, xmmword ptr [rax+0x10]",
			"vpsllq zmm2{k3}, zmm6, xmm3",
			"vpsllq zmm2{k3}, zmm6, xmmword ptr [rax+0x10]",
			"pmuludq mmx1, mmx5",
			"pmuludq mmx1, qword ptr [rax]",
			"pmuludq xmm1, xmm5",
			"pmuludq xmm1, xmmword ptr [rax]",
			"vpmuludq xmm2, xmm6, xmm3",
			"vpmuludq xmm2, xmm6, xmmword ptr [rax]",
			"vpmuludq ymm2, ymm6, ymm3",
			"vpmuludq ymm2, ymm6, ymmword ptr [rax]",
			"vpmuludq xmm2{k3}{z}, xmm6, xmm3",
			"vpmuludq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpmuludq xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vpmuludq ymm2{k3}{z}, ymm6, ymm3",
			"vpmuludq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpmuludq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpmuludq zmm2{k3}{z}, zmm6, zmm3",
			"vpmuludq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpmuludq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"pmaddwd mmx1, mmx5",
			"pmaddwd mmx1, qword ptr [rax]",
			"pmaddwd xmm1, xmm5",
			"pmaddwd xmm1, xmmword ptr [rax]",
			"vpmaddwd xmm2, xmm6, xmm3",
			"vpmaddwd xmm2, xmm6, xmmword ptr [rax]",
			"vpmaddwd ymm2, ymm6, ymm3",
			"vpmaddwd ymm2, ymm6, ymmword ptr [rax]",
			"vpmaddwd xmm2{k3}, xmm6, xmm3",
			"vpmaddwd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpmaddwd ymm2{k3}, ymm6, ymm3",
			"vpmaddwd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpmaddwd zmm2{k3}, zmm6, zmm3",
			"vpmaddwd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"psadbw mmx1, mmx5",
			"psadbw mmx1, qword ptr [rax]",
			"psadbw xmm1, xmm5",
			"psadbw xmm1, xmmword ptr [rax]",
			"vpsadbw xmm2, xmm6, xmm3",
			"vpsadbw xmm2, xmm6, xmmword ptr [rax]",
			"vpsadbw ymm2, ymm6, ymm3",
			"vpsadbw ymm2, ymm6, ymmword ptr [rax]",
			"vpsadbw xmm2, xmm6, xmm3",
			"vpsadbw xmm2, xmm6, xmmword ptr [rax+0x10]",
			"vpsadbw ymm2, ymm6, ymm3",
			"vpsadbw ymm2, ymm6, ymmword ptr [rax+0x20]",
			"vpsadbw zmm2, zmm6, zmm3",
			"vpsadbw zmm2, zmm6, zmmword ptr [rax+0x40]",
			"addr32 maskmovq mmx2, mmx3",
			"maskmovq mmx2, mmx3",
			"addr32 maskmovdqu xmm2, xmm3",
			"maskmovdqu xmm2, xmm3",
			"addr32 vmaskmovdqu xmm2, xmm3",
			"vmaskmovdqu xmm2, xmm3",
			"psubb mmx1, mmx5",
			"psubb mmx1, qword ptr [rax]",
			"psubb xmm1, xmm5",
			"psubb xmm1, xmmword ptr [rax]",
			"vpsubb xmm2, xmm6, xmm3",
			"vpsubb xmm2, xmm6, xmmword ptr [rax]",
			"vpsubb ymm2, ymm6, ymm3",
			"vpsubb ymm2, ymm6, ymmword ptr [rax]",
			"vpsubb xmm2{k3}, xmm6, xmm3",
			"vpsubb xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsubb ymm2{k3}, ymm6, ymm3",
			"vpsubb ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsubb zmm2{k3}, zmm6, zmm3",
			"vpsubb zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"psubw mmx1, mmx5",
			"psubw mmx1, qword ptr [rax]",
			"psubw xmm1, xmm5",
			"psubw xmm1, xmmword ptr [rax]",
			"vpsubw xmm2, xmm6, xmm3",
			"vpsubw xmm2, xmm6, xmmword ptr [rax]",
			"vpsubw ymm2, ymm6, ymm3",
			"vpsubw ymm2, ymm6, ymmword ptr [rax]",
			"vpsubw xmm2{k3}, xmm6, xmm3",
			"vpsubw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsubw ymm2{k3}, ymm6, ymm3",
			"vpsubw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsubw zmm2{k3}, zmm6, zmm3",
			"vpsubw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"psubd mmx1, mmx5",
			"psubd mmx1, qword ptr [rax]",
			"psubd xmm1, xmm5",
			"psubd xmm1, xmmword ptr [rax]",
			"vpsubd xmm2, xmm6, xmm3",
			"vpsubd xmm2, xmm6, xmmword ptr [rax]",
			"vpsubd ymm2, ymm6, ymm3",
			"vpsubd ymm2, ymm6, ymmword ptr [rax]",
			"vpsubd xmm2{k3}{z}, xmm6, xmm3",
			"vpsubd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsubd xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vpsubd ymm2{k3}{z}, ymm6, ymm3",
			"vpsubd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsubd ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpsubd zmm2{k3}{z}, zmm6, zmm3",
			"vpsubd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpsubd zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"psubq mmx1, mmx5",
			"psubq mmx1, qword ptr [rax]",
			"psubq xmm1, xmm5",
			"psubq xmm1, xmmword ptr [rax]",
			"vpsubq xmm2, xmm6, xmm3",
			"vpsubq xmm2, xmm6, xmmword ptr [rax]",
			"vpsubq ymm2, ymm6, ymm3",
			"vpsubq ymm2, ymm6, ymmword ptr [rax]",
			"vpsubq xmm2{k3}{z}, xmm6, xmm3",
			"vpsubq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsubq xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vpsubq ymm2{k3}{z}, ymm6, ymm3",
			"vpsubq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsubq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpsubq zmm2{k3}{z}, zmm6, zmm3",
			"vpsubq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpsubq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"paddb mmx1, mmx5",
			"paddb mmx1, qword ptr [rax]",
			"paddb xmm1, xmm5",
			"paddb xmm1, xmmword ptr [rax]",
			"vpaddb xmm2, xmm6, xmm3",
			"vpaddb xmm2, xmm6, xmmword ptr [rax]",
			"vpaddb ymm2, ymm6, ymm3",
			"vpaddb ymm2, ymm6, ymmword ptr [rax]",
			"vpaddb xmm2{k3}, xmm6, xmm3",
			"vpaddb xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpaddb ymm2{k3}, ymm6, ymm3",
			"vpaddb ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpaddb zmm2{k3}, zmm6, zmm3",
			"vpaddb zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"paddw mmx1, mmx5",
			"paddw mmx1, qword ptr [rax]",
			"paddw xmm1, xmm5",
			"paddw xmm1, xmmword ptr [rax]",
			"vpaddw xmm2, xmm6, xmm3",
			"vpaddw xmm2, xmm6, xmmword ptr [rax]",
			"vpaddw ymm2, ymm6, ymm3",
			"vpaddw ymm2, ymm6, ymmword ptr [rax]",
			"vpaddw xmm2{k3}, xmm6, xmm3",
			"vpaddw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpaddw ymm2{k3}, ymm6, ymm3",
			"vpaddw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpaddw zmm2{k3}, zmm6, zmm3",
			"vpaddw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"paddd mmx1, mmx5",
			"paddd mmx1, qword ptr [rax]",
			"paddd xmm1, xmm5",
			"paddd xmm1, xmmword ptr [rax]",
			"vpaddd xmm2, xmm6, xmm3",
			"vpaddd xmm2, xmm6, xmmword ptr [rax]",
			"vpaddd ymm2, ymm6, ymm3",
			"vpaddd ymm2, ymm6, ymmword ptr [rax]",
			"vpaddd xmm2{k3}{z}, xmm6, xmm3",
			"vpaddd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpaddd xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vpaddd ymm2{k3}{z}, ymm6, ymm3",
			"vpaddd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpaddd ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpaddd zmm2{k3}{z}, zmm6, zmm3",
			"vpaddd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpaddd zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"ud0 cx, si",
			"ud0 bx, word ptr [rax]",
			"ud0 ecx, esi",
			"ud0 ebx, dword ptr [rax]",
			"ud0 rcx, rsi",
			"ud0 rbx, qword ptr [rax]",
			"pshufb mmx1, mmx5",
			"pshufb mmx1, qword ptr [rax]",
			"pshufb xmm1, xmm5",
			"pshufb xmm1, xmmword ptr [rax]",
			"vpshufb xmm2, xmm6, xmm3",
			"vpshufb xmm2, xmm6, xmmword ptr [rax]",
			"vpshufb ymm2, ymm6, ymm3",
			"vpshufb ymm2, ymm6, ymmword ptr [rax]",
			"vpshufb xmm2{k3}, xmm6, xmm3",
			"vpshufb xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpshufb ymm2{k3}, ymm6, ymm3",
			"vpshufb ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpshufb zmm2{k3}, zmm6, zmm3",
			"vpshufb zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"phaddw mmx1, mmx5",
			"phaddw mmx1, qword ptr [rax]",
			"phaddw xmm1, xmm5",
			"phaddw xmm1, xmmword ptr [rax]",
			"vphaddw xmm2, xmm6, xmm3",
			"vphaddw xmm2, xmm6, xmmword ptr [rax]",
			"vphaddw ymm2, ymm6, ymm3",
			"vphaddw ymm2, ymm6, ymmword ptr [rax]",
			"phaddd mmx1, mmx5",
			"phaddd mmx1, qword ptr [rax]",
			"phaddd xmm1, xmm5",
			"phaddd xmm1, xmmword ptr [rax]",
			"vphaddd xmm2, xmm6, xmm3",
			"vphaddd xmm2, xmm6, xmmword ptr [rax]",
			"vphaddd ymm2, ymm6, ymm3",
			"vphaddd ymm2, ymm6, ymmword ptr [rax]",
			"phaddsw mmx1, mmx5",
			"phaddsw mmx1, qword ptr [rax]",
			"phaddsw xmm1, xmm5",
			"phaddsw xmm1, xmmword ptr [rax]",
			"vphaddsw xmm2, xmm6, xmm3",
			"vphaddsw xmm2, xmm6, xmmword ptr [rax]",
			"vphaddsw ymm2, ymm6, ymm3",
			"vphaddsw ymm2, ymm6, ymmword ptr [rax]",
			"pmaddubsw mmx1, mmx5",
			"pmaddubsw mmx1, qword ptr [rax]",
			"pmaddubsw xmm1, xmm5",
			"pmaddubsw xmm1, xmmword ptr [rax]",
			"vpmaddubsw xmm2, xmm6, xmm3",
			"vpmaddubsw xmm2, xmm6, xmmword ptr [rax]",
			"vpmaddubsw ymm2, ymm6, ymm3",
			"vpmaddubsw ymm2, ymm6, ymmword ptr [rax]",
			"vpmaddubsw xmm2{k3}, xmm6, xmm3",
			"vpmaddubsw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpmaddubsw ymm2{k3}, ymm6, ymm3",
			"vpmaddubsw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpmaddubsw zmm2{k3}, zmm6, zmm3",
			"vpmaddubsw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"phsubw mmx1, mmx5",
			"phsubw mmx1, qword ptr [rax]",
			"phsubw xmm1, xmm5",
			"phsubw xmm1, xmmword ptr [rax]",
			"vphsubw xmm2, xmm6, xmm3",
			"vphsubw xmm2, xmm6, xmmword ptr [rax]",
			"vphsubw ymm2, ymm6, ymm3",
			"vphsubw ymm2, ymm6, ymmword ptr [rax]",
			"phsubd mmx1, mmx5",
			"phsubd mmx1, qword ptr [rax]",
			"phsubd xmm1, xmm5",
			"phsubd xmm1, xmmword ptr [rax]",
			"vphsubd xmm2, xmm6, xmm3",
			"vphsubd xmm2, xmm6, xmmword ptr [rax]",
			"vphsubd ymm2, ymm6, ymm3",
			"vphsubd ymm2, ymm6, ymmword ptr [rax]",
			"phsubsw mmx1, mmx5",
			"phsubsw mmx1, qword ptr [rax]",
			"phsubsw xmm1, xmm5",
			"phsubsw xmm1, xmmword ptr [rax]",
			"vphsubsw xmm2, xmm6, xmm3",
			"vphsubsw xmm2, xmm6, xmmword ptr [rax]",
			"vphsubsw ymm2, ymm6, ymm3",
			"vphsubsw ymm2, ymm6, ymmword ptr [rax]",
			"psignb mmx1, mmx5",
			"psignb mmx1, qword ptr [rax]",
			"psignb xmm1, xmm5",
			"psignb xmm1, xmmword ptr [rax]",
			"vpsignb xmm2, xmm6, xmm3",
			"vpsignb xmm2, xmm6, xmmword ptr [rax]",
			"vpsignb ymm2, ymm6, ymm3",
			"vpsignb ymm2, ymm6, ymmword ptr [rax]",
			"psignw mmx1, mmx5",
			"psignw mmx1, qword ptr [rax]",
			"psignw xmm1, xmm5",
			"psignw xmm1, xmmword ptr [rax]",
			"vpsignw xmm2, xmm6, xmm3",
			"vpsignw xmm2, xmm6, xmmword ptr [rax]",
			"vpsignw ymm2, ymm6, ymm3",
			"vpsignw ymm2, ymm6, ymmword ptr [rax]",
			"psignd mmx1, mmx5",
			"psignd mmx1, qword ptr [rax]",
			"psignd xmm1, xmm5",
			"psignd xmm1, xmmword ptr [rax]",
			"vpsignd xmm2, xmm6, xmm3",
			"vpsignd xmm2, xmm6, xmmword ptr [rax]",
			"vpsignd ymm2, ymm6, ymm3",
			"vpsignd ymm2, ymm6, ymmword ptr [rax]",
			"pmulhrsw mmx1, mmx5",
			"pmulhrsw mmx1, qword ptr [rax]",
			"pmulhrsw xmm1, xmm5",
			"pmulhrsw xmm1, xmmword ptr [rax]",
			"vpmulhrsw xmm2, xmm6, xmm3",
			"vpmulhrsw xmm2, xmm6, xmmword ptr [rax]",
			"vpmulhrsw ymm2, ymm6, ymm3",
			"vpmulhrsw ymm2, ymm6, ymmword ptr [rax]",
			"vpmulhrsw xmm2{k3}, xmm6, xmm3",
			"vpmulhrsw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpmulhrsw ymm2{k3}, ymm6, ymm3",
			"vpmulhrsw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpmulhrsw zmm2{k3}, zmm6, zmm3",
			"vpmulhrsw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermilps xmm2, xmm6, xmm3",
			"vpermilps xmm2, xmm6, xmmword ptr [rax]",
			"vpermilps ymm2, ymm6, ymm3",
			"vpermilps ymm2, ymm6, ymmword ptr [rax]",
			"vpermilps xmm2{k3}{z}, xmm6, xmm3",
			"vpermilps xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpermilps xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vpermilps ymm2{k3}{z}, ymm6, ymm3",
			"vpermilps ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpermilps ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpermilps zmm2{k3}{z}, zmm6, zmm3",
			"vpermilps zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermilps zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vpermilpd xmm2, xmm6, xmm3",
			"vpermilpd xmm2, xmm6, xmmword ptr [rax]",
			"vpermilpd ymm2, ymm6, ymm3",
			"vpermilpd ymm2, ymm6, ymmword ptr [rax]",
			"vpermilpd xmm2{k3}{z}, xmm6, xmm3",
			"vpermilpd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpermilpd xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vpermilpd ymm2{k3}{z}, ymm6, ymm3",
			"vpermilpd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpermilpd ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpermilpd zmm2{k3}{z}, zmm6, zmm3",
			"vpermilpd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermilpd zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"vtestps xmm1, xmm5",
			"vtestps xmm2, xmmword ptr [rax]",
			"vtestps ymm1, ymm5",
			"vtestps ymm2, ymmword ptr [rax]",
			"vtestpd xmm1, xmm5",
			"vtestpd xmm2, xmmword ptr [rax]",
			"vtestpd ymm1, ymm5",
			"vtestpd ymm2, ymmword ptr [rax]",
			"pblendvb xmm1, xmm5",
			"pblendvb xmm1, xmmword ptr [rax]",
			"vpsrlvw xmm2{k3}, xmm6, xmm3",
			"vpsrlvw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsrlvw ymm2{k3}, ymm6, ymm3",
			"vpsrlvw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsrlvw zmm2{k3}, zmm6, zmm3",
			"vpsrlvw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpmovuswb xmm3{k3}, xmm2",
			"vpmovuswb qword ptr [rax+8]{k3}, xmm2",
			"vpmovuswb xmm3{k3}, ymm2",
			"vpmovuswb xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovuswb ymm3{k3}, zmm2",
			"vpmovuswb ymmword ptr [rax+0x20]{k3}, zmm2",
			"vpsravw xmm2{k3}, xmm6, xmm3",
			"vpsravw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsravw ymm2{k3}, ymm6, ymm3",
			"vpsravw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsravw zmm2{k3}, zmm6, zmm3",
			"vpsravw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpmovusdb xmm3{k3}, xmm2",
			"vpmovusdb dword ptr [rax+4]{k3}, xmm2",
			"vpmovusdb xmm3{k3}, ymm2",
			"vpmovusdb qword ptr [rax+8]{k3}, ymm2",
			"vpmovusdb xmm3{k3}, zmm2",
			"vpmovusdb xmmword ptr [rax+0x10]{k3}, zmm2",
			"vpsllvw xmm2{k3}, xmm6, xmm3",
			"vpsllvw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpsllvw ymm2{k3}, ymm6, ymm3",
			"vpsllvw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpsllvw zmm2{k3}, zmm6, zmm3",
			"vpsllvw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpmovusqb xmm3{k3}, xmm2",
			"vpmovusqb word ptr [rax+2]{k3}, xmm2",
			"vpmovusqb xmm3{k3}, ymm2",
			"vpmovusqb dword ptr [rax+4]{k3}, ymm2",
			"vpmovusqb xmm3{k3}, zmm2",
			"vpmovusqb qword ptr [rax+8]{k3}, zmm2",
			"vcvtph2ps xmm1, xmm5",
			"vcvtph2ps xmm2, qword ptr [rax]",
			"vcvtph2ps ymm1, xmm5",
			"vcvtph2ps ymm2, xmmword ptr [rax]",
			"vcvtph2ps xmm2{k3}{z}, xmm3",
			"vcvtph2ps xmm2{k3}, qword ptr [rax+8]",
			"vcvtph2ps ymm2{k3}{z}, xmm3",
			"vcvtph2ps ymm2{k3}, xmmword ptr [rax+0x10]",
			"vcvtph2ps zmm2{k3}{z}{sae}, ymm3",
			"vcvtph2ps zmm2{k3}, ymmword ptr [rax+0x20]",
			"vpmovusdw xmm3{k3}, xmm2",
			"vpmovusdw qword ptr [rax+8]{k3}, xmm2",
			"vpmovusdw xmm3{k3}, ymm2",
			"vpmovusdw xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovusdw ymm3{k3}, zmm2",
			"vpmovusdw ymmword ptr [rax+0x20]{k3}, zmm2",
			"blendvps xmm1, xmm5",
			"blendvps xmm1, xmmword ptr [rax]",
			"vprorvd xmm2{k3}{z}, xmm6, xmm3",
			"vprorvd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vprorvd xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vprorvd ymm2{k3}{z}, ymm6, ymm3",
			"vprorvd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vprorvd ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vprorvd zmm2{k3}{z}, zmm6, zmm3",
			"vprorvd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vprorvd zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vprorvq xmm2{k3}{z}, xmm6, xmm3",
			"vprorvq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vprorvq xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vprorvq ymm2{k3}{z}, ymm6, ymm3",
			"vprorvq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vprorvq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vprorvq zmm2{k3}{z}, zmm6, zmm3",
			"vprorvq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vprorvq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"vpmovusqw xmm3{k3}, xmm2",
			"vpmovusqw dword ptr [rax+4]{k3}, xmm2",
			"vpmovusqw xmm3{k3}, ymm2",
			"vpmovusqw qword ptr [rax+8]{k3}, ymm2",
			"vpmovusqw xmm3{k3}, zmm2",
			"vpmovusqw xmmword ptr [rax+0x10]{k3}, zmm2",
			"blendvpd xmm1, xmm5",
			"blendvpd xmm1, xmmword ptr [rax]",
			"vprolvd xmm2{k3}{z}, xmm6, xmm3",
			"vprolvd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vprolvd xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vprolvd ymm2{k3}{z}, ymm6, ymm3",
			"vprolvd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vprolvd ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vprolvd zmm2{k3}{z}, zmm6, zmm3",
			"vprolvd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vprolvd zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vprolvq xmm2{k3}{z}, xmm6, xmm3",
			"vprolvq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vprolvq xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vprolvq ymm2{k3}{z}, ymm6, ymm3",
			"vprolvq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vprolvq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vprolvq zmm2{k3}{z}, zmm6, zmm3",
			"vprolvq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vprolvq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"vpmovusqd xmm3{k3}, xmm2",
			"vpmovusqd qword ptr [rax+8]{k3}, xmm2",
			"vpmovusqd xmm3{k3}, ymm2",
			"vpmovusqd xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovusqd ymm3{k3}, zmm2",
			"vpmovusqd ymmword ptr [rax+0x20]{k3}, zmm2",
			"vpermps ymm2, ymm6, ymm3",
			"vpermps ymm2, ymm6, ymmword ptr [rax]",
			"vpermps ymm2{k3}{z}, ymm6, ymm3",
			"vpermps ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpermps ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpermps zmm2{k3}{z}, zmm6, zmm3",
			"vpermps zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermps zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vpermpd ymm2{k3}{z}, ymm6, ymm3",
			"vpermpd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpermpd ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpermpd zmm2{k3}{z}, zmm6, zmm3",
			"vpermpd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermpd zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"ptest xmm1, xmm5",
			"ptest xmm1, xmmword ptr [rax]",
			"vptest xmm1, xmm5",
			"vptest xmm2, xmmword ptr [rax]",
			"vptest ymm1, ymm5",
			"vptest ymm2, ymmword ptr [rax]",
			"vbroadcastss xmm1, xmm5",
			"vbroadcastss xmm2, dword ptr [rax]",
			"vbroadcastss ymm1, xmm5",
			"vbroadcastss ymm2, dword ptr [rax]",
			"vbroadcastss xmm2, xmm3",
			"vbroadcastss xmm2, dword ptr [rax+4]",
			"vbroadcastss ymm2, xmm3",
			"vbroadcastss ymm2, dword ptr [rax+4]",
			"vbroadcastss zmm2, xmm3",
			"vbroadcastss zmm2, dword ptr [rax+4]",
			"vbroadcastsd ymm1, xmm5",
			"vbroadcastsd ymm2, qword ptr [rax]",
			"vbroadcastf32x2 ymm2, xmm3",
			"vbroadcastf32x2 ymm2, qword ptr [rax+8]",
			"vbroadcastf32x2 zmm2, xmm3",
			"vbroadcastf32x2 zmm2, qword ptr [rax+8]",
			"vbroadcastsd ymm2, xmm3",
			"vbroadcastsd ymm2, qword ptr [rax+8]",
			"vbroadcastsd zmm2, xmm3",
			"vbroadcastsd zmm2, qword ptr [rax+8]",
			"vbroadcastf128 ymm2, xmmword ptr [rax]",
			"vbroadcastf32x4 ymm2, xmmword ptr [rax+0x10]",
			"vbroadcastf32x4 zmm2, xmmword ptr [rax+0x10]",
			"vbroadcastf64x2 ymm2, xmmword ptr [rax+0x10]",
			"vbroadcastf64x2 zmm2, xmmword ptr [rax+0x10]",
			"vbroadcastf32x8 zmm2, ymmword ptr [rax+0x20]",
			"vbroadcastf64x4 zmm2, ymmword ptr [rax+0x20]",
			"pabsb mmx1, mmx5",
			"pabsb mmx1, qword ptr [rax]",
			"pabsb xmm1, xmm5",
			"pabsb xmm1, xmmword ptr [rax]",
			"vpabsb xmm1, xmm5",
			"vpabsb xmm2, xmmword ptr [rax]",
			"vpabsb ymm1, ymm5",
			"vpabsb ymm2, ymmword ptr [rax]",
			"vpabsb xmm2, xmm3",
			"vpabsb xmm2, xmmword ptr [rax+0x10]",
			"vpabsb ymm2, ymm3",
			"vpabsb ymm2, ymmword ptr [rax+0x20]",
			"vpabsb zmm2, zmm3",
			"vpabsb zmm2, zmmword ptr [rax+0x40]",
			"pabsw mmx1, mmx5",
			"pabsw mmx1, qword ptr [rax]",
			"pabsw xmm1, xmm5",
			"pabsw xmm1, xmmword ptr [rax]",
			"vpabsw xmm1, xmm5",
			"vpabsw xmm2, xmmword ptr [rax]",
			"vpabsw ymm1, ymm5",
			"vpabsw ymm2, ymmword ptr [rax]",
			"vpabsw xmm2, xmm3",
			"vpabsw xmm2, xmmword ptr [rax+0x10]",
			"vpabsw ymm2, ymm3",
			"vpabsw ymm2, ymmword ptr [rax+0x20]",
			"vpabsw zmm2, zmm3",
			"vpabsw zmm2, zmmword ptr [rax+0x40]",
			"pabsd mmx1, mmx5",
			"pabsd mmx1, qword ptr [rax]",
			"pabsd xmm1, xmm5",
			"pabsd xmm1, xmmword ptr [rax]",
			"vpabsd xmm2, xmm3",
			"vpabsd xmm2, xmmword ptr [rax]",
			"vpabsd ymm2, ymm3",
			"vpabsd ymm2, ymmword ptr [rax]",
			"vpabsd xmm2{k3}{z}, xmm3",
			"vpabsd xmm2{k3}, xmmword ptr [rax+0x10]",
			"vpabsd xmm2{k5}{z}, dword ptr [rax+4]{1to4}",
			"vpabsd ymm2{k3}{z}, ymm3",
			"vpabsd ymm2{k3}, ymmword ptr [rax+0x20]",
			"vpabsd ymm2{k5}{z}, dword ptr [rax+4]{1to8}",
			"vpabsd zmm2{k3}{z}, zmm3",
			"vpabsd zmm2{k3}, zmmword ptr [rax+0x40]",
			"vpabsd zmm2{k5}{z}, dword ptr [rax+4]{1to16}",
			"vpabsq xmm2{k3}{z}, xmm3",
			"vpabsq xmm2{k3}, xmmword ptr [rax+0x10]",
			"vpabsq xmm2{k5}{z}, qword ptr [rax+8]{1to2}",
			"vpabsq ymm2{k3}{z}, ymm3",
			"vpabsq ymm2{k3}, ymmword ptr [rax+0x20]",
			"vpabsq ymm2{k5}{z}, qword ptr [rax+8]{1to4}",
			"vpabsq zmm2{k3}{z}, zmm3",
			"vpabsq zmm2{k3}, zmmword ptr [rax+0x40]",
			"vpabsq zmm2{k5}{z}, qword ptr [rax+8]{1to8}",
			"pmovsxbw xmm1, xmm5",
			"pmovsxbw xmm1, qword ptr [rax]",
			"vpmovsxbw xmm1, xmm5",
			"vpmovsxbw xmm2, qword ptr [rax]",
			"vpmovsxbw ymm1, xmm5",
			"vpmovsxbw ymm2, xmmword ptr [rax]",
			"vpmovsxbw xmm2, xmm3",
			"vpmovsxbw xmm2, qword ptr [rax+8]",
			"vpmovsxbw ymm2, xmm3",
			"vpmovsxbw ymm2, xmmword ptr [rax+0x10]",
			"vpmovsxbw zmm2, ymm3",
			"vpmovsxbw zmm2, ymmword ptr [rax+0x20]",
			"vpmovswb xmm3{k3}, xmm2",
			"vpmovswb qword ptr [rax+8]{k3}, xmm2",
			"vpmovswb xmm3{k3}, ymm2",
			"vpmovswb xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovswb ymm3{k3}, zmm2",
			"vpmovswb ymmword ptr [rax+0x20]{k3}, zmm2",
			"pmovsxbd xmm1, xmm5",
			"pmovsxbd xmm1, dword ptr [rax]",
			"vpmovsxbd xmm1, xmm5",
			"vpmovsxbd xmm2, dword ptr [rax]",
			"vpmovsxbd ymm1, xmm5",
			"vpmovsxbd ymm2, qword ptr [rax]",
			"vpmovsxbd xmm2, xmm3",
			"vpmovsxbd xmm2, dword ptr [rax+4]",
			"vpmovsxbd ymm2, xmm3",
			"vpmovsxbd ymm2, qword ptr [rax+8]",
			"vpmovsxbd zmm2, xmm3",
			"vpmovsxbd zmm2, xmmword ptr [rax+0x10]",
			"vpmovsdb xmm3{k3}, xmm2",
			"vpmovsdb dword ptr [rax+4]{k3}, xmm2",
			"vpmovsdb xmm3{k3}, ymm2",
			"vpmovsdb qword ptr [rax+8]{k3}, ymm2",
			"vpmovsdb xmm3{k3}, zmm2",
			"vpmovsdb xmmword ptr [rax+0x10]{k3}, zmm2",
			"pmovsxbq xmm1, xmm5",
			"pmovsxbq xmm1, word ptr [rax]",
			"vpmovsxbq xmm1, xmm5",
			"vpmovsxbq xmm2, word ptr [rax]",
			"vpmovsxbq ymm1, xmm5",
			"vpmovsxbq ymm2, dword ptr [rax]",
			"vpmovsxbq xmm2, xmm3",
			"vpmovsxbq xmm2, word ptr [rax+2]",
			"vpmovsxbq ymm2, xmm3",
			"vpmovsxbq ymm2, dword ptr [rax+4]",
			"vpmovsxbq zmm2, xmm3",
			"vpmovsxbq zmm2, qword ptr [rax+8]",
			"vpmovsqb xmm3{k3}, xmm2",
			"vpmovsqb word ptr [rax+2]{k3}, xmm2",
			"vpmovsqb xmm3{k3}, ymm2",
			"vpmovsqb dword ptr [rax+4]{k3}, ymm2",
			"vpmovsqb xmm3{k3}, zmm2",
			"vpmovsqb qword ptr [rax+8]{k3}, zmm2",
			"pmovsxwd xmm1, xmm5",
			"pmovsxwd xmm1, qword ptr [rax]",
			"vpmovsxwd xmm1, xmm5",
			"vpmovsxwd xmm2, qword ptr [rax]",
			"vpmovsxwd ymm1, xmm5",
			"vpmovsxwd ymm2, xmmword ptr [rax]",
			"vpmovsxwd xmm2, xmm3",
			"vpmovsxwd xmm2, qword ptr [rax+8]",
			"vpmovsxwd ymm2, xmm3",
			"vpmovsxwd ymm2, xmmword ptr [rax+0x10]",
			"vpmovsxwd zmm2, ymm3",
			"vpmovsxwd zmm2, ymmword ptr [rax+0x20]",
			"vpmovsdw xmm3{k3}, xmm2",
			"vpmovsdw qword ptr [rax+8]{k3}, xmm2",
			"vpmovsdw xmm3{k3}, ymm2",
			"vpmovsdw xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovsdw ymm3{k3}, zmm2",
			"vpmovsdw ymmword ptr [rax+0x20]{k3}, zmm2",
			"pmovsxwq xmm1, xmm5",
			"pmovsxwq xmm1, dword ptr [rax]",
			"vpmovsxwq xmm1, xmm5",
			"vpmovsxwq xmm2, dword ptr [rax]",
			"vpmovsxwq ymm1, xmm5",
			"vpmovsxwq ymm2, qword ptr [rax]",
			"vpmovsxwq xmm2, xmm3",
			"vpmovsxwq xmm2, dword ptr [rax+4]",
			"vpmovsxwq ymm2, xmm3",
			"vpmovsxwq ymm2, qword ptr [rax+8]",
			"vpmovsxwq zmm2, xmm3",
			"vpmovsxwq zmm2, xmmword ptr [rax+0x10]",
			"vpmovsqw xmm3{k3}, xmm2",
			"vpmovsqw dword ptr [rax+4]{k3}, xmm2",
			"vpmovsqw xmm3{k3}, ymm2",
			"vpmovsqw qword ptr [rax+8]{k3}, ymm2",
			"vpmovsqw xmm3{k3}, zmm2",
			"vpmovsqw xmmword ptr [rax+0x10]{k3}, zmm2",
			"pmovsxdq xmm1, xmm5",
			"pmovsxdq xmm1, qword ptr [rax]",
			"vpmovsxdq xmm1, xmm5",
			"vpmovsxdq xmm2, qword ptr [rax]",
			"vpmovsxdq ymm1, xmm5",
			"vpmovsxdq ymm2, xmmword ptr [rax]",
			"vpmovsxdq xmm2, xmm3",
			"vpmovsxdq xmm2, qword ptr [rax+8]",
			"vpmovsxdq ymm2, xmm3",
			"vpmovsxdq ymm2, xmmword ptr [rax+0x10]",
			"vpmovsxdq zmm2, ymm3",
			"vpmovsxdq zmm2, ymmword ptr [rax+0x20]",
			"vpmovsqd xmm3{k3}, xmm2",
			"vpmovsqd qword ptr [rax+8]{k3}, xmm2",
			"vpmovsqd xmm3{k3}, ymm2",
			"vpmovsqd xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovsqd ymm3{k3}, zmm2",
			"vpmovsqd ymmword ptr [rax+0x20]{k3}, zmm2",
			"vptestmb k2{k3}, xmm6, xmm3",
			"vptestmb k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestmb k2{k3}, ymm6, ymm3",
			"vptestmb k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestmb k2{k3}, zmm6, zmm3",
			"vptestmb k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestmw k2{k3}, xmm6, xmm3",
			"vptestmw k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestmw k2{k3}, ymm6, ymm3",
			"vptestmw k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestmw k2{k3}, zmm6, zmm3",
			"vptestmw k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestnmb k2{k3}, xmm6, xmm3",
			"vptestnmb k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestnmb k2{k3}, ymm6, ymm3",
			"vptestnmb k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestnmb k2{k3}, zmm6, zmm3",
			"vptestnmb k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestnmw k2{k3}, xmm6, xmm3",
			"vptestnmw k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestnmw k2{k3}, ymm6, ymm3",
			"vptestnmw k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestnmw k2{k3}, zmm6, zmm3",
			"vptestnmw k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestmd k2{k3}, xmm6, xmm3",
			"vptestmd k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestmd k2{k5}, xmm6, dword ptr [rax+4]{1to4}",
			"vptestmd k2{k3}, ymm6, ymm3",
			"vptestmd k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestmd k2{k5}, ymm6, dword ptr [rax+4]{1to8}",
			"vptestmd k2{k3}, zmm6, zmm3",
			"vptestmd k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestmd k2{k5}, zmm6, dword ptr [rax+4]{1to16}",
			"vptestmq k2{k3}, xmm6, xmm3",
			"vptestmq k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestmq k2{k5}, xmm6, qword ptr [rax+8]{1to2}",
			"vptestmq k2{k3}, ymm6, ymm3",
			"vptestmq k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestmq k2{k5}, ymm6, qword ptr [rax+8]{1to4}",
			"vptestmq k2{k3}, zmm6, zmm3",
			"vptestmq k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestmq k2{k5}, zmm6, qword ptr [rax+8]{1to8}",
			"vptestnmd k2{k3}, xmm6, xmm3",
			"vptestnmd k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestnmd k2{k5}, xmm6, dword ptr [rax+4]{1to4}",
			"vptestnmd k2{k3}, ymm6, ymm3",
			"vptestnmd k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestnmd k2{k5}, ymm6, dword ptr [rax+4]{1to8}",
			"vptestnmd k2{k3}, zmm6, zmm3",
			"vptestnmd k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestnmd k2{k5}, zmm6, dword ptr [rax+4]{1to16}",
			"vptestnmq k2{k3}, xmm6, xmm3",
			"vptestnmq k2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vptestnmq k2{k5}, xmm6, qword ptr [rax+8]{1to2}",
			"vptestnmq k2{k3}, ymm6, ymm3",
			"vptestnmq k2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vptestnmq k2{k5}, ymm6, qword ptr [rax+8]{1to4}",
			"vptestnmq k2{k3}, zmm6, zmm3",
			"vptestnmq k2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vptestnmq k2{k5}, zmm6, qword ptr [rax+8]{1to8}",
			"pmuldq xmm1, xmm5",
			"pmuldq xmm1, xmmword ptr [rax]",
			"vpmuldq xmm2, xmm6, xmm3",
			"vpmuldq xmm2, xmm6, xmmword ptr [rax]",
			"vpmuldq ymm2, ymm6, ymm3",
			"vpmuldq ymm2, ymm6, ymmword ptr [rax]",
			"vpmuldq xmm2{k3}{z}, xmm6, xmm3",
			"vpmuldq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpmuldq xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vpmuldq ymm2{k3}{z}, ymm6, ymm3",
			"vpmuldq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpmuldq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpmuldq zmm2{k3}{z}, zmm6, zmm3",
			"vpmuldq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpmuldq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"vpmovm2b xmm2, k3",
			"vpmovm2b ymm2, k3",
			"vpmovm2b zmm2, k3",
			"vpmovm2w xmm2, k3",
			"vpmovm2w ymm2, k3",
			"vpmovm2w zmm2, k3",
			"pcmpeqq xmm1, xmm5",
			"pcmpeqq xmm1, xmmword ptr [rax]",
			"vpcmpeqq xmm2, xmm6, xmm3",
			"vpcmpeqq xmm2, xmm6, xmmword ptr [rax]",
			"vpcmpeqq ymm2, ymm6, ymm3",
			"vpcmpeqq ymm2, ymm6, ymmword ptr [rax]",
			"vpcmpeqq k2{k3}, xmm6, xmm3",
			"vpcmpeqq k2, xmm6, xmmword ptr [rax+0x10]",
			"vpcmpeqq k2{k5}, xmm6, qword ptr [rax+8]{1to2}",
			"vpcmpeqq k2{k3}, ymm6, ymm3",
			"vpcmpeqq k2, ymm6, ymmword ptr [rax+0x20]",
			"vpcmpeqq k2{k5}, ymm6, qword ptr [rax+8]{1to4}",
			"vpcmpeqq k2{k3}, zmm6, zmm3",
			"vpcmpeqq k2, zmm6, zmmword ptr [rax+0x40]",
			"vpcmpeqq k2{k5}, zmm6, qword ptr [rax+8]{1to8}",
			"vpmovb2m k2, xmm3",
			"vpmovb2m k2, ymm3",
			"vpmovb2m k2, zmm3",
			"vpmovw2m k2, xmm3",
			"vpmovw2m k2, ymm3",
			"vpmovw2m k2, zmm3",
			"movntdqa xmm1, xmmword ptr [rax]",
			"vmovntdqa xmm2, xmmword ptr [rax]",
			"vmovntdqa ymm2, ymmword ptr [rax]",
			"vmovntdqa xmm2, xmmword ptr [rax+0x10]",
			"vmovntdqa ymm2, ymmword ptr [rax+0x20]",
			"vmovntdqa zmm2, zmmword ptr [rax+0x40]",
			"vpbroadcastmb2q xmm2, k3",
			"vpbroadcastmb2q ymm2, k3",
			"vpbroadcastmb2q zmm2, k3",
			"packusdw xmm1, xmm5",
			"packusdw xmm1, xmmword ptr [rax]",
			"vpackusdw xmm2, xmm6, xmm3",
			"vpackusdw xmm2, xmm6, xmmword ptr [rax]",
			"vpackusdw ymm2, ymm6, ymm3",
			"vpackusdw ymm2, ymm6, ymmword ptr [rax]",
			"vpackusdw xmm2{k3}{z}, xmm6, xmm3",
			"vpackusdw xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpackusdw xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vpackusdw ymm2{k3}{z}, ymm6, ymm3",
			"vpackusdw ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpackusdw ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpackusdw zmm2{k3}{z}, zmm6, zmm3",
			"vpackusdw zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpackusdw zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vmaskmovps xmm2, xmm6, xmmword ptr [rax]",
			"vmaskmovps ymm2, ymm6, ymmword ptr [rax]",
			"vscalefps xmm2{k3}{z}, xmm6, xmm3",
			"vscalefps xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vscalefps xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vscalefps ymm2{k3}{z}, ymm6, ymm3",
			"vscalefps ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vscalefps ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vscalefps zmm2{k3}{z}{ru-sae}, zmm6, zmm3",
			"vscalefps zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vscalefps zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vscalefpd xmm2{k3}{z}, xmm6, xmm3",
			"vscalefpd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vscalefpd xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vscalefpd ymm2{k3}{z}, ymm6, ymm3",
			"vscalefpd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vscalefpd ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vscalefpd zmm2{k3}{z}{ru-sae}, zmm6, zmm3",
			"vscalefpd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vscalefpd zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"vmaskmovpd xmm2, xmm6, xmmword ptr [rax]",
			"vmaskmovpd ymm2, ymm6, ymmword ptr [rax]",
			"vscalefss xmm2{k3}, xmm6, xmm3",
			"vscalefss xmm2{k3}, xmm6, dword ptr [rax+4]",
			"vscalefsd xmm2{k3}{z}, xmm6, xmm3",
			"vscalefsd xmm2{k3}, xmm6, qword ptr [rax+8]",
			"vmaskmovps xmmword ptr [rax], xmm6, xmm2",
			"vmaskmovps ymmword ptr [rax], ymm6, ymm2",
			"vmaskmovpd xmmword ptr [rax], xmm6, xmm2",
			"vmaskmovpd ymmword ptr [rax], ymm6, ymm2",
			"pmovzxbw xmm1, xmm5",
			"pmovzxbw xmm1, qword ptr [rax]",
			"vpmovzxbw xmm1, xmm5",
			"vpmovzxbw xmm2, qword ptr [rax]",
			"vpmovzxbw ymm1, xmm5",
			"vpmovzxbw ymm2, xmmword ptr [rax]",
			"vpmovzxbw xmm2, xmm3",
			"vpmovzxbw xmm2, qword ptr [rax+8]",
			"vpmovzxbw ymm2, xmm3",
			"vpmovzxbw ymm2, xmmword ptr [rax+0x10]",
			"vpmovzxbw zmm2, ymm3",
			"vpmovzxbw zmm2, ymmword ptr [rax+0x20]",
			"vpmovwb xmm3{k3}, xmm2",
			"vpmovwb qword ptr [rax+8]{k3}, xmm2",
			"vpmovwb xmm3{k3}, ymm2",
			"vpmovwb xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovwb ymm3{k3}, zmm2",
			"vpmovwb ymmword ptr [rax+0x20]{k3}, zmm2",
			"pmovzxbd xmm1, xmm5",
			"pmovzxbd xmm1, dword ptr [rax]",
			"vpmovzxbd xmm1, xmm5",
			"vpmovzxbd xmm2, dword ptr [rax]",
			"vpmovzxbd ymm1, xmm5",
			"vpmovzxbd ymm2, qword ptr [rax]",
			"vpmovzxbd xmm2, xmm3",
			"vpmovzxbd xmm2, dword ptr [rax+4]",
			"vpmovzxbd ymm2, xmm3",
			"vpmovzxbd ymm2, qword ptr [rax+8]",
			"vpmovzxbd zmm2, xmm3",
			"vpmovzxbd zmm2, xmmword ptr [rax+0x10]",
			"vpmovdb xmm3{k3}, xmm2",
			"vpmovdb dword ptr [rax+4]{k3}, xmm2",
			"vpmovdb xmm3{k3}, ymm2",
			"vpmovdb qword ptr [rax+8]{k3}, ymm2",
			"vpmovdb xmm3{k3}, zmm2",
			"vpmovdb xmmword ptr [rax+0x10]{k3}, zmm2",
			"pmovzxbq xmm1, xmm5",
			"pmovzxbq xmm1, word ptr [rax]",
			"vpmovzxbq xmm1, xmm5",
			"vpmovzxbq xmm2, word ptr [rax]",
			"vpmovzxbq ymm1, xmm5",
			"vpmovzxbq ymm2, dword ptr [rax]",
			"vpmovzxbq xmm2, xmm3",
			"vpmovzxbq xmm2, word ptr [rax+2]",
			"vpmovzxbq ymm2, xmm3",
			"vpmovzxbq ymm2, dword ptr [rax+4]",
			"vpmovzxbq zmm2, xmm3",
			"vpmovzxbq zmm2, qword ptr [rax+8]",
			"vpmovqb xmm3{k3}, xmm2",
			"vpmovqb word ptr [rax+2]{k3}, xmm2",
			"vpmovqb xmm3{k3}, ymm2",
			"vpmovqb dword ptr [rax+4]{k3}, ymm2",
			"vpmovqb xmm3{k3}, zmm2",
			"vpmovqb qword ptr [rax+8]{k3}, zmm2",
			"pmovzxwd xmm1, xmm5",
			"pmovzxwd xmm1, qword ptr [rax]",
			"vpmovzxwd xmm1, xmm5",
			"vpmovzxwd xmm2, qword ptr [rax]",
			"vpmovzxwd ymm1, xmm5",
			"vpmovzxwd ymm2, xmmword ptr [rax]",
			"vpmovzxwd xmm2, xmm3",
			"vpmovzxwd xmm2, qword ptr [rax+8]",
			"vpmovzxwd ymm2, xmm3",
			"vpmovzxwd ymm2, xmmword ptr [rax+0x10]",
			"vpmovzxwd zmm2, ymm3",
			"vpmovzxwd zmm2, ymmword ptr [rax+0x20]",
			"vpmovdw xmm3{k3}, xmm2",
			"vpmovdw qword ptr [rax+8]{k3}, xmm2",
			"vpmovdw xmm3{k3}, ymm2",
			"vpmovdw xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovdw ymm3{k3}, zmm2",
			"vpmovdw ymmword ptr [rax+0x20]{k3}, zmm2",
			"pmovzxwq xmm1, xmm5",
			"pmovzxwq xmm1, dword ptr [rax]",
			"vpmovzxwq xmm1, xmm5",
			"vpmovzxwq xmm2, dword ptr [rax]",
			"vpmovzxwq ymm1, xmm5",
			"vpmovzxwq ymm2, qword ptr [rax]",
			"vpmovzxwq xmm2, xmm3",
			"vpmovzxwq xmm2, dword ptr [rax+4]",
			"vpmovzxwq ymm2, xmm3",
			"vpmovzxwq ymm2, qword ptr [rax+8]",
			"vpmovzxwq zmm2, xmm3",
			"vpmovzxwq zmm2, xmmword ptr [rax+0x10]",
			"vpmovqw xmm3{k3}, xmm2",
			"vpmovqw dword ptr [rax+4]{k3}, xmm2",
			"vpmovqw xmm3{k3}, ymm2",
			"vpmovqw qword ptr [rax+8]{k3}, ymm2",
			"vpmovqw xmm3{k3}, zmm2",
			"vpmovqw xmmword ptr [rax+0x10]{k3}, zmm2",
			"pmovzxdq xmm1, xmm5",
			"pmovzxdq xmm1, qword ptr [rax]",
			"vpmovzxdq xmm1, xmm5",
			"vpmovzxdq xmm2, qword ptr [rax]",
			"vpmovzxdq ymm1, xmm5",
			"vpmovzxdq ymm2, xmmword ptr [rax]",
			"vpmovzxdq xmm2, xmm3",
			"vpmovzxdq xmm2, qword ptr [rax+8]",
			"vpmovzxdq ymm2, xmm3",
			"vpmovzxdq ymm2, xmmword ptr [rax+0x10]",
			"vpmovzxdq zmm2, ymm3",
			"vpmovzxdq zmm2, ymmword ptr [rax+0x20]",
			"vpmovqd xmm3{k3}, xmm2",
			"vpmovqd qword ptr [rax+8]{k3}, xmm2",
			"vpmovqd xmm3{k3}, ymm2",
			"vpmovqd xmmword ptr [rax+0x10]{k3}, ymm2",
			"vpmovqd ymm3{k3}, zmm2",
			"vpmovqd ymmword ptr [rax+0x20]{k3}, zmm2",
			"vpermd ymm2, ymm6, ymm3",
			"vpermd ymm2, ymm6, ymmword ptr [rax]",
			"vpermd ymm2{k3}{z}, ymm6, ymm3",
			"vpermd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpermd ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpermd zmm2{k3}{z}, zmm6, zmm3",
			"vpermd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermd zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vpermq ymm2{k3}{z}, ymm6, ymm3",
			"vpermq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpermq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpermq zmm2{k3}{z}, zmm6, zmm3",
			"vpermq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpermq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"pcmpgtq xmm1, xmm5",
			"pcmpgtq xmm1, xmmword ptr [rax]",
			"vpcmpgtq xmm2, xmm6, xmm3",
			"vpcmpgtq xmm2, xmm6, xmmword ptr [rax]",
			"vpcmpgtq ymm2, ymm6, ymm3",
			"vpcmpgtq ymm2, ymm6, ymmword ptr [rax]",
			"vpcmpgtq k2{k3}, xmm6, xmm3",
			"vpcmpgtq k2, xmm6, xmmword ptr [rax+0x10]",
			"vpcmpgtq k2{k5}, xmm6, qword ptr [rax+8]{1to2}",
			"vpcmpgtq k2{k3}, ymm6, ymm3",
			"vpcmpgtq k2, ymm6, ymmword ptr [rax+0x20]",
			"vpcmpgtq k2{k5}, ymm6, qword ptr [rax+8]{1to4}",
			"vpcmpgtq k2{k3}, zmm6, zmm3",
			"vpcmpgtq k2, zmm6, zmmword ptr [rax+0x40]",
			"vpcmpgtq k2{k5}, zmm6, qword ptr [rax+8]{1to8}",
			"pminsb xmm1, xmm5",
			"pminsb xmm1, xmmword ptr [rax]",
			"vpminsb xmm2, xmm6, xmm3",
			"vpminsb xmm2, xmm6, xmmword ptr [rax]",
			"vpminsb ymm2, ymm6, ymm3",
			"vpminsb ymm2, ymm6, ymmword ptr [rax]",
			"vpminsb xmm2{k3}, xmm6, xmm3",
			"vpminsb xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpminsb ymm2{k3}, ymm6, ymm3",
			"vpminsb ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpminsb zmm2{k3}, zmm6, zmm3",
			"vpminsb zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpmovm2d xmm2, k3",
			"vpmovm2d ymm2, k3",
			"vpmovm2d zmm2, k3",
			"vpmovm2q xmm2, k3",
			"vpmovm2q ymm2, k3",
			"vpmovm2q zmm2, k3",
			"pminsd xmm1, xmm5",
			"pminsd xmm1, xmmword ptr [rax]",
			"vpminsd xmm2, xmm6, xmm3",
			"vpminsd xmm2, xmm6, xmmword ptr [rax]",
			"vpminsd ymm2, ymm6, ymm3",
			"vpminsd ymm2, ymm6, ymmword ptr [rax]",
			"vpminsd xmm2{k3}{z}, xmm6, xmm3",
			"vpminsd xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpminsd xmm2{k5}{z}, xmm6, dword ptr [rax+4]{1to4}",
			"vpminsd ymm2{k3}{z}, ymm6, ymm3",
			"vpminsd ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpminsd ymm2{k5}{z}, ymm6, dword ptr [rax+4]{1to8}",
			"vpminsd zmm2{k3}{z}, zmm6, zmm3",
			"vpminsd zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpminsd zmm2{k5}{z}, zmm6, dword ptr [rax+4]{1to16}",
			"vpminsq xmm2{k3}{z}, xmm6, xmm3",
			"vpminsq xmm2{k3}, xmm6, xmmword ptr [rax+0x10]",
			"vpminsq xmm2{k5}{z}, xmm6, qword ptr [rax+8]{1to2}",
			"vpminsq ymm2{k3}{z}, ymm6, ymm3",
			"vpminsq ymm2{k3}, ymm6, ymmword ptr [rax+0x20]",
			"vpminsq ymm2{k5}{z}, ymm6, qword ptr [rax+8]{1to4}",
			"vpminsq zmm2{k3}{z}, zmm6, zmm3",
			"vpminsq zmm2{k3}, zmm6, zmmword ptr [rax+0x40]",
			"vpminsq zmm2{k5}{z}, zmm6, qword ptr [rax+8]{1to8}",
			"vpmovd2m k2, xmm3",
			"vpmovd2m k2, ymm3",
			"vpmovd2m k2, zmm3",
			"vpmovq2m k2, xmm3",
			"vpmovq2m k2, ymm3",
			"vpmovq2m k2, zmm3",
			"pminuw xmm1, xmm5",
		};
	}
}
#endif
