// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

namespace Generator.Tables.CSharp {
	// It's generated by a C# cctor
	[Generator(TargetLanguage.CSharp)]
	sealed class CSharpRegisterInfoTableGenerator {
		public CSharpRegisterInfoTableGenerator(GeneratorContext generatorContext) { }
		public void Generate() { }
	}
}
