// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if MVEX
using System;

namespace Iced.Intel {
	[Flags]
	enum MvexInfoFlags2 {
		None = 0x00000000,
		NoSaeRoundingControl = 0x00000001,
		ConvFn32 = 0x00000002,
		IgnoresEvictionHint = 0x00000004,
	}
}
#endif
