/*
Copyright (C) 2018-2019 de4dot@gmail.com

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if DECODER || ENCODER
namespace Iced.Intel {
	/// <summary>Tuple type (EVEX) which can be used to get the disp8 scale factor <c>N</c></summary>
	public enum TupleType {
		/// <summary><c>N = 1</c></summary>
		N1 = 0,
		/// <summary><c>N = 2</c></summary>
		N2 = 1,
		/// <summary><c>N = 4</c></summary>
		N4 = 2,
		/// <summary><c>N = 8</c></summary>
		N8 = 3,
		/// <summary><c>N = 16</c></summary>
		N16 = 4,
		/// <summary><c>N = 32</c></summary>
		N32 = 5,
		/// <summary><c>N = 64</c></summary>
		N64 = 6,
		/// <summary><c>N = b ? 4 : 8</c></summary>
		N8b4 = 7,
		/// <summary><c>N = b ? 4 : 16</c></summary>
		N16b4 = 8,
		/// <summary><c>N = b ? 4 : 32</c></summary>
		N32b4 = 9,
		/// <summary><c>N = b ? 4 : 64</c></summary>
		N64b4 = 10,
		/// <summary><c>N = b ? 8 : 16</c></summary>
		N16b8 = 11,
		/// <summary><c>N = b ? 8 : 32</c></summary>
		N32b8 = 12,
		/// <summary><c>N = b ? 8 : 64</c></summary>
		N64b8 = 13,
	}
}
#endif
